### DISCUSSION TITLE
YAML build filter (`when:changeset:includes`) not working with Azure DevOps

### DISCUSSION THREAD

**Discussion by zbecknell** [codemagic-ci-cd/codemagic-docs#1055] [Q&A]
I have a Flutter app shared with non-flutter projects.  I need to trigger a build only when changes happen in the Flutter project directory.  This doesn't seem to be working -- maybe it's because I'm using Azure DevOps service hooks?

Here's the start of my build file:

```yaml
workflows:
  default-workflow:
    name: Default Workflow
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: dev
          include: true
          source: false
      tag_patterns:
        - pattern: '*'
          include: true
    when:
      changeset:
        includes:
          - 'src/MyProjectLocation/'
  ```
