### DISCUSSION TITLE
Dynamic global environment

### DISCUSSION THREAD

**Discussion by gopherios** [codemagic-ci-cd/codemagic-docs#1080] [Q&A] [answered]
Hi everyone!

I need to set $APP_STORE_CONNECT_PRIVATE_KEY and other global vars in codemagic.yaml file. Not in "Environment variables" tab! Inside codemagic.yaml)

But! If i set in one script then after try read in another script var is not available. And not available in publishing.

How to solve this problem?

Thanks!

**Comment by todah-zg** [comment, marked as answer]
Please follow [this guide](https://docs.codemagic.io/yaml-basic-configuration/using-environment-variables/#setting-environment-variables-at-build-time) on how to set environment variables during builds.

In short, you can save the variable to the $CM_ENV file in one script to be able to access it in subsequent scripts.
``` yaml
scripts:
  - name: Step 1
    script: |
       echo "APP_STORE_CONNECT_PRIVATE_KEY='my secret value'" >> $CM_ENV
  - name: Step 2
    script: |
       echo $APP_STORE_CONNECT_PRIVATE_KEY
```
