### DISCUSSION TITLE
`Cannot save Signing Certificates without certificate private key` when auto signing an iOS app

### DISCUSSION THREAD

**Discussion by yod527** [codemagic-ci-cd/codemagic-docs#1117] [Q&A]
Hello everyone!

Struggling with automatic codesiging for my react-native ios app + testflight build publishing.

**I've did everything in Teams tab, rather than private application configuration, so no variables with certificates was added, and configuration looks like that**
```
        environment:
            ios_signing:
              distribution_type: app_store # or: ad_hoc | development | enterprise
              bundle_identifier: xxx.xxxxx.xx
        publishing:
          app_store_connect:
            # Use referenced App Store Connect API key to authenticate binary upload
            auth: integration
            submit_to_testflight: true
            beta_groups:
              - better-testers
            submit_to_app_store: false
```
I've configured an integration with appsore connect.
Issued an appstore distribution certificate (via codemagic)
Via apple developer I've created an appstore distribution profile, and later imported it via codemagic.

Still getting errors, and didn't know actually where can I dig, any help will be appreciated...

build id 635fe4430edd57f76d8ba08b
