### DISCUSSION TITLE
Auto trigger on 2 branches only

### DISCUSSION THREAD

**Discussion by smitmartijn** [codemagic-ci-cd/codemagic-docs#1143] [Q&A] [answered]
Hi, 

I'm trying to get a codemagic.yaml in place that'll automatically trigger builds on 2 branches: `release` and `beta` and I'm hoping someone here can provide guidance. The documentation only has single branch examples..So far, I've tried this:

```
    triggering:
      branch_patterns:
        - pattern: '*'
          include: false
        - pattern: 'release'
          include: true
        - pattern: 'beta'
          include: true
      events:
        - push
      cancel_previous_builds: true
```
And without the initial exclude:
```
    triggering:
      branch_patterns:
        - pattern: 'release'
          include: true
        - pattern: 'beta'
          include: true
      events:
        - push
      cancel_previous_builds: true
```
Also tried with regex:
```
    triggering:
      branch_patterns:
        - pattern: '[beta|release]'
          include: true
      events:
        - push
      cancel_previous_builds: true
```
But none of these trigger automatic builds. 

I did find semi-success with this:

```
workflows:
  beta:
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "beta"
          include: true
    scripts:
      - *step_1
      - *step_2
  release:
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "release"
          include: true
    scripts:
      - *step_1
      - *step_2
```

However, I have over 20 steps and I'd like to avoid repeating the `scripts` block, if possible. 

Can anyone point me in the right direction? Thanks!
