### DISCUSSION TITLE
Failed to set code signing settings for node_modules/lottie-ios/script/test-carthage/Carthage/Checkouts/lottie-ios/Lottie.xcodeproj

### DISCUSSION THREAD

**Discussion by Congregate-App** [codemagic-ci-cd/codemagic-docs#1217] [Q&A] [answered]
Hi there.

We're working on a React Native app we're trying to use CI/CD tools to allow devs (like me) who do not have a Mac to build and publish the app on Test Flight.
When running the build on Codemagic, I am getting an error that seems to be triggered by the Lottie library we use in the app.
Here's the build ID: 6391aab536a64119ad2bd6b1

I do not understand what triggers the error. I have followed the steps [here](https://docs.codemagic.io/yaml-code-signing/signing-ios/) and the signing seems to work fine. It's just Lottie for which there seems to be no code signing.

I'd also appreciate if someone could explain why this fails specifically because of Lottie.

```
Configure code signing settings
Searching for files matching /Users/builder/Library/MobileDevice/Provisioning Profiles/*.mobileprovision
Searching for files matching /Users/builder/Library/MobileDevice/Provisioning Profiles/*.provisionprofile
List available code signing certificates in keychain /Users/builder/Library/codemagic-cli-tools/keychains/08-12-22_93qbsvor.keychain-db
Searching for files matching /Users/builder/clone/**/*.xcodeproj
Failed to set code signing settings for node_modules/lottie-ios/script/test-carthage/Carthage/Checkouts/lottie-ios/Lottie.xcodeproj


Build failed :|
Step 10 script `Set up provisioning profiles settings on Xcode project` exited with status code 1
```

And here is the `codemagic.yaml` file, where I need to update lottie-ios to a specific version to prevent Cocoapods from throwing a mismatched dependency error. The script fails at "Set up provisioning profiles settings on Xcode project"

```
workflows:
    react-native-ios:
      name: React Native iOS
      max_build_duration: 120
      instance_type: mac_mini_m1
      integrations:
        app_store_connect: Wavier Company Codemagic
      environment:
        ios_signing:
          distribution_type: app_store
          bundle_identifier: com.wavier
        vars:
          BUNDLE_ID: "com.wavier"
          XCODE_WORKSPACE: "BarbApp.xcworkspace" 
      scripts:
        - name: Deal with Sass
          script: |
            yarn remove node-sass
            yarn add sass
        - name: Update lottie-ios
          script: | 
            yarn add lottie-ios@3.4.0
        - name: Install Yarn dep
          script: | 
            yarn install
        - name: Update node-gyp
          script: |
            npm explore npm/node_modules/@npmcli/run-script -g -- npm_config_global=false npm install node-gyp@latest
        - name: Install CocoaPods dependencies
          script: |
            cd ios
            pod install
        - name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
          script: |
            keychain initialize
        - name: Use system default keychain
          script: |
            keychain add-certificates
        - name: Set up provisioning profiles settings on Xcode project
          script: xcode-project use-profiles 
        - name: Build ipa for distribution
          script: | 
            xcode-project build-ipa --workspace "$CM_BUILD_DIR/ios/$XCODE_WORKSPACE"
  #           --scheme "$XCODE_SCHEME"
      artifacts:
        - build/ios/ipa/*.ipa
        - /tmp/xcodebuild_logs/*.log
        - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
        - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
      publishing:
        email:
          recipients:
            - osfieldgaga@gmail.com
        app_store_connect:
          auth: integration
```

Thanks in advance for your help!
