### DISCUSSION TITLE
Build failed: No "teamID" specified and no team ID found in the archive

### DISCUSSION THREAD

**Discussion by UnknownBaronX** [codemagic-ci-cd/codemagic-docs#1247] [Q&A] [answered]
I am currently getting used to codemagic with all its features.

I want to build an iOS build with ad_hoc. Before I added the 'Developer Portal' key, profiles and certs successfully.

While build my app it fails at "buiid ipa and automatic versioning" with following error:

```
Running "flutter pub get" in clone...                              625ms

💪 Building with sound null safety 💪

Archiving com.company.appname...
Automatically signing iOS for device deployment using specified development team in Xcode project: XXXXXXXX
Running pod install...                                           1,561ms
Running Xcode build...                                          
Xcode archive done.                                         62.7s
Built /Users/builder/clone/build/ios/archive/Runner.xcarchive.
Building App Store IPA...                                        2,370ms
Encountered error while creating the IPA:
error: exportArchive: No "teamID" specified and no team ID found in the archive

Try distributing the app in Xcode: "open /Users/builder/clone/build/ios/archive/Runner.xcarchive" 
```

Current codemagic xaml:

```
workflows:
  ios-workflow:
    name: iOS Workflow ad-hoc
    environment:
      ios_signing:
        provisioning_profiles:
            - Ad-Hoc profile
        certificates:
            - Codemagic Cert
    scripts:
        - script: xcode-project use-profiles
        - script: flutter packages pub get
        - name: set up code signing settings on xcode project
          script: xcode-project use-profiles
        - name: Flutter build ipa and automatic versioning
          script: flutter build ipa 
    artifacts:
        - build/ios/ipa/*.ipa
```
