### DISCUSSION TITLE
Build fail with error: Unable to decrypt environment variable

### DISCUSSION THREAD

**Discussion by morsagmon** [codemagic-ci-cd/codemagic-docs#1270] [Q&A] [answered]
Hello team!

I attempted my first build, and received the following error:
`Unable to decrypt environment variable CAPACITOR_CONFIG_TS: Invalid encryption key - encrypted variables work only with builds in the same team they were created with`

I am on a free personal account, no teams were ever created.
I generated the base64 encrypted strings using this external service: [Base64Encode](https://www.base64encode.org/).

My yaml file:

```
# DEV Workflow
workflows:
  android-workflow:           # workflow ID
    name: Android Workflow    # workflow name displayed in UI
    instance_type: mac_mini_m1   # machine type to use (currently supported: `mac_mini`, `mac_pro`, `linux`, `linux_x2`)
    max_build_duration: 30    # build duration in minutes (min 1, max 120)
    environment:
      vars:             # Define your environment variables here
        CAPACITOR_CONFIG_TS: Encrypted(aW1wb3J0IHsgQ...)
        CAPACITOR_CONFIG_JSON: Encrypted(ewoJImFwcElk...)
        GOOGLE_SERVICES_INFO_PLIST: Encrypted(PD94bWwgdmVyc2lv...)
        ANDROID_MANIFEST: Encrypted(PD94bWwgdmVyc2lv...)
        GOOGLE_SERVICES_JSON: Encrypted(ewogICJwcm9qZWN0X2l...)
        BUILD_GRADLE: Encrypted(YXBwbHkgcGx1Z2luOiAnY29...)
      node: default     # Define default, latest, current, lts, carbon (or another stream), nightly or version
      npm: default       # Define default, latest, next, lts or version
      ndk: default         # Define default or revision (e.g., r19c)
    cache:
      cache_paths:    
      - $HOME/.gradle/caches              # Gradle cache
    triggering:
      events:
        - push
      branch_patterns:              # Include or exclude watched branches
        - pattern: 'DEV'
          include: true
    scripts:
      - name: Install npm dependencies for Ionic project
        script: |
          npm install
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Update dependencies and copy web assets to native project
        script: |
          # npx cap copy # <- use this is you don't need to update native dependencies
          npx cap sync # <- update native dependencies and copy web assets to native project
      - name: Decrypt Firebase environment vars
        script: |
          #!/bin/sh
          echo $CAPACITOR_CONFIG_TS | base64 --decode > $CM_BUILD_DIR/capacitor.config.ts
          echo $CAPACITOR_CONFIG_JSON | base64 --decode > $CM_BUILD_DIR/ios/App/App/capacitor.config.json
          echo $GOOGLE_SERVICES_INFO_PLIST | base64 --decode > $CM_BUILD_DIR/ios/Runner/GoogleService-Info.plist
          echo $ANDROID_MANIFEST | base64 --decode > $CM_BUILD_DIR/android/app/src/main/AndroidManifest.xml
          echo $GOOGLE_SERVICES_JSON | base64 --decode > $CM_BUILD_DIR/android/app/google-services.json
          echo $BUILD_GRADLE | base64 --decode > $CM_BUILD_DIR/android/app/build.gradle
      - name: Build Android DEBUG
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - myname@mydomain.com
        notify:
          success: true
          failure: true
```

What am I missing please/?
