### DISCUSSION TITLE
Build error gradle

### DISCUSSION THREAD

**Discussion by morsagmon** [codemagic-ci-cd/codemagic-docs#1275] [Q&A]
Hello team!

Running a build I receive this error:

`Failed to create parent directory '/android' when creating directory '/android/app/generated/source/buildConfig/debug'`

It is raised in this command:
`./gradlew assembleDebug`

Trying to get more info with --info or --debug I ended up with no more valuable info.

On my local machine there is no problem.

Searching around it usually about clearing old files and refreshing the project (in Android Studio), or admin permissions required, but I guess every run here is starting clean, and I don't really have control over the server running this.

Any pointers to help me out of this?
Thanks!

Complete yaml file here:

```
# DEV Workflow
workflows:
  android-workflow:           # workflow ID
    name: Android Workflow    # workflow name displayed in UI
    instance_type: mac_mini_m1   # machine type to use (currently supported: `mac_mini`, `mac_pro`, `linux`, `linux_x2`)
    max_build_duration: 30    # build duration in minutes (min 1, max 120)
    environment:
      groups:             # Define your environment variables here
        - DEV_VARIABLES
      node: 16.16.0     # Define default, latest, current, lts, carbon (or another stream), nightly or version
      npm: 8.11.0       # Define default, latest, next, lts or version
      ndk: default         # Define default or revision (e.g., r19c)
    cache:
      cache_paths:    
      - $HOME/.gradle/caches              # Gradle cache
    triggering:
      events:
        - push
      branch_patterns:              # Include or exclude watched branches
        - pattern: 'DEV'
          include: true      
    scripts:
      - name: Install npm dependencies for Ionic project
        script: |
          npm install --force
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Update dependencies and copy web assets to native project
        script: |
          npx cap copy # <- use this is you don't need to update native dependencies
          # npx cap sync # <- update native dependencies and copy web assets to native project
      - name: Decrypt Firebase environment vars
        script: |
          #!/bin/sh
          echo $DEV_ANGULAR_ENV | base64 --decode > $CM_BUILD_DIR/src/environments/environment.ts
          echo $DEV_CAPACITOR_CONFIG_TS | base64 --decode > $CM_BUILD_DIR/capacitor.config.ts
          echo $DEV_CAPACITOR_CONFIG_JSON | base64 --decode > $CM_BUILD_DIR/ios/App/App/capacitor.config.json
          echo $DEV_GOOGLE_SERVICES_INFO_PLIST | base64 --decode > $CM_BUILD_DIR/ios/Runner/GoogleService-Info.plist
          echo $DEV_ANDROID_MANIFEST | base64 --decode > $CM_BUILD_DIR/android/app/src/main/AndroidManifest.xml
          echo $DEV_GOOGLE_SERVICES_JSON | base64 --decode > $CM_BUILD_DIR/android/app/google-services.json
          echo $DEV_BUILD_GRADLE | base64 --decode > $CM_BUILD_DIR/android/app/build.gradle
      - name: Build Android DEBUG
        script: |
          cd android
          ./gradlew clean
          ./gradlew assembleDebug          

    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - mor@simplify.study
        notify:
          success: true
          failure: true

```
