### DISCUSSION TITLE
Codemagic.yaml how to run script only if version.txt has change then only

### DISCUSSION THREAD

**Discussion by abhiddreambolix** [codemagic-ci-cd/codemagic-docs#1306] [Q&A] [answered]
I want the script to run only one certain condition that is we push changes contains version.txt file the build and deploy

**Comment by himesh-cm** [comment, marked as answer]
Hi @abhiddreambolix,
You can do something like this, you can read more about it [here](https://docs.codemagic.io/yaml-running-builds/starting-builds-automatically/#using-changeset-inside-when).

```
workflows:
  sample-workflow:
    name: Sample App workflow
    triggering:
      events:
        - push
    when:
      changeset:
        includes:
          - 'path/to/version.txt'
```
