### DISCUSSION TITLE
How to choose an Android and iOS emulator to run Flutter integration tests?

### DISCUSSION THREAD

**Discussion by mregnauld** [codemagic-ci-cd/codemagic-docs#1320] [Q&A] [answered]
Hello,

In my `codemagic.yaml` file, I would like to run my integration tests for my Flutter app using the following scripts, following [the documentation](https://docs.codemagic.io/yaml-testing/testing/):

```yaml
workflows:
  tests-workflow:
    name: Tests Workflow
    max_build_duration: 60
    instance_type: mac_mini
    environment:
      flutter: stable
      xcode: latest
      cocoapods: 1.9.1
    scripts:
      - name: Integration tests Android
        script: |
          flutter emulators --launch emulator &
          adb wait-for-device
          flutter -d emulator-5554 test --machine > test-results/flutter.json integration_test --flavor free
        test_report: test-results/flutter.json
      - name: Integration tests iOS
        script: |
          flutter emulators --launch apple_ios_simulator
          flutter -d iPhone test --machine > test-results/flutter.json integration_test --flavor free
        test_report: test-results/flutter.json
```

Is it possible to choose which Android emulator and which iOS emulator to run?

Thanks.
