### DISCUSSION TITLE
The mac_mini instance type does not support the selected Xcode version.

### DISCUSSION THREAD

**Discussion by mregnauld** [codemagic-ci-cd/codemagic-docs#1323] [Q&A]
I tried to execute the following workflow:

```yaml
  emulators-workflow:
    name: Available emulators
    max_build_duration: 10
    instance_type: mac_mini
    environment:
      flutter: stable
      xcode: latest
      cocoapods: 1.9.1
    scripts:
      - name: Available emulators
        script: flutter emulators
```

But as soon as I launch it, I get the following error:
```
The mac_mini instance type does not support the selected Xcode version. Please consider using mac_pro or mac_mini_m1 instead.
```

Why isn't that working on Mac mini?
