### DISCUSSION TITLE
"No devices are connected" when running a Flutter integration test

### DISCUSSION THREAD

**Discussion by mregnauld** [codemagic-ci-cd/codemagic-docs#1327] [Q&A] [answered]
In my workflow, I want to run integration tests for my Flutter app, by running those scripts:

```yaml
- name: Install pods
  script: |
    find . -name "Podfile" -execdir pod install \;
- name: Integration tests iOS
  script: |
    flutter emulators --launch apple_ios_simulator
    flutter -d iPhone test --machine > test-results/flutter.json integration_test --flavor free
  test_report: test-results/flutter.json
```

But for some reason, I got the following error:

```
No devices are connected. Ensure that `flutter doctor` shows at least one connected device

Build failed :|
Step 7 script `Integration tests iOS` exited with status code 1
```

What did I do wrong?

Thanks.
