### DISCUSSION TITLE
No matching certificate found for every requested profile

### DISCUSSION THREAD

**Discussion by tiger5226** [codemagic-ci-cd/codemagic-docs#1396] [Q&A]
This is not telling me much information. What should I check in the event I get this error? I can fetch the profile from the API I set up from the Codemagic UI. I can also fetch the certificate for it. Below is the relevant section of my yaml:

```yaml
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    integrations:
      app_store_connect: <codemagic ref name for api integration>
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: <explicit bundle id of app>
      vars:
        APP_ID: <myappid>
      flutter: stable
      xcode: latest
      cocoapods: default
```

Any help would be appreciated. I have another project using the workflow instead of yaml on a team account but it connects to the same apple developer account. I can't seem to switch from yaml to workflow though. Might be because the team account is a paid account this personal one is a free account.
