### DISCUSSION TITLE
One base project include two projects. How can i set codemagic.yaml two tag creation

### DISCUSSION THREAD

**Discussion by DestechHasarWebsiteleri** [codemagic-ci-cd/codemagic-docs#1416] [Q&A]
One base project include two projects. How can i set codemagic.yaml two tag creation

**Comment by icarusdust** [comment]
Hi @DestechHasarWebsiteleri, you can target the project that you want to build by using `working_directory` in yaml:

```
workflows:
  second-workflow:
    name: Second workflow
    working_directory: second_app
```

Or choose the directory from dropdown in the Workflow Editor. More info in the blog post: https://blog.codemagic.io/codemagic-monorepo/
Then you can create your tags accordingly.
