### DISCUSSION TITLE
Failed to set code signing settings for Pods/._Pods.xcodeproj

### DISCUSSION THREAD

**Discussion by jomart1985** [codemagic-ci-cd/codemagic-docs#1419] [Q&A]
i received this error when try to build my project in code-magic :
Failed to set code signing settings for Pods/._Pods.xcodeproj
this my yaml file settings :

```
workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: CodemagicSign
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: noon.team.mn
      vars:
        BUNDLE_ID: "noon.team.mn"
        XCODE_WORKSPACE: "WKWebViewLocalAssetsObjC.xcworkspace"
        XCODE_SCHEME: "WKWebViewLocalAssetsObjC"
        APP_ID: V25LVKC5NA.noon.team.mn
    scripts:
      - name: Set up provisioning profiles settings on Xcode project
        script: xcode-project use-profiles
      - name: Build ipa for distribution
        script: | 
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - jomart1985@mail.com
        notify:
          success: true
          failure: false 
```

**Comment by jomart1985** [comment]
im now get this new error:

```
▸ Compiling GULKeychainUtils.m
▸ Compiling GULKeychainStorage.m
▸ Compiling GULHeartbeatDateStorageUserDefaults.m
▸ Compiling GULHeartbeatDateStorage.m
▸ Compiling GULAppEnvironmentUtil.m
▸ Compiling GULAppDelegateSwizzler.m
▸ Generating 'EARestrictedScrollView.framework.dSYM'
▸ Touching EARestrictedScrollView.framework (in target 'EARestrictedScrollView' from project 'Pods')
▸ Copying EAIntroView.h
▸ Copying EAIntroView-umbrella.h
▸ Copying EAIntroPage.h
▸ Processing EAIntroView-Info.plist
▸ Compiling EAIntroView.m
▸ Compiling EAIntroView_vers.c
▸ Compiling EAIntroView-dummy.m
▸ Compiling EAIntroPage.m
▸ Linking GoogleUtilities
▸ Generating 'GoogleUtilities.framework.dSYM'
▸ Linking EAIntroView
▸ Touching GoogleUtilities.framework (in target 'GoogleUtilities' from project 'Pods')
▸ Running script '[CP] Copy XCFrameworks'
▸ Copying GoogleDataTransport.h
▸ Copying GoogleDataTransport-umbrella.h
▸ Copying GDTCORTransport.h
▸ Copying GDTCORTargets.h
▸ Copying GDTCOREventTransformer.h
▸ Copying GDTCOREventDataObject.h
▸ Copying GDTCOREvent.h
▸ Copying GDTCOREndpoints.h
▸ Copying GDTCORConsoleLogger.h
▸ Copying GDTCORClock.h
▸ Processing GoogleDataTransport-Info.plist
▸ Copying FirebaseCoreInternal-umbrella.h
▸ Compiling client_metrics.nanopb.c
▸ Compiling cct.nanopb.c
Failed to archive /Users/builder/clone/WKWebViewLocalAssetsObjC.xcworkspace. The following build commands failed:

PhaseScriptExecution [CP]\ Copy\ XCFrameworks /Users/builder/Library/Developer/Xcode/DerivedData/WKWebViewLocalAssetsObjC-fvxxuqufqsqmowcfufxditimurkx/Build/Intermediates.noindex/ArchiveIntermediates/WKWebViewLocalAssetsObjC/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/GoogleAppMeasurement.build/Script-A46CB35DA72DB1B804CC07D56033370E.sh (in target 'GoogleAppMeasurement' from project 'Pods')
	...
	cd /Users/builder/clone/Pods
	/Applications/Xcode-14.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c -target arm64-apple-ios11.0 -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -std\=c99 -fmodules -gmodules -fmodules-cache-path\=/Users/builder/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -fmodules-prune-interval\=86400 -fmodules-prune-after\=345600 -fbuild-session-file\=/Users/builder/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror\=non-modular-include-in-framework-module -fmodule-name\=GoogleDataTransport -Wno-trigraphs -fpascal-strings -Os -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror\=return-type -Wdocumentation -Wunreachable-code -Werror\=deprecated-objc-isa-usage -Werror\=objc-root-class -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-implicit-fallthrough -DPOD_CONFIGURATION_RELEASE\=1 -DCOCOAPODS\=1 -DPB_FIELD_32BIT\=1 -DPB_NO_PACKED_STRUCTS\=1 -DPB_ENABLE_MALLOC\=1GDTCOR_VERSION\=9.2.1 -isysroot /Applications/Xcode-14.2.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk -fstrict-aliasing -Wdeprecated-declarations -g -Wno-sign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wno-semicolon-before-method-body -Wunguarded-availability -iquote /Users/builder/Library/Developer/Xcode/DerivedData/WKWebViewLocalAssetsObjC-fvxxuqufqsqmowcfufxditimurkx/Build/Intermediates.noindex/ArchiveIntermediates/WKWebViewLocalAssetsObjC/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/GoogleDataTransport.build/GoogleDataTransport-generated-files.hmap -I/Users/builder/Library/Developer/Xcode/DerivedData/WKWebViewLocalAssetsObjC-fvxxuqufqsqmowcfufxditimurkx/Build/Intermediates.noindex/ArchiveIntermediates/WKWebViewLocalAssetsObjC/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/GoogleDataTransport.build/GoogleDataTransport-own-target-headers.hmap -I/Users/builder/Library/Developer/Xcode/DerivedData/WKWebViewLocalAssetsObjC-fvxxuqufqsqmowcfufxditimurkx/Build/Intermediates.noindex/ArchiveIntermediates/WKWebViewLocalAssetsObjC/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/GoogleDataTransport.build/GoogleDataTransport-all-non-framework-target-headers.hmap -ivfsoverlay /Users/builder/Library/Developer/Xcode/DerivedData/WKWebViewLocalAssetsObjC-fvxxuqufqsqmowcfufxditimurkx/Build/Intermediates.noindex/ArchiveIntermediates/WKWebViewLocalAssetsObjC/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/GoogleDataTransport.build/all-product-headers.yaml -iquote /Users/builder/Library/Developer/Xcode/DerivedData/WKWebViewLocalAssetsObjC-fvxxuqufqsqmowcfufxditimurkx/Build/Intermediates.noindex/ArchiveIntermediates/WKWebViewLocalAssetsObjC/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/GoogleDataTransport.build/GoogleDataTransport-project-headers.hmap -I/Users/builder/Library/Developer/Xcode/DerivedData/WKWebViewLocalAssetsObjC-fvxxuqufqsqmowcfufxditimurkx/Build/Intermediates.noindex/ArchiveIntermediates/WKWebViewLocalAssetsObjC/BuildProductsPath/Release-iphoneos/GoogleDataTransport/include -I/Users/builder/clone/Pods/GoogleDataTransport -I/Users/builder/Library/Developer/Xcode/DerivedData/WKWebViewLocalAssetsObjC-fvxxuqufqsqmowcfufxditimurkx/Build/Intermediates.noindex/ArchiveIntermediates/WKWebViewLocalAssetsObjC/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/GoogleDataTransport.build/DerivedSources-normal/arm64 -I/Users/builder/Library/Developer/Xcode/DerivedData/WKWebViewLocalAssetsObjC-fvxxuqufqsqmowcfufxditimurkx/Build/Intermediates.noindex/ArchiveIntermediates/WKWebViewLocalAssetsObjC/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/GoogleDataTransport.build/DerivedSources/arm64 -I/Users/builder/Library/Developer/Xcode/DerivedData/WKWebViewLocalAssetsObjC-fvxxuqufqsqmowcfufxditimurkx/Build/Intermediates.noindex/ArchiveIntermediates/WKWebViewLocalAssetsObjC/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/GoogleDataTransport.build/DerivedSources -F/Users/builder/Library/Developer/Xcode/DerivedData/WKWebViewLocalAssetsObjC-fvxxuqufqsqmowcfufxditimurkx/Build/Intermediates.noindex/ArchiveIntermediates/WKWebViewLocalAssetsObjC/BuildProductsPath/Release-iphoneos/GoogleDataTransport -F/Users/builder/Library/Developer/Xcode/DerivedData/WKWebViewLocalAssetsObjC-fvxxuqufqsqmowcfufxditimurkx/Build/Intermediates.noindex/ArchiveIntermediates/WKWebViewLocalAssetsObjC/BuildProductsPath/Release-iphoneos/GoogleUtilities -F/Users/builder/Library/Developer/Xcode/DerivedData/WKWebViewLocalAssetsObjC-fvxxuqufqsqmowcfufxditimurkx/Build/Intermediates.noindex/ArchiveIntermediates/WKWebViewLocalAssetsObjC/BuildProductsPath/Release-iphoneos/PromisesObjC -F/Users/builder/Library/Developer/Xcode/DerivedData/WKWebViewLocalAssetsObjC-fvxxuqufqsqmowcfufxditimurkx/Build/Intermediates.noindex/ArchiveIntermediates/WKWebViewLocalAssetsObjC/BuildProductsPath/Release-iphoneos/nanopb -MMD -MT dependencies -MF /Users/builder/Library/Developer/Xcode/DerivedData/WKWebViewLocalAssetsObjC-fvxxuqufqsqmowcfufxditimurkx/Build/Intermediates.noindex/ArchiveIntermediates/WKWebViewLocalAssetsObjC/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/GoogleDataTransport.build/Objects-normal/arm64/client_metrics.nanopb.d --serialize-diagnostics /Users/builder/Library/Developer/Xcode/DerivedData/WKWebViewLocalAssetsObjC-fvxxuqufqsqmowcfufxditimurkx/Build/Intermediates.noindex/ArchiveIntermediates/WKWebViewLocalAssetsObjC/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/GoogleDataTransport.build/Objects-normal/arm64/client_metrics.nanopb.dia -c /Users/builder/clone/Pods/GoogleDataTransport/GoogleDataTransport/GDTCCTLibrary/Protogen/nanopb/client_metrics.nanopb.c -o /Users/builder/Library/Developer/Xcode/DerivedData/WKWebViewLocalAssetsObjC-fvxxuqufqsqmowcfufxditimurkx/Build/Intermediates.noindex/ArchiveIntermediates/WKWebViewLocalAssetsObjC/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/GoogleDataTransport.build/Objects-normal/arm64/client_metrics.nanopb.o
	CompileC /Users/builder/Library/Developer/Xcode/DerivedData/WKWebViewLocalAssetsObjC-fvxxuqufqsqmowcfufxditimurkx/Build/Intermediates.noindex/ArchiveIntermediates/WKWebViewLocalAssetsObjC/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/GoogleDataTransport.build/Objects-normal/arm64/cct.nanopb.o /Users/builder/clone/Pods/GoogleDataTransport/GoogleDataTransport/GDTCCTLibrary/Protogen/nanopb/cct.nanopb.c normal arm64 c com.apple.compilers.llvm.clang.1_0.compiler (in target 'GoogleDataTransport' from project 'Pods')
	cd /Users/builder/clone/Pods
	/Applications/Xcode-14.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c -target arm64-apple-ios11.0 -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -std\=c99 -fmodules -gmodules -fmodules-cache-path\=/Users/builder/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -fmodules-prune-interval\=86400 -fmodules-prune-after\=345600 -fbuild-session-file\=/Users/builder/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror\=non-modular-include-in-framework-module -fmodule-name\=GoogleDataTransport -Wno-trigraphs -fpascal-strings -Os -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror\=return-type -Wdocumentation -Wunreachable-code -Werror\=deprecated-objc-isa-usage -Werror\=objc-root-class -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-implicit-fallthrough -DPOD_CONFIGURATION_RELEASE\=1 -DCOCOAPODS\=1 -DPB_FIELD_32BIT\=1 -DPB_NO_PACKED_STRUCTS\=1 -DPB_ENABLE_MALLOC\=1GDTCOR_VERSION\=9.2.1 -isysroot /Applications/Xcode-14.2.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk -fstrict-aliasing -Wdeprecated-declarations -g -Wno-sign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wno-semicolon-before-method-body -Wunguarded-availability -iquote /Users/builder/Library/Developer/Xcode/DerivedData/WKWebViewLocalAssetsObjC-fvxxuqufqsqmowcfufxditimurkx/Build/Intermediates.noindex/ArchiveIntermediates/WKWebViewLocalAssetsObjC/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/GoogleDataTransport.build/GoogleDataTransport-generated-files.hmap -I/Users/builder/Library/Developer/Xcode/DerivedData/WKWebViewLocalAssetsObjC-fvxxuqufqsqmowcfufxditimurkx/Build/Intermediates.noindex/ArchiveIntermediates/WKWebViewLocalAssetsObjC/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/GoogleDataTransport.build/GoogleDataTransport-own-target-headers.hmap -I/Users/builder/Library/Developer/Xcode/DerivedData/WKWebViewLocalAssetsObjC-fvxxuqufqsqmowcfufxditimurkx/Build/Intermediates.noindex/ArchiveIntermediates/WKWebViewLocalAssetsObjC/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/GoogleDataTransport.build/GoogleDataTransport-all-non-framework-target-headers.hmap -ivfsoverlay /Users/builder/Library/Developer/Xcode/DerivedData/WKWebViewLocalAssetsObjC-fvxxuqufqsqmowcfufxditimurkx/Build/Intermediates.noindex/ArchiveIntermediates/WKWebViewLocalAssetsObjC/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/GoogleDataTransport.build/all-product-headers.yaml -iquote /Users/builder/Library/Developer/Xcode/DerivedData/WKWebViewLocalAssetsObjC-fvxxuqufqsqmowcfufxditimurkx/Build/Intermediates.noindex/ArchiveIntermediates/WKWebViewLocalAssetsObjC/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/GoogleDataTransport.build/GoogleDataTransport-project-headers.hmap -I/Users/builder/Library/Developer/Xcode/DerivedData/WKWebViewLocalAssetsObjC-fvxxuqufqsqmowcfufxditimurkx/Build/Intermediates.noindex/ArchiveIntermediates/WKWebViewLocalAssetsObjC/BuildProductsPath/Release-iphoneos/GoogleDataTransport/include -I/Users/builder/clone/Pods/GoogleDataTransport -I/Users/builder/Library/Developer/Xcode/DerivedData/WKWebViewLocalAssetsObjC-fvxxuqufqsqmowcfufxditimurkx/Build/Intermediates.noindex/ArchiveIntermediates/WKWebViewLocalAssetsObjC/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/GoogleDataTransport.build/DerivedSources-normal/arm64 -I/Users/builder/Library/Developer/Xcode/DerivedData/WKWebViewLocalAssetsObjC-fvxxuqufqsqmowcfufxditimurkx/Build/Intermediates.noindex/ArchiveIntermediates/WKWebViewLocalAssetsObjC/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/GoogleDataTransport.build/DerivedSources/arm64 -I/Users/builder/Library/Developer/Xcode/DerivedData/WKWebViewLocalAssetsObjC-fvxxuqufqsqmowcfufxditimurkx/Build/Intermediates.noindex/ArchiveIntermediates/WKWebViewLocalAssetsObjC/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/GoogleDataTransport.build/DerivedSources -F/Users/builder/Library/Developer/Xcode/DerivedData/WKWebViewLocalAssetsObjC-fvxxuqufqsqmowcfufxditimurkx/Build/Intermediates.noindex/ArchiveIntermediates/WKWebViewLocalAssetsObjC/BuildProductsPath/Release-iphoneos/GoogleDataTransport -F/Users/builder/Library/Developer/Xcode/DerivedData/WKWebViewLocalAssetsObjC-fvxxuqufqsqmowcfufxditimurkx/Build/Intermediates.noindex/ArchiveIntermediates/WKWebViewLocalAssetsObjC/BuildProductsPath/Release-iphoneos/GoogleUtilities -F/Users/builder/Library/Developer/Xcode/DerivedData/WKWebViewLocalAssetsObjC-fvxxuqufqsqmowcfufxditimurkx/Build/Intermediates.noindex/ArchiveIntermediates/WKWebViewLocalAssetsObjC/BuildProductsPath/Release-iphoneos/PromisesObjC -F/Users/builder/Library/Developer/Xcode/DerivedData/WKWebViewLocalAssetsObjC-fvxxuqufqsqmowcfufxditimurkx/Build/Intermediates.noindex/ArchiveIntermediates/WKWebViewLocalAssetsObjC/BuildProductsPath/Release-iphoneos/nanopb -MMD -MT dependencies -MF /Users/builder/Library/Developer/Xcode/DerivedData/WKWebViewLocalAssetsObjC-fvxxuqufqsqmowcfufxditimurkx/Build/Intermediates.noindex/ArchiveIntermediates/WKWebViewLocalAssetsObjC/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/GoogleDataTransport.build/Objects-normal/arm64/cct.nanopb.d --serialize-diagnostics /Users/builder/Library/Developer/Xcode/DerivedData/WKWebViewLocalAssetsObjC-fvxxuqufqsqmowcfufxditimurkx/Build/Intermediates.noindex/ArchiveIntermediates/WKWebViewLocalAssetsObjC/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/GoogleDataTransport.build/Objects-normal/arm64/cct.nanopb.dia -c /Users/builder/clone/Pods/GoogleDataTransport/GoogleDataTransport/GDTCCTLibrary/Protogen/nanopb/cct.nanopb.c -o /Users/builder/Library/Developer/Xcode/DerivedData/WKWebViewLocalAssetsObjC-fvxxuqufqsqmowcfufxditimurkx/Build/Intermediates.noindex/ArchiveIntermediates/WKWebViewLocalAssetsObjC/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/GoogleDataTransport.build/Objects-normal/arm64/cct.nanopb.o
	note: Run script build phase 'Run Script' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'WKWebViewLocalAssetsObjC' from project 'WKWebViewLocalAssetsObjC')


Build failed :|
Step 6 script `Build ipa for distribution` exited with status code 65
```

this is my yaml file modified :

```
 workflows:
  ios-workflow:
    name: iOS Workflow
    integrations:
      app_store_connect: CodemagicSign
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: noon.team.mn
      vars:
        BUNDLE_ID: "noon.team.mn"
        XCODE_WORKSPACE: "WKWebViewLocalAssetsObjC.xcworkspace"
        XCODE_SCHEME: "WKWebViewLocalAssetsObjC"
        APP_ID: V25LVKC5NA.noon.team.mn
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install CocoaPods dependencies
        script: | 
          pod install
      - name: Set up provisioning profiles settings on Xcode project
        script: xcode-project use-profiles --project WKWebViewLocalAssetsObjC/*.xcodeproj
      - name: Increment build number
        script: | 
          cd $CM_BUILD_DIR
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_ID")
          agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))
      - name: Build ipa for distribution
        script: | 
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - jomart1985@mail.com
        notify:
          success: true
          failure: false
      app_store_connect:
        auth: integration

  
```
