### DISCUSSION TITLE
How write tag script in codemagic.yaml?

### DISCUSSION THREAD

**Discussion by ghost** [codemagic-ci-cd/codemagic-docs#1428] [Q&A]
# I try
 - Default of Enter build mode: ./gradlew bundleRelease
 - ./android/gradlew bundleRelease
 - android/gradlew bundleRelease
 - /android/gradlew bundleRelease
##
```yaml
workflows:
  my-workflow:
    environment:
      flutter: default
    scripts:
      - name: Build Android App Bundle
        working_directory: android
        script: /android/gradlew bundleRelease
    artifacts:
      - build/**/outputs/bundle/**/*.aab
```
# My codes
 - https://github.com/alexandrogs/ratos/blob/master/codemagic.yaml
 - flutter: environment: sdk: '>=2.19.2 <3.0.0'
   - https://github.com/alexandrogs/ratos/blob/master/pubspec.yaml
 - https://github.com/alexandrogs/ratos
 - Code old success in other simple project: https://gitlab.com/AlexandroGonSan/firstplay/-/blob/master/codemagic.yaml
