### DISCUSSION TITLE
Define single file as artifact in code magic.yaml

### DISCUSSION THREAD

**Discussion by phhoef** [codemagic-ci-cd/codemagic-docs#1491] [Q&A]
I've a small Flutter desktop application and I am building this App on Codemagic for Windows.
During the build process a setup is generated through Inno Setup.

Inno setup outputs the installer to `dist/MyApp Setup.exe`.
I've defined the following artifact:
```yaml
    artifacts:
      - "dist/MyApp Setup.exe"
```

I am expecting, that only this exe file is published as artifact.
In fact, the whole dist folder containing the exe file is zipped and offered for download.
The name of the artifact is `MyApp_2_11_artifacts.zip`. When unpacked the structure is
```
- dist
   - MyApp Setup.exe
```

Can someone please give me a hint, how to only output the single exe file?

**Comment by icarusdust** [comment]
Hi @phhoef, Flutter Windows package is `.msix` which is generated under `build/windows/**/*.msix`.  However, I believe` .exe` file will need to be generated inside the zip folder, well to be honest I am not quite familiar with it but producing it inside a zip folder is what I am expecting as` .exe` itself is not a publishable artefact. As you can see in this Windows sample project, `.exe` is expected to be inside a zip folder in `build/windows/runner/*.zip`: https://github.com/codemagic-ci-cd/codemagic-sample-projects/blob/main/flutter/flutter-windows-demo-project/codemagic.yaml

On the other hand, perhaps, you can try to unzip. I strongly suggest you to do it by [remote accessing a builder machine,](https://docs.codemagic.io/troubleshooting/accessing-builder-machine-via-ssh/) so that you can check all the paths.

**Reply by phhoef** [reply]
Thanks @icarusdust for your reply.
The exe file is built without issues and it is put inside the `dist` folder. I've double checked that by connecting to the builder machine.
I do not see any problems with the paths. It seems, that the artifact step itself is building the zip file ...

This is the complete workflow
```yaml
workflows:
  default-workflow:
    name: Build Windows
    instance_type: windows_x2
    max_build_duration: 30
    environment:
      flutter: default
      xcode: latest
      cocoapods: default
    scripts:
      - flutter packages pub get
      - choco install innosetup
      - flutter build windows --release
      - iscc.exe windows/installer/MyApp.iss
    artifacts:
      - "dist/MyApp Setup.exe"
```

I think in your example they need a zip file, as the compiled application is not a self bundles file format like the app bundle on Mac. So beside the executable there is at least one dll file necessary to run the application.

In my case, all the necessary files are packed inside the inno installer and compiled to a single executable.
