### DISCUSSION TITLE
Upload of APK for GitHub release fails

### DISCUSSION THREAD

**Discussion by joelpaulkoch** [codemagic-ci-cd/codemagic-docs#1510] [Q&A]
I want to create a release and upload a apk to GitHub as a publishing step.
So, I build a universal apk in a previous step and list it as artifact, the apk shows up as artifact after the pipeline run.

To publish it, I followed the instructions given here: https://docs.codemagic.io/flutter-publishing/github-releases/ 
In particular this script: 
```
 #!/usr/bin/env zsh

 # Publish only for tag builds
 if [ -z ${CM_TAG} ]; then
   echo "Not a tag build will not publish GitHub release"
   exit 0
 fi

 gh release create "${CM_TAG}" \
     --title "My App ${CM_TAG}" \
     **/app-${CM_TAG}".apk
```

Strangely, this worked once but not for the following pipeline runs. 
Now it's giving me this error:
`
stat  : no such file or directory
/var/folders/w2/rrf5p87d1bbfyphxc7jdnyvh0000gn/T/build_script_9_1_hrrdhwmv:12: permission denied: build/app/outputs/bundle/release/app-v1.1.0.apk
`

The build step for the apk is on of the scripts of the workflow and the publishing step is configured as a script in the publishing section, so the build step should run before the publishing step right?

```
workflows:
  default-workflow:
...
    triggering:
      events:
        - tag
    scripts:
      - name: Build universal apk
        script: |
...
    artifacts:   
      - build/**/outputs/**/*.apk
    publishing:
      scripts:
        - name: Publish to GitHub
          script: |
...
```
