### DISCUSSION TITLE
Triggering Bug: Draft PR is not getting update after publishing the PR.

### DISCUSSION THREAD

**Discussion by nabil-hfz** [codemagic-ci-cd/codemagic-docs#1511] [Q&A]
Hi there, 
So when ever I create a new draft PR then doing bunch of commits then publish my PR, the codemagic does not trigger a build.
It seems that the when condition has a bug for this specific stiuation, however this case does not happen when the initial state of the PR is not a draft and the codemagic triggers perfectly when ever there is a new update (new commit). You can find my codemagic.yaml file content. **Please feel free to ask me for any more elaboration.**

```
workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    environment:
      flutter: stable
    triggering:
      events:
        - pull_request
        - push
        - tag
    when:
      condition: not event.pull_request.draft
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter analyze
        script: |
          flutter analyze
        ignore_failure: false
      - name: Flutter Unit tests
        script: |
          mkdir -p test-results
          flutter test --machine > test-results/flutter.json
        test_report: test-results/flutter.json
        ignore_failure: false
      - name: Flutter Integration tests
        script: |
          mkdir -p test-results 
          flutter -d emulator-5554 test --machine > test-results/flutter_integration_test.json integration_test
        test_report: test-results/flutter_integration_test.json
        ignore_failure: false
      - name: Build APK with Flutter
        script: |
          flutter build apk --release
    artifacts:
      - build/**/outputs/apk/**/*.apk
      - partner_app/build/**/outputs/apk/**/*.apk
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - build/ios/ipa/*.ipa
      - build/macos/**/*.pkg
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log

```
