### DISCUSSION TITLE
caching won't work ?

### DISCUSSION THREAD

**Discussion by softlion** [codemagic-ci-cd/codemagic-docs#1525] [Q&A] [answered]
Hello,
I set up caching correctly in yaml.
I verified by ssh that the folders do exist.
But nothing is cached, nothing is displayed in the cache UI.

```yaml
    environment:
      ...
    cache:
      cache_paths:
        - $CM_BUILD_DIR/dotnet
        - $CM_BUILD_DIR/mobile/Watchium/obj/
        - .nuget/packages
```

Sample build ID: 64233195121c7f6458ad7a6c

Is it a feature available to paid customers only ? There is nothing in the doc about that.
