### DISCUSSION TITLE
Triggering via tag not possible with GitLab and yaml workflow

### DISCUSSION THREAD

**Discussion by gerken-tss** [codemagic-ci-cd/codemagic-docs#1577] [Q&A] [answered]
I can not get `tag_triggering` working with GitLab. It's strange - the .yaml file looks like this:

```
definitions:
  …
workflows:
  test_workflow:
    name: Test Workflow
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: '*'
          include: true
    scripts:
      - name: Test output
        script: |
          echo "Hello world!️"
  …
```

I had wanted to make the switch from UI to yaml workflow. For this, I have cloned the app and made the transition. Before I delete the old app I wanted to make sure that triggering still works with the yaml app. Funny thing: when I create a tag, the old app (the one still working with the UI) is instantly triggering, but the new one isn't.

I am really confused as this codemagic.yaml snippet is really basic. The only thing that is somehow "special" about my setup is that there are two apps that refer to the same repository (as I cloned it). Could that be the reason? Does cloning an app lead to only one app receiving the triggers from GitLab? But I don't want to delete the old app before I can make the new one work properly.

Can anyone explain this? Is something wrong with my config? I have tried all kinds of tag names. Nothing works.
