### DISCUSSION TITLE
Flutter run on iOS simulator never finishes

### DISCUSSION THREAD

**Discussion by chip2n** [codemagic-ci-cd/codemagic-docs#1586] [Q&A] [answered]
I'm trying to run my Flutter integration tests on an iOS simulator. The xcode build finishes, but the test never starts because (I assume) it's waiting for the simulator to finish launching. After 12 minutes, it times out.

I've tried connecting via SSH, launching the emulator manually and then trying to execute `flutter run`, which also never finishes.

Here's the config:

```
workflows:
  test-integration-ios:
    name: iOS integration tests
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
    cache:
      cache_paths:
        - $HOME/Library/Caches/CocoaPods
        - $FLUTTER_ROOT/.pub-cache
    scripts:
      - name: Get Flutter packages
        script: | 
          flutter packages pub get
      - name: Run codegen
        script: |
          flutter pub run build_runner build -d
      - name: iOS integration tests
        script: |
          flutter emulators --launch apple_ios_simulator
          flutter -d iPhone test integration_test/main_test.dart
```

The log for the test stage is basically (I have removed most loading messages):

```
00:00 +0: loading /Users/builder/clone/integration_test/main_test.dart                                                                                                                                 
...
                  Running Xcode build...                                          
...
01:26 +0: loading /Users/builder/clone/integration_test/main_test.dart                                                                                                                                 
Xcode build done.                                           70.0s
01:27 +0: loading /Users/builder/clone/integration_test/main_test.dart                                                                                                                                 
...
12:00 +0 -1: loading /Users/builder/clone/integration_test/main_test.dart [E]                                                                                                                          
  TimeoutException after 0:12:00.000000: Test timed out after 12 minutes.
  package:test_api/src/backend/invoker.dart 334:28  Invoker._handleError.<fn>
  dart:async/zone.dart 1390:47                      _rootRun
  dart:async/zone.dart 1300:19                      _CustomZone.run
  package:test_api/src/backend/invoker.dart 332:10  Invoker._handleError
  package:test_api/src/backend/invoker.dart 288:9   Invoker.heartbeat.<fn>.<fn>
  dart:async/zone.dart 1398:13                      _rootRun
  dart:async/zone.dart 1300:19                      _CustomZone.run
  package:test_api/src/backend/invoker.dart 287:38  Invoker.heartbeat.<fn>
  dart:async-patch/timer_patch.dart 18:15           Timer._createTimer.<fn>
  dart:isolate-patch/timer_impl.dart 398:19         _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 429:5          _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 192:26      _RawReceivePort._handleMessage
  

To run this test again: /Users/builder/programs/flutter/bin/cache/dart-sdk/bin/dart test /Users/builder/clone/integration_test/main_test.dart -p vm --plain-name 'loading /Users/builder/clone/integration_test/main_test.dart'

12:00 +0 -1: Some tests failed.                                                                                                                                                                        


Build failed :|
Step 6 script `iOS integration tests` exited with status code 1
```
