### DISCUSSION TITLE
No upload to AppStore - no errors, the build looks successful

### DISCUSSION THREAD

**Discussion by proshin-roman** [codemagic-ci-cd/codemagic-docs#1658] [Q&A] [answered]
# Summary
I have a build configuration (codemagic.yaml) for uploading my application to the AppStore. Even though the logs for builds look successful - there are no errors - I don't get any upload to the AppStore. So, it's still only the version I've uploaded manually.

The build script is built taking two CodeMagic articles as examples:
- https://docs.codemagic.io/yaml-quick-start/building-a-flutter-app/
- https://docs.codemagic.io/yaml-publishing/app-store-connect/

I'm pretty sure I'm missing something, but I'm really confused by seeing literally no errors in the build logs.

How should I modify the build script to get the artifact uploaded to the AppStore?

Any help/questions/advices are really welcomed!

# Details
Here is the full codemagic.yaml (erased sensitive info):
```
workflows:
  build-ios-on-master:
    name: Build iOS on commit to master
    max_build_duration: 60
    integrations:
      app_store_connect: "<app-store-connect-ID>"
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: app_store
        bundle_identifier: org.domain.package
      vars:
        APP_ID: xxx
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'master'
          include: true
          source: true
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build the API client
        script: |
          flutter pub run build_runner build --delete-conflicting-outputs
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter build ipa
        script: |
          BUILD_NUMBER=$(($(app-store-connect get-latest-app-store-build-number "$APP_ID") + 1))
          flutter build ipa --release \
            --build-name=1.0.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
integrations:
  app_store_connect: "<app-store-connect-ID>"
publishing:
  app_store_connect:
    auth: integration
    submit_to_testflight: true
    expire_build_submitted_for_review: true
    beta_groups:
      - "Family & friends"
    submit_to_app_store: false
    cancel_previous_submissions: true
    release_type: MANUAL
    copyright: 2023 xxx
```

For the last build, I've got the following logs:
**Step "Flutter build ipa":**
```
Did not find latest build for app xxx

Archiving org.domain.package...
Adding input path to Thin Binary build phase.
Automatically signing iOS for device deployment using specified development team in Xcode project: XXXX
Running pod install...                                             850ms
Running Xcode build...                                          
Xcode archive done.                                         61.3s
Built /Users/builder/clone/build/ios/archive/Runner.xcarchive.

[✓] App Settings Validation
    • Version Number: 1.0.2
    • Build Number: 2
    • Display Name: App Name
    • Deployment Target: 11.0
    • Bundle Identifier: org.domain.package

[!] App Icon and Launch Image Assets Validation
    ! App icon is set to the default placeholder icon. Replace with unique icons.
    ! Launch image is set to the default placeholder icon. Replace with unique launch image.

To update the settings, please refer to https://docs.flutter.dev/deployment/ios

Building App Store IPA...                                           9.8s
Built IPA to /Users/builder/clone/build/ios/ipa.
To upload to the App Store either:
    1. Drag and drop the "build/ios/ipa/*.ipa" bundle into the Apple Transporter macOS app https://apps.apple.com/us/app/transporter/id1234567
    2. Run "xcrun altool --upload-app --type ios -f build/ios/ipa/*.ipa --apiKey your_api_key --apiIssuer your_issuer_id".
       See "man altool" for details about how to authenticate with the App Store Connect API key.
```

**Step "Publishing":**
```
== Gathering artifacts ==

== Publishing artifacts ==

Publishing artifact app_name.ipa
```

**For the last step "Cleaning up":**
```
Dependency caching is disabled. Skipping.
```
