### DISCUSSION TITLE
Test report not being read

### DISCUSSION THREAD

**Discussion by ErshadGS** [codemagic-ci-cd/codemagic-docs#1666] [Q&A] [answered]
Hello, 

I have setup codemagic pipeline for Unity and have managed to run unit tests, which gives me a NUnit test result xml. But since codemagic does not support that, I converted it into JUnit test result xml using a XSLT i found [here](https://github.com/nunit/nunit-transforms/tree/master/nunit3-junit). 

Just to check, I have first added the junit-results.xml to my repo under a folder called CICDTools. 
I then created a new work flow to see how codemagic displays test results. 
The following is my workflow:-

```
workflows:
  TestReport:
    instance_type: mac_mini_m1
    name: test report
    max_build_duration: 120
    scripts:
     - name: Unit tests
       script: | 
         echo "Reading test report"
       test_report: clone/CICDTools/*.xml
```
       
I have verified that the xml is an JUnit xml, it has <testsuites> and all. 
but codemagic says

```
Reading test report
No valid test result files matching "clone/CICDTools/*.xml" were found. Test results are not displayed.
```

What am I doing wrong here? Please help.

**Comment by ErshadGS** [comment]
nevermind all i had to was remove the "clone".

```
workflows:
  TestReport:
    instance_type: mac_mini_m1
    name: test report
    max_build_duration: 120
    scripts:
      - name: Unit tests
        script: | 
         echo "Reading test report"
        test_report: CICDTools/junit-results.xml
    artifacts:
      - CICDTools/junit-results.xml
```
      
 But now it gives me a whole new error

<img width="842" alt="image" src="https://github.com/codemagic-ci-cd/codemagic-docs/assets/110253681/4e82d803-8ed8-456e-bfc9-eccbd2c53107">

build id - 6463cb0a99df419b263a2202
