### DISCUSSION TITLE
Github Release with codemagic.yaml

### DISCUSSION THREAD

**Discussion by einsitang** [codemagic-ci-cd/codemagic-docs#1667] [Q&A]
hello,

I try to use codemagic.yaml build a flutter app and publish to github release, but the document(https://docs.codemagic.io/yaml-publishing/github-releases/) seem not work

is that `GITHUB_TOKEN` define right?
```
environment:
    vars:
      GITHUB_TOKEN
```

and the `codemagic - Environment variables` look setting right
<img width="1361" alt="image" src="https://github.com/codemagic-ci-cd/codemagic-docs/assets/1745525/7f68a2b6-c439-4c73-82c7-10e53dcadfd6">

if put the code `environment.vars` to codemagic.yaml, codemagic will tell me error:
```
Invalid configuration: 1 validation error for YamlConfiguration workflows -> sudoku-flutter-workflow -> environment -> vars value is not a valid dict (type=type_error.dict)
```

somebody can help me correct codemagic.yaml 

```
workflows:
  sudoku-flutter-workflow:
    environment:
      java: 11
      flutter: 3.7.0
      android_signing:
        - ANDROID_KEYJKS
    scripts:
      - name: show gradle info
        script: gradle --version
      - name: build apk with flutter
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/apk/**/*.apk
    publishing:
      scripts:
        - name: publish to Github
          script: | 
            #!/usr/bin/env zsh
            
            echo "show GITHUB_TOKEN : ${GITHUB_TOKEN}"
            gh auth login ${GITHUB_TOKEN}
            gh release create "${CM_COMMIT}" \
            --title "Sudoku-Flutter#${CM_COMMIT} codemagic build" \
            --notes-file build/app/outputs/apk/**/*.apk
```

**Comment by einsitang** [comment]
I think I’am figure out this problem,look like this document(https://docs.codemagic.io/yaml-publishing/github-releases/) may not clear , because I am look at reference [**Amazon S3 publishing using codemagic.yaml**](https://docs.codemagic.io/yaml-publishing/aws/) to make sure `GITHUB_TOKEN` is gh environment variable, so I need to define codemagic environment groups to let GITHUB_TOKEN expose .

this is truely environment config:
```
workflows:
  sudoku-flutter-workflow:
    environment:
      java: 11
      flutter: 3.7.0
      android_signing:
        - ANDROID_KEYJKS
      groups:
        - githubtoken
       ....
```

you might need update this document([**github-releases**](https://docs.codemagic.io/yaml-publishing/github-releases/)) just like [**Amazon S3 publishing using codemagic.yaml**](https://docs.codemagic.io/yaml-publishing/aws/) 

and you can close this discussion
