### DISCUSSION TITLE
How to run script only if STORE publish succeded.

### DISCUSSION THREAD

**Discussion by vasilich6107** [codemagic-ci-cd/codemagic-docs#1733] [Q&A] [answered]
I have integrated appstore/googleplay api.

```
    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
```

But there is no information in the documentation how to detect in script if publishing succeeded.
