### DISCUSSION TITLE
React-Native: Android Build fail

### DISCUSSION THREAD

**Discussion by ChampiMagic** [codemagic-ci-cd/codemagic-docs#1748] [Q&A] [answered]
### If you are looking for help, please confirm the following...

- [X] I confirm I have searched the [Docs](https://docs.codemagic.io), [Codemagic Sample Projects](https://github.com/codemagic-ci-cd/codemagic-sample-projects), and GitHub [Discussions](https://github.com/orgs/codemagic-ci-cd/discussions).
- [X] I confirm the software versions on my local computer match the ones in CI environment (e.g. Xcode version, Gradle version). See [here](https://docs.codemagic.io/troubleshooting/common-android-issues/#builds-work-locally-but-fail-on-codemagic)
- [X] I confirm I am able to do a fresh clone of the repository and build the project on my local computer.

### Which mobile framework are you using?

React Native

### Steps to reproduce

1- Press Start new build bottom
2- Wait for configs to finished
3- Try to execute the following script for build android bundle release: `chmod +x ./gradlew | ./gradlew bundleRelease` I tried with only `./gradlew bundleRelease` too and I'm getting the same error message

This is my config file:
``` yaml
workflows:
  android:
    name: react-native-android
    instance_type: mac_mini_m1
    environment:
      node: 18
      java: 19
      groups:
        - google_credentials
      android_signing:
        - scrumit_keystore
    scripts:
      - name: Build Android App Bundle
        working_directory: android
        script: chmod +x ./gradlew | ./gradlew bundleRelease
    artifacts:
      - build/**/outputs/bundle/**/*.aab
    publishing:
      google_play:
        # Contents of the JSON key file for Google Play service account saved
        # as a secure environment variable
        credentials: $GCLOUD_KEY_FILE

        # Name of the track internal, alpha, beta, production, internal app sharing,
        # or your custom track name
        track: internal

        # Optional Priority of the release (only set if in-app updates are supported)
        # integer in range [0, 5]
        # in_app_update_priority: 3

        # Optional. Rollout fraction (set only if releasing to a fraction of users)
        # value between (0, 1)
        # rollout_fraction: 0.25

        # Optional boolean To be used ONLY if your app cannot be sent for review automatically *
        changes_not_sent_for_review: true

        # Optional boolean. Publish artifacts under a draft release.
        # Can not be used together with rollout_fraction. Defaults to false
        submit_as_draft: true

```

### Expected results

Android bundle build successfully

### Actual results

The console throw me the following message:
![Captura de pantalla 2023-06-08 165935](https://github.com/codemagic-ci-cd/codemagic-docs/assets/97173716/488d6abf-32c3-4122-97bb-1e07f35b885f)

### Build id (optional)

648230a2cd1f7cff38b48955
