### DISCUSSION TITLE
Unity License Activation Fails

### DISCUSSION THREAD

**Discussion by rahul-Inspirit** [codemagic-ci-cd/codemagic-docs#1788] [Q&A]
### If you are looking for help, please confirm the following...

- [X] I confirm I have searched the [Docs](https://docs.codemagic.io), [Codemagic Sample Projects](https://github.com/codemagic-ci-cd/codemagic-sample-projects), and GitHub [Discussions](https://github.com/orgs/codemagic-ci-cd/discussions).
- [X] I confirm the software versions on my local computer match the ones in CI environment (e.g. Xcode version, Gradle version). See [here](https://docs.codemagic.io/troubleshooting/common-android-issues/#builds-work-locally-but-fail-on-codemagic)
- [X] I confirm I am able to do a fresh clone of the repository and build the project on my local computer.

### Which mobile framework are you using?

Unity

### Steps to reproduce

Run unity_android_workflow

### Expected results

Successful build

### Actual results

/var/folders/w2/rrf5p87d1bbfyphxc7jdnyvh0000gn/T/build_script_2_1_0eit30kn: line 3: /Contents/MacOS/Unity: No such file or directory

Build failed :|
Step 2 script `Activate Unity License` exited with status code 127

### Build id (optional)

648f0100f1fd989ece3517c2

**Comment by dtrdic** [comment]
Hello @rahul-Inspirit, can you try to lower the Xcode version in your yaml file. If it's not specified it uses the 14.3.1 which is a default version. Try using 14.2 or 14.1 version instead

```
workflows:
 android-workflow:
    name: Android Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      android_signing:
        - cdemagicKeystore
      xcode: 14.2
      groups:
```
