### DISCUSSION TITLE
Issue building React native ios app

### DISCUSSION THREAD

**Discussion by iib0011** [codemagic-ci-cd/codemagic-docs#1789] [Q&A] [answered]
### If you are looking for help, please confirm the following...

- [X] I confirm I have searched the [Docs](https://docs.codemagic.io), [Codemagic Sample Projects](https://github.com/codemagic-ci-cd/codemagic-sample-projects), and GitHub [Discussions](https://github.com/orgs/codemagic-ci-cd/discussions).
- [X] I confirm the software versions on my local computer match the ones in CI environment (e.g. Xcode version, Gradle version). See [here](https://docs.codemagic.io/troubleshooting/common-android-issues/#builds-work-locally-but-fail-on-codemagic)
- [X] I confirm I am able to do a fresh clone of the repository and build the project on my local computer.

### Which mobile framework are you using?

React Native

### Steps to reproduce

Try to build a React native ios app with codeMagic
```yaml
    scripts:
      - name: Install dependencies
        script: |
            yarn install
      - name: Install CocoaPods dependencies
        script: |
            cd ios && pod install
      - name: Set up provisioning profiles settings on Xcode project
        script: |
          sudo gem install xcodeproj
          sudo xcode-project use-profiles
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/ios/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
   
```

### Expected results

The build should happen without problem

### Actual results

But I have this: Failed to set code signing settings for node_modules/react-native-fast-image/ios/FastImage.xcodeproj. It happens at this step: 
```bash
sudo xcode-project use-profiles
```

### Build id (optional)

648f2f98fd6c8e1321b5a2a6
