### DISCUSSION TITLE
working_directory param doesn't work

### DISCUSSION THREAD

**Discussion by christopher-FH** [codemagic-ci-cd/codemagic-docs#1866] [Q&A]
### If you are looking for help, please confirm the following...

- [x] I confirm I have searched the [Docs](https://docs.codemagic.io), [Codemagic Sample Projects](https://github.com/codemagic-ci-cd/codemagic-sample-projects), and GitHub [Discussions](https://github.com/orgs/codemagic-ci-cd/discussions).
- [X] I confirm the software versions on my local computer match the ones in CI environment (e.g. Xcode version, Gradle version). See [here](https://docs.codemagic.io/troubleshooting/common-android-issues/#builds-work-locally-but-fail-on-codemagic)
- [X] I confirm I am able to do a fresh clone of the repository and build the project on my local computer.

### Which mobile framework are you using?

Flutter (Dart)

### Steps to reproduce

1. Use example from documentation
```
workflows:
  build-apps:
    name: Build iOS and Android
    working_directory: mobile
    scripts:
      - name: Prepare
        script: pwd # current working directory is /Users/builder/clone/mobile
      - name: Build iOS
        working_directory: mobile/ios
        script: pwd # current working directory is /Users/builder/clone/mobile/ios
      - name: Build Android
        working_directory: mobile/android
        script: pwd # current working directory is /Users/builder/clone/mobile/android
      - name: Process Logs
        working_directory: /Users/builder/Library/Logs
        script: pwd # current working directory is /Users/builder/Library/Logs
```
2. Run build

### Expected results

success

### Actual results

failure

Build failed :|

### Build id (optional)

64ad5bbbd5567cbd2cc50e96

**Comment by kulakarla** [comment]
Hello Christopher, are you sure you have a directory called "mobile" inside your repository? I tested it with a sample, created a folder called "mobile" inside my repo with subfolders "ios" and "android" and the build succeeded. Used the exact same YAML.

In your error logs I find: FileNotFoundError: [Errno 2] No such file or directory: PosixPath('/Users/builder/clone/mobile')

**Reply by christopher-FH** [reply]
@kulakarla 
How did you check this error? I didn't see that.

Now I see the problem, I though that working_directory is the directory where we clone repo as well.

We use external tool from github. I wanted to clone main repo to separate directory, like that:
.../clone/app_directory/app files
.../clone/tool/tool files

Do you have any idea what is the best way to do that?

**Reply by kulakarla** [reply]
@christopher-FH 
I can see general logs.

So, currently it is not possible to have the initial repo cloned to a different folder.

The simplest suggestion from me is a simple bash script of copying the folder. Here's a simple example I made to copy the repo to another folder inside clone. Just some checking scripts aswell.

```
workflows:
  build-apps:
    name: Build iOS and Android
    scripts:
      - name: Copy folder
        working_directory: /Users/builder
        script: |
          cp -R clone app_files
          rm -rf clone/*
          mv app_files clone
      - name: Check folder is empty
        working_directory: /Users/builder/clone
        script: |
          ls
      - name: Check existence
        working_directory: /Users/builder/clone/app_files
        script: |
          ls
```
