### DISCUSSION TITLE
Read current git branch

### DISCUSSION THREAD

**Discussion by munnadroid** [codemagic-ci-cd/codemagic-docs#1874] [Q&A]
### If you are looking for help, please confirm the following...

- [x] I confirm I have searched the [Docs](https://docs.codemagic.io), [Codemagic Sample Projects](https://github.com/codemagic-ci-cd/codemagic-sample-projects), and GitHub [Discussions](https://github.com/orgs/codemagic-ci-cd/discussions).
- [X] I confirm the software versions on my local computer match the ones in CI environment (e.g. Xcode version, Gradle version). See [here](https://docs.codemagic.io/troubleshooting/common-android-issues/#builds-work-locally-but-fail-on-codemagic)
- [X] I confirm I am able to do a fresh clone of the repository and build the project on my local computer.

### Which mobile framework are you using?

Flutter (Dart)

### Steps to reproduce

I have below codemagic.yaml 
 ```
triggering:      
      events:      
        - push.   
      branch_patterns:
        - pattern: "*-release"
          include: true
          source: true
      cancel_previous_builds: false  # Set to `true` to automatically cancel outdated webhook builds
.
.
.
- name: Build APK with Flutter
        script: |
          flutter build apk --flavor sit -t lib/main_sit.dart --release --build-name=1.0.0 --build-number=10
```

I am not able to configure the flavor `sit` dynamically by reading from current branch.
I have branches as sit-release, uat-release, preprod-release, prod-release

### Expected results

I have branches as sit-release, uat-release, preprod-release, prod-release
I want to read the current triggered branch name and use the branch name while creating the build.
For example, if current triggered branch is `uat-release`, the build generation command would be. 
```
- name: Build APK with Flutter
        script: |
        flutter build apk --flavor uat -t lib/main_uat.dart --release --build-name=1.0.0 --build-number=10
```

### Actual results

Not able to find the documentation to read the current branch.
