### DISCUSSION TITLE
Using same repository to multiple apps

### DISCUSSION THREAD

**Discussion by MaroniDaniel** [codemagic-ci-cd/codemagic-docs#1908] [Q&A] [answered]
### If you are looking for help, please confirm the following...

- [X] I confirm I have searched the [Docs](https://docs.codemagic.io), [Codemagic Sample Projects](https://github.com/codemagic-ci-cd/codemagic-sample-projects), and GitHub [Discussions](https://github.com/orgs/codemagic-ci-cd/discussions).
- [X] I confirm the software versions on my local computer match the ones in CI environment (e.g. Xcode version, Gradle version). See [here](https://docs.codemagic.io/troubleshooting/common-android-issues/#builds-work-locally-but-fail-on-codemagic)
- [X] I confirm I am able to do a fresh clone of the repository and build the project on my local computer.

### Which mobile framework are you using?

Flutter (Dart)

### Steps to reproduce

I got 5 different apps with basically the same code, just using different images/files/colors. (like a template app)
To solve this problematic approach, i created a single new repository and did some automation to create different branches of the same app, to reuse the code.

This is what i'm trying to do:

1. Every branch that i create is a different app, inside the same repository;
2. For each different branch (app), a request is sent to the codemagic with the app id and the branch name to start the build;
3. To do that, i was expecting to change the repository of every application inside the codemagic to the same repository, and just use different branches.
4. I cant use the .yaml configuration file to try different things because i'm using the codemagic API to send new builds, and i don't think you can use .yalm when using the API.

It's possible to make this work?

### Expected results

Be able to use the same repository for different applications.

### Actual results

Theres no option to change an aplication repository.

**Comment by dtrdic** [comment]
if i understand you correctly you can try something like this.. This will trigger a workflow named android-workflow on different branches (main, master, dev)

```
workflows:
    trigger:
      name: trigger builds for different branches
      environment:
        groups:
          - firebase_credentials
          - google_play_credentials
          - token
      scripts:
        - name: Trigger multiple branches
          script: |
            BRANCHES=("main" "master" "dev")

            for BRANCH in ${BRANCHES[@]}; do
              echo "Triggering workflow $WORKFLOW for branch $BRANCH"

              # Make the POST request to trigger the build for the current branch
              curl -H "Content-Type: application/json" -H "x-auth-token: $CM_API_KEY" \
                --data '{
                  "appId": "645a0fafc5f77d006a400bf1",
                  "workflowId": "android-workflow",
                  "branch": "'${BRANCH}'"
                }' \
                https://api.codemagic.io/builds
            done

    android-workflow:
        name: Android Workflow
        max_build_duration: 120
        instance_type: mac_mini_m1
        labels:
          - ${PACKAGE_NAME}
        environment:
        
        . . .
```
