### DISCUSSION TITLE
Use env variable for submit_to_appstore option

### DISCUSSION THREAD

**Discussion by daniel-naegele** [codemagic-ci-cd/codemagic-docs#1916] [Q&A] [answered]
### If you are looking for help, please confirm the following...

- [X] I confirm I have searched the [Docs](https://docs.codemagic.io), [Codemagic Sample Projects](https://github.com/codemagic-ci-cd/codemagic-sample-projects), and GitHub [Discussions](https://github.com/orgs/codemagic-ci-cd/discussions).
- [X] I confirm the software versions on my local computer match the ones in CI environment (e.g. Xcode version, Gradle version). See [here](https://docs.codemagic.io/troubleshooting/common-android-issues/#builds-work-locally-but-fail-on-codemagic)
- [X] I confirm I am able to do a fresh clone of the repository and build the project on my local computer.

### Which mobile framework are you using?

Flutter (Dart)

### Steps to reproduce

We want to use env variables to determine whether to publish the app or not (different clients etc.) but use the same workflow. Currently, the publishing section looks like this:
```yaml
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        submit_to_app_store: $APP_STORE_SUBMIT_TO_STORE
```

The variable `APP_STORE_SUBMIT_TO_STORE` is set to `false`

### Expected results

Build should just complete like normal

### Actual results

The build stops already at the yaml validation with the message:
`Invalid configuration: 1 validation error for YamlConfiguration workflows -> ios-client-release -> publishing -> app_store_connect -> submit_to_app_store value could not be parsed to a boolean (type=type_error.bool)`

### Build id (optional)

64c13f3a5bbed199534c8ae9

**Comment by dtrdic** [comment]
Hey @daniel-naegele, could you please provide more information about your use case? When you would like to publish the app and when you would prefer not to publish it?

**Reply by daniel-naegele** [reply]
We are using the same setup as the mentioned white label codemagic.yaml sample. Sometimes we have a client, which is completely implemented, but we don't want to publish their app yet. So we would set the env variable (which for us would default to true) to false in order to prevent a accidental release in the app store.

You can already achieve the same behavior for the play store, as the publishing track can already be specified as an env variable

**Reply by dtrdic** [reply, marked as answer]
Hey @daniel-naegele, unfortunately, you can't use environment variables for that field. But you can create a different job inside the same workflow and have different values for the `submit_to_app_store` field, like this;

<img width="517" alt="image" src="https://github.com/codemagic-ci-cd/codemagic-docs/assets/38918425/8e77bfb2-c6dd-4c48-aee8-80c2e109521a">

if you are a white-label user, just trigger the workflows you want to build through rest API

![image](https://github.com/codemagic-ci-cd/codemagic-docs/assets/38918425/8abeba55-3460-4bf1-afac-dea6c5e184e5)

**Reply by daniel-naegele** [reply]
Yes we could just duplicate our current iOS workflow and use it instead for some clients as a workaround, but from my perspective an env variable is a way more flexible solution. 
You don't have any code (workflow) duplication and could use it really easy.

Maybe this should have been a feature request, rather than a Q&A post.

**Reply by dtrdic** [reply]
I agree, using environment variables would be more flexible, but the current limitation may have been designed as a safety feature to prevent accidental releases like you also want to avoid.
But regardless, I forwarded your suggestion and will let you know if we make any changes or updates regarding this feature request

**Reply by toebgen** [reply]
Hi @dtrdic ,
I am currently running into the same issue.
In the meantime, has there been any update in this regard, by any chance?
Thanks in advance!

**Comment by wer-mathurin** [comment]
@daniel-naegele , @dtrdic 

I'm not 100% sure, but I think ou can achieve this by using the inputs !

```
    inputs:
      publishAsDraft:
        description: Submit as draft
        type: boolean
        default: $GOOGLE_SUBMIT_DRAFT

...
...

   publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: $GOOGLE_PLAY_TRACK
        submit_as_draft: ${{ inputs.publishAsDraft }}

```


So if you are running it in the UI, the question will be asked
According to the documentation
https://docs.codemagic.io/knowledge-codemagic/build-inputs/#starting-builds-with-inputs-automatically
If you are running it with the API the default value will be used....
