### DISCUSSION TITLE
How to add something to the PATH on Windows?

### DISCUSSION THREAD

**Discussion by nilsreichardt** [codemagic-ci-cd/codemagic-docs#1921] [Q&A]
### If you are looking for help, please confirm the following...

- [X] I confirm I have searched the [Docs](https://docs.codemagic.io), [Codemagic Sample Projects](https://github.com/codemagic-ci-cd/codemagic-sample-projects), and GitHub [Discussions](https://github.com/orgs/codemagic-ci-cd/discussions).
- [X] I confirm the software versions on my local computer match the ones in CI environment (e.g. Xcode version, Gradle version). See [here](https://docs.codemagic.io/troubleshooting/common-android-issues/#builds-work-locally-but-fail-on-codemagic)
- [X] I confirm I am able to do a fresh clone of the repository and build the project on my local computer.

### Which mobile framework are you using?

Flutter (Dart)

### Steps to reproduce

Hey 👋 I'm writing the docs for using Shorebird and Codemagic on Windows machines: https://docs.shorebird.dev/ci/codemagic.

Unfortunately, I'm unable to add Shorebird to the PATH. How can I achieve this? On macOS/Linux I can just run `echo PATH="$HOME/.shorebird/bin:$PATH" >> $CM_ENV`.

My current workflow (the issue is in the `Add-Content -Path $env:CM_ENV -Value`): 

```
workflows:
  example:
    name: Example
    environment:
      groups:
        - shorebird
      flutter: stable
    instance_type: windows_x2
    scripts:
      - name: 🐦 Setup Shorebird
        script: |
          Set-ExecutionPolicy RemoteSigned -scope CurrentUser # Needed to execute remote scripts
          iwr -UseBasicParsing 'https://raw.githubusercontent.com/shorebirdtech/install/main/install.ps1'|iex

          Add-Content -Path $env:CM_ENV -Value PATH=C:\Users\builder\.shorebird\bin:$PATH
      - name: 🚀 Shorebird Patch
        script: |
          echo "Patching Shorebird"
          shorebird --version
```

Docs on how to add an environment variable:

```
  scripts:
    - name: Save variable to ENV file
      script: | 
        Add-Content -Path $env:CM_ENV -Value "KEY=value"
```

https://docs.codemagic.io/yaml-basic-configuration/using-environment-variables/

### Expected results

I want to be able to run `shorebird` commands.

### Actual results

Either I'm getting directly error code 1 or 

```
shorebird : The term 'shorebird' is not recognized as the name of a cmdlet, function, script file, or operable 
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\builder\AppData\Local\Temp\build_script_4_1_o6d5lac6.ps1:1 char:1
+ shorebird release android --force
+ ~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (shorebird:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

### Build id (optional)

64c2da967b1051fc62323c64

**Comment by eseidel** [comment]
Hmm, the Shorebird installer tries to add `shorebird` to the path, but maybe it's not working in the CM environment?
https://github.com/shorebirdtech/install/blob/main/install.ps1#L48

**Reply by mohammedbabelly20** [reply]
Hey @eseidel,
Yes, actually the path is added correctly to the User path.
However it seems like `PowerShell` can't find this path, whereas `Command Prompt` or `Git Bash` are working fine, and because Codemagic's scripts are executed in `PS` so @nilsreichardt is facing this issue.

I've done some experiments on a physical Windows machine and I didn't see any issues.
Then I tried installing `Shorebird` on a **`Windows Server 2019 AWS EC2`** instance, (same version that CM uses) and I got the same issue, which is `PowerShell` is not able to find this path, even though the path is added.
However, when I installed `Shorebird` on a **`Windows Server 2022 AWS EC2`** instance, everything was going well.

![AWS EC2 - win server 2019](https://github.com/codemagic-ci-cd/codemagic-docs/assets/104768048/325d9726-feb6-4e60-a216-1c51f34ccf19)
![AWS EC2 - win server 2022](https://github.com/codemagic-ci-cd/codemagic-docs/assets/104768048/654d3550-7484-4698-bbbb-67753606a191)

**Reply by nilsreichardt** [reply]
Thanks for taking a look into that, @codemagic-mohammed <3

For me, there are two open questions:

* The initial question on how to add something to the PATH on Windows is still a bit unclear to me
* Needs this to be fixed on Shorebird side or Codemagic side? Or needs nothing to be fixed and you always need to add the tool manually to the PATH (with `Add-Content -Path $env:CM_ENV...`)

**Comment by eseidel** [comment]
I don't know 🤷 Suggestions welcome, we're happy to change our powershell script in any way necessary!
https://github.com/shorebirdtech/install/blob/main/install.ps1

**Comment by mohammedbabelly20** [comment]
Hey @nilsreichardt,

- The issue is not how to add the PATH, it's already there.
- It can be fixed from our side if we updated our machines to Win Server 2022, which is something we're not planning to do at the time. If I or someone from Shorebird find out why this issue is happening on Win Server 2019 default PowerShell then we can suggest that fix. 

**For now, how to use Shorebird on Codemagic's Windows machine?**
It's a simple trick that you can do to run the PS1 file directly by defining an environment variable with the file's full path, then using the variable name like this `& $env:shorebird --version` instead of `shorebird --version`.
```
  shorebird-windows-workflow:
    name: Shorebird widows Workflow
    instance_type: windows_x2
    environment:
      flutter: stable    
      vars:
        shorebird: "C:\\Users\\builder\\.shorebird\\bin\\shorebird.ps1"
    scripts:
      - name: Setup Shorebird
        script: |
          Set-ExecutionPolicy RemoteSigned -scope CurrentUser # Needed to execute remote scripts
          iwr 'https://raw.githubusercontent.com/shorebirdtech/install/main/install.ps1'|iex

      - name: Shorebird Patch
        script: |
          & $env:shorebird --version
```

I'm gonna leave this discussion open for now.
