### DISCUSSION TITLE
How do I set the CERTIFICATES

### DISCUSSION THREAD

**Discussion by earnestangel** [codemagic-ci-cd/codemagic-docs#1943] [Q&A]
### If you are looking for help, please confirm the following...

- [X] I confirm I have searched the [Docs](https://docs.codemagic.io), [Codemagic Sample Projects](https://github.com/codemagic-ci-cd/codemagic-sample-projects), and GitHub [Discussions](https://github.com/orgs/codemagic-ci-cd/discussions).
- [X] I confirm the software versions on my local computer match the ones in CI environment (e.g. Xcode version, Gradle version). See [here](https://docs.codemagic.io/troubleshooting/common-android-issues/#builds-work-locally-but-fail-on-codemagic)
- [X] I confirm I am able to do a fresh clone of the repository and build the project on my local computer.

### Which mobile framework are you using?

-

### Steps to reproduce

My project is using the native iOS app, and not using any framework. 

This is my workflow
```
workflows:
  my-workflow:
    scripts:
      - name: Add provisioning profiles
        script: |
          set -e # exit on first failed command

          PROFILES_HOME="$HOME/Library/MobileDevice/Provisioning Profiles"
          mkdir -p "$PROFILES_HOME"
          echo ${PROVISIONING_PROFILE?} | base64 --decode > "$PROFILES_HOME/$(uuidgen).mobileprovision"
      - name: Add signing certificate
        script: |
          set -e # exit on first failed command

          echo ${CERTIFICATE?} | base64 --decode > /tmp/certificate.p12
          keychain initialize
          keychain add-certificates \
              --certificate /tmp/certificate.p12 \
              --certificate-password ${CERTIFICATE_PASSWORD?}
      - name: Increment build number
        script: agvtool new-version -all $BUILD_NUMBER
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Build ipa for distribution
        script: xcode-project build-ipa \
                    --workspace "${XCODE_WORKSPACE?}" \
                    --scheme "${XCODE_SCHEME?}"
    artifacts:
      - build/ios/ipa/*.ipa

```

How do I set the certificate? I'm genuinely confused with the process. 

### Expected results

The build runs successfully

### Actual results

I got this error when trying to "Add signing certificate"

```
/var/folders/w2/rrf5p87d1bbfyphxc7jdnyvh0000gn/T/build_script_3_1_do328zmh: line 5: CERTIFICATE: parameter null or not set
Initialize new keychain to store code signing certificates at /Users/builder/Library/codemagic-cli-tools/keychains/04-08-23_m1w4uj3d.keychain-db
Create keychain /Users/builder/Library/codemagic-cli-tools/keychains/04-08-23_m1w4uj3d.keychain-db
Set keychain /Users/builder/Library/codemagic-cli-tools/keychains/04-08-23_m1w4uj3d.keychain-db timeout to "no timeout"
Set keychain /Users/builder/Library/codemagic-cli-tools/keychains/04-08-23_m1w4uj3d.keychain-db to system default keychain
Unlock keychain /Users/builder/Library/codemagic-cli-tools/keychains/04-08-23_m1w4uj3d.keychain-db
/var/folders/w2/rrf5p87d1bbfyphxc7jdnyvh0000gn/T/build_script_3_1_do328zmh: line 7: CERTIFICATE_PASSWORD: parameter null or not set


Build failed :|
Step 3 script `Add signing certificate` exited with status code 1
```

**Comment by kulakarla** [comment]
Hi @earnestangel 

Have you tried following [iOS native code signing docs](https://docs.codemagic.io/yaml-quick-start/building-a-native-ios-app/) for easier signing? You only have to: connect your Developer Portal with Codemagic, upload your certificate, upload the right provisioning profile and add a few lines in codemagic.yaml.

I see that you are trying to manually code sign. If you wish to continue that, try and follow these docs [here](https://docs.codemagic.io/yaml-code-signing/alternative-code-signing-methods/).

I see in your workflow you have not imported any variable groups, on which manual code signing all ultimately depends on.

The certificate is set by utilizing our environment variables: you encode your certificate and provisioning profiles to base64, then add these as our environment variables, which makes these variables available in your build scripts. Certificate is then written into a file and added into Keychain. Later, Xcode is retrieving these values from there. However, note that you have to import the environment variables first in YAML, like this (I added CM_CERTIFICATE AND CM_PROVISIONING_PROFILE as environment variables to a group called "code_signing"):
```
environment:
    groups:
       - apple_credentials
       - code_signing

```

Please refer to the [manual code signing docs](https://docs.codemagic.io/yaml-code-signing/alternative-code-signing-methods/), complete it step-by-step. If any issues appear, let me know.

**Reply by earnestangel** [reply]
Hi, I really appreciate your reply. So if I use the provisioning profile, I can remove the 2 sections (add provisioning profile and certificate) off my yaml file?

**Reply by kulakarla** [reply]
@earnestangel 

Yes, pretty much. Say that you are using code signing identities to sign, the docs being [here](https://docs.codemagic.io/yaml-quick-start/building-a-native-ios-app/).

Then you have uploaded a certificate (.p12 format) to Codemagic and the provisioning profile in .mobileprovision. Make sure the provisioning profile is using the right certificate. Also, when you create a certificate, please remember that certificate can be downloaded with its private key **once**, make sure you don't lose it or you have to create it again.

Your YAML should look something like this:

```
workflows:
  ios-native-workflow:
    name: iOS Native
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: io.codemagic.sample.iosnative
      vars:
        BUNDLE_ID: "io.codemagic.sample.iosnative"
        XCODE_WORKSPACE: "CodemagicSample.xcworkspace" # <-- Put the name of your Xcode workspace here
        XCODE_SCHEME: "CodemagicSample" # <-- Put the name of your Xcode scheme here
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install CocoaPods dependencies
        script: | 
          pod install
      - name: Set up provisioning profiles settings on Xcode project
        script: xcode-project use-profiles
      - name: Build ipa for distribution
        script: | 
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

```

Take a look at this [sample project here](https://github.com/codemagic-ci-cd/codemagic-sample-projects/blob/main/ios/ios-code-signing-identities-demo-project/codemagic.yaml) and also check out the docs I mentioned above. By following it step-by-step, I'm sure you will get everything running smoothly.
