### DISCUSSION TITLE
Locally encrypt files to be used in `environment.vars`

### DISCUSSION THREAD

**Discussion by WernerRaathAtPolymorph** [codemagic-ci-cd/codemagic-docs#1978] [Q&A]
### If you are looking for help, please confirm the following...

- [X] I confirm I have searched the [Docs](https://docs.codemagic.io), [Codemagic Sample Projects](https://github.com/codemagic-ci-cd/codemagic-sample-projects), and GitHub [Discussions](https://github.com/orgs/codemagic-ci-cd/discussions).
- [X] I confirm the software versions on my local computer match the ones in CI environment (e.g. Xcode version, Gradle version). See [here](https://docs.codemagic.io/troubleshooting/common-android-issues/#builds-work-locally-but-fail-on-codemagic)
- [X] I confirm I am able to do a fresh clone of the repository and build the project on my local computer.

### Which mobile framework are you using?

Flutter (Dart)

### Steps to reproduce

1. Within an existing flutter project, I create a `codemagic.yaml` file:
  ```
  workflows:
    default-workflow:
      name: Default Workflow
      max_build_duration: 60
      environment:
        vars:
          MY_VAR: SomeVar
          ENCRYPTED_VAR: Encrypted(c29tZSMjUmVhbGx5MDBDb21wbGljYXRlZD09U3RyaW5nXwo=)
        flutter: default
        xcode: latest
        cocoapods: default
      triggering:
        events:
          - push
        branch_patterns:
          - pattern: qa
            include: true
            source: true
      scripts:
        - echo "$MY_VAR"
        - echo $ENCRYPTED_VAR | base64 --decode
  ```
2. I push to `qa` and see a build has started, but it hangs forever

`ENCRYPTED_VAR` was created by doing a base64 encoding of `some##Really00Complicated==String_` and wrapping it within `Encrypted(...)`.
```
echo some##Really00Complicated==String_ | base64
```

### Expected results

I expect:
- The pipeline to start
- To print the unencrypted variable
- To print the decrypted value of the encrypted variable

### Actual results

My pipeline just hangs on `Preparing build machine` and times out after +- 10min, where the step logs only show:
```
0
```

### Build id (optional)

64df5d26a1615fab2fd74ec7
