### DISCUSSION TITLE
Add option 'label_patterns' to `triggering` section to only trigger workflows if a pull request has a specific label

### DISCUSSION THREAD

**Discussion by nilsreichardt** [codemagic-ci-cd/codemagic-docs#2080] [Ideas]
### Use case

I'm using the [`codemagic_app_preview` CLI](https://pub.dev/packages/codemagic_app_preview) to post app preview builds for the pull requests. However, if you don't have the unlimited plan, you might want to only trigger the workflow on pull requests with a specific label to avoid unnecessary builds. For that, it would be great to only trigger the workflow if the pull request has a specific label.

### Idea

**Idea:**

This is how it could like in the `codemagic.yaml`:

```yaml
workflows:
  app_preview:
    name: app_preview
    triggering:
      label_patterns:
        - pattern: 'build-app-preview'
          include: true
    scripts:
      ...
    artifacts:
      - build/**/outputs/apk/**/*.apk
      - build/ios/ipa/*.ipa
    publishing:
      scripts:
        - name: Post App Preview
          script: |
            dart pub global activate codemagic_app_preview
            app_preview post \
             --github_token $GITHUB_PAT \
             --codemagic_token $CODEMAGIC_TOKEN
```

**Current workaround:**

The current workaround is to create a GitHub Action that triggers the Codemagic build with the Codemagic Build API:

```yaml
name: App Preview

on:
  pull_request:
    types:
      - labeled
      - synchronize

jobs:
  label_app_preview:
    # Only run this job if the PR is labeled with "build-app-preview".
    #
    # Keep in mind that a new build will be triggered when the PR is labeled
    # with any lable as long as the label "build-app-preview" is included in the
    # list of labels. For example, if the PR is labeled with "build-app-preview"
    # and "bug", the job will be triggered when the label "bug" is removed.
    if: contains(github.event.pull_request.labels.*.name, 'build-app-preview')
    runs-on: ubuntu-22.04
    env:
      CODEMAGIC_TOKEN: ${{ secrets.CODEMAGIC_TOKEN }}
      CODEMAGIC_APP_ID: ${{ secrets.CODEMAGIC_APP_ID }}
      # From "codemagic.yaml"
      CODEMAGIC_WORKFLOW_ID: "app-preview"
    steps:
      - name: Start Codemagic Build
        run: |
          curl --request POST 'https://api.codemagic.io/builds' \
            -f \
            --header 'x-auth-token: '"$CODEMAGIC_TOKEN" \
            --header 'Content-Type: application/json' \
            --data-raw "{
                \"appId\": \"$CODEMAGIC_APP_ID\",
                \"branch\": \"$GITHUB_HEAD_REF\",
                \"workflowId\": \"$CODEMAGIC_WORKFLOW_ID\"
            }"
```

**Disclaimer:**

This is a low-priority feature request and there is an easy workaround for that. However, I'm creating this request to collect upvote to track if other customers have the same request and what use cases other customers have. If there is a certain demand for that, we could first add good docs for that.

If you are a Codemagic customer and you have another use case for this feature, please let us know in the comments.

**Comment by Ycoi** [comment]
Hi @nilsreichardt! Thanks for the feedback, actually you should already be able to do this using the when conditions as described in [our docs](https://docs.codemagic.io/yaml-running-builds/starting-builds-automatically/#using-condition-inside-when).  There are some examples there which use pull request labels as conditions.

**Reply by nilsreichardt** [reply]
Hi @Ycoi, thanks for suggestion. However, using `condition` is not an option for my use case because the workflow is not triggered if you assign a label after creation of the pull request.

Here an example with the label `build-app-preview`:

1. I open a pull request without any labels --> Codemagic skips this build because the label `build-app-preview` is not assigned.
2. I assign the label `build-app-preview` --> Codemagic does nothing, but for my use it should trigger here
3. Only when commenting a new build is triggered --> Codemagic checks the condition

**Comment by mikhail-tokarev** [comment]
Hey @nilsreichardt 
sorry for the radio silence. Looks like low hanging fruit to add `labeled` action for GitHub webhooks. In this case you don't need GitHub Actions and everything will work using `condition` rules. We will keep you in the loop

**Comment by mohammedbabelly20** [comment]
Hey @nilsreichardt,
Now Codemagic can handle the `labeled` action received from GitHub when you add a new label to your PR.

That being said, you can now get rid of the GitHub action to trigger a Codemagic build and just add a condition to your triggering section as described [here](https://docs.codemagic.io/yaml-running-builds/starting-builds-automatically/#using-condition-inside-when) to check the PR labels.

**Reply by mohammedbabelly20** [reply]
**UPDATE:** We now have a new triggering event called `pull_request_labeled` which triggers builds when adding a new label to a GitHub PR.

By default, if you have this event, it will start builds for every label you add, unless you limit it by a condition like this:
```
triggering:
  events:
    - pull_request_labeled
when:
  condition: event.pull_request.labels[0].name == "label"
```
