### DISCUSSION TITLE
No matching profiles found for bundle identifier

### DISCUSSION THREAD

**Discussion by JaafarRammal** [codemagic-ci-cd/codemagic-docs#2083] [Q&A]
### If you are looking for help, please confirm the following...

- [X] I confirm I have searched the [Docs](https://docs.codemagic.io), [Codemagic Sample Projects](https://github.com/codemagic-ci-cd/codemagic-sample-projects), and GitHub [Discussions](https://github.com/orgs/codemagic-ci-cd/discussions).
- [X] I confirm the software versions on my local computer match the ones in CI environment (e.g. Xcode version, Gradle version). See [here](https://docs.codemagic.io/troubleshooting/common-android-issues/#builds-work-locally-but-fail-on-codemagic)
- [X] I confirm I am able to do a fresh clone of the repository and build the project on my local computer.

### Which mobile framework are you using?

Flutter (Dart)

### Steps to reproduce

Hello. I am having an issue with profiles after moving my workflow from workflow editor (UI) to the `codemagic.yaml` config. My workflow was working fine when using the workflow editor (see screenshot below with the relevant configuration sections)

![image](https://github.com/codemagic-ci-cd/codemagic-docs/assets/45538723/fd985c1c-8bbf-410c-8452-81307b2ad2a4)

 When I moved to a `codemagic.yaml` config, it fails with the following:
 
```
No matching profiles found for bundle identifier "com.REDACTED.REDACTED" and distribution type "app_store"
```

I have verified both the key name `CodeMagic - CICD` and the bundle identifier `com.REDACTED.REDACTED` match.

Here is my config:

```yaml
workflows:
  ios-workflow:
    name: Build and publish ios app
    instance_type: mac_mini_m1
    max_build_duration: 10
    integrations:
      app_store_connect: CodeMagic - CICD
    environment:
      flutter: stable
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.REDACTED.REDACTED
    cache:
      cache_paths:
        - $HOME/Library/Caches/CocoaPods
        - $FLUTTER_ROOT/.pub-cache
    triggering:
      events:
        - push
      tag_patterns:
        - pattern: '([0-9]).+([0-9]).+([0-9])\++([0-9])'
          include: true
      cancel_previous_builds: true
    scripts:
      - name: Echo out parsed tags
        script: |
          echo "Tag on trigger: $CM_TAG"
          IFS=- read -r BUILD_NAME BUILD_NUMBER <<< $CM_TAG
          echo "Build name: $BUILD_NAME"
          echo "Build number: $BUILD_NUMBER"
      - name: Set up code signing settings on Xcode project
        script: | 
          xcode-project use-profiles
      - name: Get Flutter packages
        script: | 
          flutter packages pub get
      - name: Install pods
        script: | 
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter analyze
        script: | 
          flutter analyze
      - name: Flutter build ipa
        script: | 
          IFS=- read -r BUILD_NAME BUILD_NUMBER <<< $CM_TAG
          flutter build ipa --release \
            --build-name=$BUILD_NAME \
            --build-number=$BUILD_NUMBER \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true 
      email:
        recipients:
          - REDACTED
        notify:
          success: true
          failure: true
```

### Expected results

I expected the CI to build fine

### Actual results

The CI is note building fine

### Build id (optional)

6518100e8f36db3b59e4a017
