### DISCUSSION TITLE
Fails to find apk even though it's verified to be there

### DISCUSSION THREAD

**Discussion by movaid7** [codemagic-ci-cd/codemagic-docs#2143] [Q&A] [answered]
### If you are looking for help, please confirm the following...

- [X] I confirm I have searched the [Docs](https://docs.codemagic.io), [Codemagic Sample Projects](https://github.com/codemagic-ci-cd/codemagic-sample-projects), and GitHub [Discussions](https://github.com/orgs/codemagic-ci-cd/discussions).
- [X] I confirm the software versions on my local computer match the ones in CI environment (e.g. Xcode version, Gradle version). See [here](https://docs.codemagic.io/troubleshooting/common-android-issues/#builds-work-locally-but-fail-on-codemagic)
- [X] I confirm I am able to do a fresh clone of the repository and build the project on my local computer.

### Which mobile framework are you using?

Flutter (Dart)

### Steps to reproduce

1. Setup build step with [Shorebird](https://docs.shorebird.dev/ci/codemagic) to produce an APK file output
`shorebird release android --artifact=apk --force`
2. Setup publishing to Firebase App Distribution with artifact_type of apk
```yaml
publishing:
  firebase:
    # authenticate via service account
    firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
    android:
      app_id: {my_app_id}
      groups:
        - Alpha
      artifact_type: "apk"
```

### Expected results

I've added a script that runs after the Shorebird build command to verify that the apk `app-release.apk` was created in the release folder:

_Command_
```bash
echo "🔍 Checking APK directory contents..."
ls build/app/outputs/apk/release/
```

_Output_
```
🔍 Checking APK directory contents...
app-release.apk
output-metadata.json
```

Since the APK (app-release.apk) is clearly present in the release folder, the subsequent publishing step should find this APK and push it to Firebase App Distribution as a new release.

_Publishing Config_
```yaml
publishing:
  firebase:
    # authenticate via service account
    firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
    android:
      app_id: {my_app_id}
      groups:
        - Alpha
      artifact_type: "apk"
```

### Actual results

- Shorebird build completes successfully
- APK is verified to be present in the release folder
- Yet, the publishing step fails stating that no artifacts were found

_Publishing Output_
```
== Gathering artifacts ==
No artifacts were found
```

### Build id (optional)

6537d06ddaa4bfe81980fe16

**Comment by dtrdic** [comment, marked as answer]
hey @movaid7, i think you are missing a section in your yaml file where you specify what files or outputs should be saved
```
        artifacts:
          - build/**/outputs/**/*.apk
        publishing:
          firebase:
              firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
              android:
                app_id: 1:xxx:android:xxx
```
like this you define the artifacts that should be collected and saved after the build process is completed
