### DISCUSSION TITLE
Upload dSym file - Unable to read Google Service plist

### DISCUSSION THREAD

**Discussion by thangmoxielabs** [codemagic-ci-cd/codemagic-docs#2146] [Q&A] [answered]
### If you are looking for help, please confirm the following...

- [X] I confirm I have searched the [Docs](https://docs.codemagic.io), [Codemagic Sample Projects](https://github.com/codemagic-ci-cd/codemagic-sample-projects), and GitHub [Discussions](https://github.com/orgs/codemagic-ci-cd/discussions).
- [X] I confirm the software versions on my local computer match the ones in CI environment (e.g. Xcode version, Gradle version). See [here](https://docs.codemagic.io/troubleshooting/common-android-issues/#builds-work-locally-but-fail-on-codemagic)
- [X] I confirm I am able to do a fresh clone of the repository and build the project on my local computer.

### Which mobile framework are you using?

Flutter (Dart)

### Context: I have a workflow in Workflow Editor that uses the same script in step 3. I'm migrating to the codemagic.yaml and it fails to upload dSym files.

1. Set up
```
environment:
    groups:
        - firebase_credentials
...
publishing:
      firebase:
        firebase_service_account: $GOOGLE_APPLICATION_CREDENTIALS
        android: 
          app_id: # app_id
          artifact_type: aab
        ios: 
          app_id: # app_id
```
Where $GOOGLE_APPLICATION_CREDENTIALS env var is set to $CM_BUILD_DIR/firebase_credentials.json.
$GCLOUD_SERVICE_ACCOUNT_CREDENTIALS env var is set to be the content of the credential json file.

2. Run build ipa
3. Upload dSym file
```
echo "Find build artifacts"
dsymPath=$(find $CM_BUILD_DIR/hg_mobile_app/build/ios/archive/Runner.xcarchive -name "*.dSYM")

if [[ -z ${dsymPath} ]] 
then 
  echo "No debug symbols were found at $dsymPath, skip publishing to Firebase Crashlytics" 
else 
  echo "Publishing debug symbols from $dsymPath to Firebase Crashlytics" 
  ls -d -- $CM_BUILD_DIR/* 
  $CM_BUILD_DIR/hg_mobile_app/ios/Pods/FirebaseCrashlytics/upload-symbols \
    -gsp hg_mobile_app/ios/Runner/GoogleService-Info.plist -p ios $dsymPath 
fi
```

### Expected results

dSym files are uploaded successfully 

### Actual results

```
error: Unable to read Google Service plist at path hg_mobile_app/ios/Runner/GoogleService-Info.plist
```

### Build id (optional)

6537f749000d733194bfb8ce
