### DISCUSSION TITLE
Conditions inside when seems to be broken

### DISCUSSION THREAD

**Discussion by greg0x** [codemagic-ci-cd/codemagic-docs#2158] [Q&A]
### If you are looking for help, please confirm the following...

- [X] I confirm I have searched the [Docs](https://docs.codemagic.io), [Codemagic Sample Projects](https://github.com/codemagic-ci-cd/codemagic-sample-projects), and GitHub [Discussions](https://github.com/orgs/codemagic-ci-cd/discussions).
- [X] I confirm the software versions on my local computer match the ones in CI environment (e.g. Xcode version, Gradle version). See [here](https://docs.codemagic.io/troubleshooting/common-android-issues/#builds-work-locally-but-fail-on-codemagic)
- [X] I confirm I am able to do a fresh clone of the repository and build the project on my local computer.

### Which mobile framework are you using?

-

### Steps to reproduce

1. Have a workflow similar to this — note: I put this script here, it might not run but shows the problem 
```
workflows:
  demo:
    triggering:
      events:
        - pull_request
      branch_patterns:
        - pattern: "main"
          include: true
          source: false
      cancel_previous_builds: true
    when:
      condition: (not event.pull_request.head.ref == "bump-version") and (not event.pull_request.draft)
    scripts:
      - echo "yo, I should not run if CM_BRANCH is "bump-version" or the PR is draft. CM_BRANCH: ${CM_BRANCH}"
```
2. open a draft pr => workflow runs but it shouldn't 
3. open a pr from "bump-version" branch => workflow runs but it shouldn't
4. open a pr from "bump-version" branch + merge it quickly + delete the branch => workflow runs, but it shouldn't and fails on fetching app sources with the error "Failed to merge with remote source/bump-version"

### Expected results

2. workflow doesn't run or quit early
3. workflow doesn't run or quit early
4. workflow doesn't run or quit early

### Actual results

2. open a draft pr => workflow runs but it shouldn't 
3. open a pr from "bump-version" branch => workflow runs but it shouldn't
4. open a pr from "bump-version" branch + merge it quickly + delete the branch => workflow runs, but it shouldn't and fails on fetching app sources with the error "Failed to merge with remote source/bump-version"

### Build id (optional)

653ba4ceb495bd0a6e65f511

**Comment by dtrdic** [comment]
hey @greg-nagy, just a note that the build will always be triggered but only after fetching app sources and meeting the condition you set, the build will be stopped

**Reply by greg0x** [reply]
My issue comes from the fact that checkout happens before checking the condition.

My 2c would be to check the condition first and only then try to check out the code — I understand that this will lead to complications with changeset-based filters. The full solution probably would require checking the conditions in 2 stages, before and after checkout. 

The below use-case forces me to use trigger trickery to orchestrate the runs, drop best practices, and push the bump to main or accept the failed test run result after the bump.

Open a PR from the "bump-version" branch + merge it quickly + delete the branch => The PR unit test workflow starts running =>  but the branch is already deleted => it fails to fetch app sources with the error "Failed to merge with remote source/bump-version" => my main is marked with failed tests.

We can work around or live with this, but it feels weird to spend time on.

**Reply by greg0x** [reply]
hm, the issue might be worse than it seems

```
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: "ctc-v*_main-v*"
          include: true
      cancel_previous_builds: true
```

is it normal that a workflow with this config is running on PRs?

**Reply by dtrdic** [reply]
hey @greg-nagy i have not been able to reproduce your latest issue, tag triggering is working as expected. I used the same tag pattern `pattern: "ctc-v*_main-v*"` and created a tag `ctc-v1_main-v1` which started a build normally. Then I tried to create a PR and no build has been triggered since I didn't specify the pull request event.

```
    triggering:
      events:
          - tag
      tag_patterns:
        - pattern: "ctc-v*_main-v*" 
          include: true
      branch_patterns:
      - pattern: main
        include: true
```

Can you give me some steps to reproduce? Please share build id as well
