### DISCUSSION TITLE
Is there a way to send an Email to the Account which performed the commit.

### DISCUSSION THREAD

**Discussion by erbenjak** [codemagic-ci-cd/codemagic-docs#2198] [Q&A] [answered]
### If you are looking for help, please confirm the following...

- [X] I confirm I have searched the [Docs](https://docs.codemagic.io), [Codemagic Sample Projects](https://github.com/codemagic-ci-cd/codemagic-sample-projects), and GitHub [Discussions](https://github.com/orgs/codemagic-ci-cd/discussions).
- [X] I confirm the software versions on my local computer match the ones in CI environment (e.g. Xcode version, Gradle version). See [here](https://docs.codemagic.io/troubleshooting/common-android-issues/#builds-work-locally-but-fail-on-codemagic)
- [X] I confirm I am able to do a fresh clone of the repository and build the project on my local computer.

### Which mobile framework are you using?

Flutter (Dart)

### Steps to reproduce

1. Some github Account commits to the repository
2. The codemagic workflow is triggered 
3. It produces the build
4. It sends an email to the account which performed the commit

### Expected results

It should be possible to send an email to an adress, which is determined during runtime of the codemagic workflow.

### Actual results

When putting an variabe (either local or environment ) in the recipients list it leads to the script failing

**Comment by himesh-cm** [comment, marked as answer]
Hi @erbenjak,
You can obtain the email address for a specific commit using the `git log` command. 
Save the email address in an environment variable and trigger a notification using a service like SendGrid or Mailgun.
for example:
```
AUTHOR_EMAIL=$(git log -1 --format='%ae' $CM_COMMIT)
```
where `CM_COMMIT` is 
Commit hash that is currently being built by Codemagic, for pull request builds it is the hash of the source commit.
You need to set up a personal access token as described in the [GitHub documentation](https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token).

**Reply by erbenjak** [reply]
Although this solution is certainly functional, I would highly prefer the convenience of performing this task directly within Codemagic. This would furthermore keep things cleaner and more straightforward. This boils down to the following: I aim to send an email to an email address determined dynamically within my Codemagic workflow.

It could look something like this:
1. Determine the address in a 1st step
 ```yaml
AUTHOR_EMAIL=$(git log -1 --format='%ae' $CM_COMMIT) #or some other function that determines an email
```
2. Use this adress in the publish step
 ```yaml
publishing:
      email:
        recipients:
          - $AUTHOR_EMAIL
```

@himesh-cm Is this possible? If not, can this be formulated as a feature request?

**Reply by himesh-cm** [reply]
You can use environment variables in step 2, which you shared above.
However, the command to fetch the author's email returns `no-reply-user-specific-git-address`, which might not work here.
There is an option to set a commit email address, and you can read more about it [here](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address).

**Reply by erbenjak** [reply]
Maybe I get something wrong about this, but I can not confirm this behavoir.
I have an environment variable (called email_address), in which I stored a private email adress for testing. 
I then run a script which looks like this.

```yaml
- name: Setting dynamic email address
        script: |
          export email_address ="example@company-address.com"
          echo $email_address 
```
'Echo' rightly returns the changed value.

And then I use this variable in publishing:
```yaml
publishing:
     email:
       recipients:
         - $email_address 
```

But the emails keep ending up in my private email as if the script did not change the value.

Maybe this is a stupid mistake on my side - I'm a beginner to codemagic.

**Reply by himesh-cm** [reply]
Hi @erbenjak, Please share a build id, so i can look into this.

**Reply by erbenjak** [reply]
Hi @himesh-cm. I have built you an minimal example to keep things simple. 

ID: 6569a9a3e32f10c867844877
Build number: 6

codemagic.yaml:
```yaml
workflows:
  android-workflow:
    name: Email Test Workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      flutter: stable
      groups:
        - email-variables

    triggering:
      events:
        - push
      branch_patterns: # Include or exclude watched branches
        - pattern: "*"
          include: true
          source: true

    scripts:
      - name: Dynamic email change
        script: |
          export email_address="my-email@company.com"
          echo $email_address 

      - name: Set up local.properties
        script: echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"

      - name: Get Flutter packages
        script: flutter pub get


      - name: Build Android-Application-Bundle  with Flutter
        script: |
          BUILD_NUMBER=1
          flutter build apk --debug \
            --build-name=1.0.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER \   

    artifacts:
      - build/**/outputs/flutter-apk/*.apk
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log

    publishing:
      email:
        recipients:
          - $email_address
        notify:
          success: true
          failure: true
```
I can assure you that the email arrived at the address specified initially, not in my-email@company.com. Which should get set in step "Dynamic email change".
