### DISCUSSION TITLE
React native: "MyApp" requires a provisioning profile. Select a provisioning profile in the Signing & Capabilities editor

### DISCUSSION THREAD

**Discussion by Bebrevski** [codemagic-ci-cd/codemagic-docs#2249] [Q&A] [answered]
### If you are looking for help, please confirm the following...

- [X] I confirm I have searched the [Docs](https://docs.codemagic.io), [Codemagic Sample Projects](https://github.com/codemagic-ci-cd/codemagic-sample-projects), and GitHub [Discussions](https://github.com/orgs/codemagic-ci-cd/discussions).
- [X] I confirm the software versions on my local computer match the ones in CI environment (e.g. Xcode version, Gradle version). See [here](https://docs.codemagic.io/troubleshooting/common-android-issues/#builds-work-locally-but-fail-on-codemagic)
- [X] I confirm I am able to do a fresh clone of the repository and build the project on my local computer.

### Which mobile framework are you using?

React Native

### Steps to reproduce

1. I don't have actual MAC machine. I use the provided from Codemagic.io, so I don't have successfull build on my local machine
2. react-native - 0.72.7
3. XCode 15 & 14
4. codemagic.yaml file
```
react-native-ios:
        name: React Native iOS
        environment:
            ios_signing:
                provisioning_profiles:
                    - valid provisioning_profile
                certificates: 
                    - valid certificate
            vars:
              BUNDLE_ID: "my.bundle.id"
              XCODE_SCHEME: "APP"
              XCODE_WORKSPACE: "APP.xcworkspace"
            node: v19.7.0
            xcode: 14.2
            cocoapods: default
        integrations:
          app_store_connect: CodeMagic.io Dev & App Manager
        scripts:
          - name: Install Dependencies and Prepare React Native Project
            script: |
              yarn install && yarn global add react-native

          - name: Set up code signing settings on Xcode project
            script: |
              xcode-project use-profiles 

          - name: Build ipa for distribution
            script: |
              cd ios && pod install && pod update
xcode-project build-ipa --workspace $XCODE_WORKSPACE --scheme "$XCODE_SCHEME"
        artifacts:
            - build/ios/ipa/*.ipa
            - /tmp/xcodebuild_logs/*.log
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
```
           
https://codemagic.io/app/6560b6738a3b0b03874faf62/build/65707e6e749000976c48f104

### Expected results

I am expecting to build iOS application and get .ipa file as artifact. Keep in mind that I don't have any problems with .apk/aab build for Android. 

### Actual results

Using Xcode 14.2 (14C18)
Check POCReactNative.xcworkspace build settings
Execute "xcodebuild -workspace /Users/builder/clone/ios/POCReactNative.xcworkspace -scheme POCReactNative -showBuildSettings"

Archive POCReactNative.xcworkspace
Execute "xcodebuild -workspace /Users/builder/clone/ios/POCReactNative.xcworkspace -scheme POCReactNative -archivePath build/ios/xcarchive/POCReactNative_2sxzszd_.xcarchive archive COMPILER_INDEX_STORE_ENABLE=NO CODE_SIGN_STYLE=Manual"

❌  /Users/builder/clone/ios/POCReactNative.xcodeproj: error: "POCReactNative" requires a provisioning profile. Select a provisioning profile in the Signing & Capabilities editor. (in target 'POCReactNative' from project 'POCReactNative')

    Run script build phase 'Start Packager' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'POCReactNative' from project 'POCReactNative')
    Run script build phase 'Bundle React Native code and images' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'POCReactNative' from project 'POCReactNative')
Failed to archive /Users/builder/clone/ios/POCReactNative.xcworkspace

Build failed :|
Step 8 script `Build ipa for distribution` exited with status code 65

### Build id (optional)

65707e6e749000976c48f104
