### DISCUSSION TITLE
.NET 8 MAUI - Android SDK platform for API level 34 is not installed

### DISCUSSION THREAD

**Discussion by ZeroCoolJr** [codemagic-ci-cd/codemagic-docs#2255] [Q&A]
### If you are looking for help, please confirm the following...

- [X] I confirm I have searched the [Docs](https://docs.codemagic.io), [Codemagic Sample Projects](https://github.com/codemagic-ci-cd/codemagic-sample-projects), and GitHub [Discussions](https://github.com/orgs/codemagic-ci-cd/discussions).
- [X] I confirm the software versions on my local computer match the ones in CI environment (e.g. Xcode version, Gradle version). See [here](https://docs.codemagic.io/troubleshooting/common-android-issues/#builds-work-locally-but-fail-on-codemagic)
- [X] I confirm I am able to do a fresh clone of the repository and build the project on my local computer.

### Which mobile framework are you using?

Other - please mention in your question

### Steps to reproduce

I've followed the steps to build .NET MAUI apps as documented here: https://docs.codemagic.io/yaml-quick-start/building-a-dotnet-maui-app/ but with some changes as I'm using .NET 8 instead of .NET 6.

### Expected results

This will build successfully.

### Actual results

The build failed with this error "Android SDK platform for API level 34 is not installed".

### Build id (optional)

6572cfb17bc4a45da3799321

**Comment by donpaul120** [comment]
We need android-34 pre-installed as android sdk

**Comment by icarusdust** [comment]
Hi, have you tried installing it from your build pipeline? The following script should install Android SDK 34 by setting the required Java version alongside:

```yaml
        - name: Android Build-tools
          script: |
              JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home
              $ANDROID_SDK_ROOT/tools/bin/sdkmanager --install "build-tools;34.0.0"
```
