### DISCUSSION TITLE
Flutter Windows tests failing

### DISCUSSION THREAD

**Discussion by jpohhhh** [codemagic-ci-cd/codemagic-docs#2282] [Q&A]
### If you are looking for help, please confirm the following...

- [X] I confirm I have searched the [Docs](https://docs.codemagic.io), [Codemagic Sample Projects](https://github.com/codemagic-ci-cd/codemagic-sample-projects), and GitHub [Discussions](https://github.com/orgs/codemagic-ci-cd/discussions).
- [X] I confirm the software versions on my local computer match the ones in CI environment (e.g. Xcode version, Gradle version). See [here](https://docs.codemagic.io/troubleshooting/common-android-issues/#builds-work-locally-but-fail-on-codemagic)
- [X] I confirm I am able to do a fresh clone of the repository and build the project on my local computer.

### Which mobile framework are you using?

Flutter (Dart)

### Steps to reproduce

I have a YAML-based Flutter setup, for macOS, Windows, Linux testing, and iOS builds.
(YAML at bottom)

The Windows test setup fails with a "Something went wrong" error.
The tests are running successfully, at least, the 
[flutter.json](https://github.com/codemagic-ci-cd/codemagic-docs/files/13744140/flutter.json) looks as expected. There's a few test failures but nothing unexpected / fatal on other platforms.

I have a feeling I'm just missing something simple about Windows paths...but I'm not sure.

I've tried downloading each of the build logs steps, as well as logging into the build machine and poking around files, but can't find anything to add more info to the "Build failed :| Something went wrong" error shown.

Error:
```
Directory: C:\Users\builder\clone


Mode                LastWriteTime         Length Name                                                                  
----                -------------         ------ ----                                                                  
d-----       12/21/2023   4:26 PM                test-results                                                          


Build failed :|
Something went wrong
```

YAML:
```yaml
definitions:
  ...definitions unused by windows flow...
  instance_windows: &instance_windows
    instance_type: windows_x2 # https://docs.codemagic.io/yaml-basic-configuration/yaml-getting-started/#instance-type
    max_build_duration: 15
  env_versions: &env_versions
    flutter: stable
    xcode: latest
    cocoapods: default
  env_keys: &env_keys
    groups:
      - app
      - codecov
  ... more definitions unused by windows flow...
  script_build_runner_build: &script_build_runner_build
    name: Build runner build
    script: flutter pub run build_runner build --delete-conflicting-outputs
  script_pub_get: &script_pub_get
    name: flutter pub get
    script: flutter pub get
  script_run_tests_windows: &script_run_tests_windows
    name: Tests
    script: |
      mkdir -p test-results
      flutter test --coverage --machine > test-results\flutter.json
    test_report: test-results\flutter.json
  flutter_test_artifacts_windows: &flutter_test_artifacts_windows
    - C:\Users\builder\clone\test-results\flutter.json
   
workflows:
... other workflows
  windows-test:
    name: Windows Test
    <<: *instance_windows
    environment:
      <<: *env_versions
      <<: *env_keys
    scripts:
      - <<: *script_build_runner_build
      - <<: *script_run_tests_windows
    artifacts: *flutter_test_artifacts_windows
```

### Expected results

Codemagic run completes. File with test results is attached. Tests step shows test failures.

### Actual results

Codemagic run completes. File with test results is attached. Tests step shows "Build failed :| Something went wrong" 

### Build id (optional)

6584647c8d3ead7900c8e3ea
