### DISCUSSION TITLE
Failed build windows flutter app, due to permission denied

### DISCUSSION THREAD

**Discussion by garawiyudha** [codemagic-ci-cd/codemagic-docs#2285] [Q&A]
### If you are looking for help, please confirm the following...

- [X] I confirm I have searched the [Docs](https://docs.codemagic.io), [Codemagic Sample Projects](https://github.com/codemagic-ci-cd/codemagic-sample-projects), and GitHub [Discussions](https://github.com/orgs/codemagic-ci-cd/discussions).
- [X] I confirm the software versions on my local computer match the ones in CI environment (e.g. Xcode version, Gradle version). See [here](https://docs.codemagic.io/troubleshooting/common-android-issues/#builds-work-locally-but-fail-on-codemagic)
- [X] I confirm I am able to do a fresh clone of the repository and build the project on my local computer.

### Which mobile framework are you using?

Flutter (Dart)

### Steps to reproduce

Hello, im getting this error when build windows app through codemagic that using private repo as dependency, 
i have search to all docs and still found nothing, is there anyone here faced the same issue ? 
```
fatal: Unable to persist credentials with the 'wincredman' credential store.
See https://aka.ms/gcm/credstores for more information.
error: unknown option `timeout'
usage: git credential-cache [options] <action>

    credential-cache is disabled in this build of Git
```

here are my config on my codemagic.yaml 
```

  # WINDOWS
  windows-prod:
    name: Windows Prod
    instance_type: windows_x2
    max_build_duration: 120
    environment:
      groups:
        - google_credentials
        - retina_credential
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: "build/*"
          include: true
    scripts:
      - *install_cert_for_windows
      - *clean_get_gen
      - *generate_intl
      - name: Build exe for distribution
        script: |
          flutter build windows --release -t lib/main_dev.dart --dart-define FLAVOR=production
      - *copy_windows_dll_resources
      - name: Build msix
        script: flutter pub run msix:create --publisher  --install-certificate false
    artifacts:
      - *msix
    publishing:
      <<: *email_develop
```

### Expected results

i wish i can build an windows app from codemagic

### Actual results

i cant build windows app from codemagic
