### DISCUSSION TITLE
Scheduled builds fail because of when condition

### DISCUSSION THREAD

**Discussion by marcocaldera** [codemagic-ci-cd/codemagic-docs#2382] [Q&A] [answered]
### If you are looking for help, please confirm the following...

- [X] I confirm I have searched the [Docs](https://docs.codemagic.io), [Codemagic Sample Projects](https://github.com/codemagic-ci-cd/codemagic-sample-projects), and GitHub [Discussions](https://github.com/orgs/codemagic-ci-cd/discussions).
- [X] I confirm the software versions on my local computer match the ones in CI environment (e.g. Xcode version, Gradle version). See [here](https://docs.codemagic.io/troubleshooting/common-android-issues/#builds-work-locally-but-fail-on-codemagic)
- [X] I confirm I am able to do a fresh clone of the repository and build the project on my local computer.

### Which mobile framework are you using?

React Native

### Steps to reproduce

I've the following when condition to trigger a specific type of build:
```
    triggering:
      events:
        - pull_request_labeled
    when:
      condition: event.pull_request.labels[0].name == "Build"
```
I want to reuse the same workflow in the scheduler but it fails because it check the label condition.

How can I use the same workflow for labelling and scheduling?

### Expected results

-

### Actual results

-

**Comment by himesh-cm** [comment]
Hello @marcocaldera,

I apologize for the delay in getting back to you. Unfortunately, the `event` variable is not currently available with scheduled builds. This means that there is currently no way to check if the build was triggered via the scheduler in your YAML file. 

If you could provide me with more details about your use case, I can share them with the developers on our team.

**Reply by marcocaldera** [reply, marked as answer]
Our use case is to re-use the same workflow that we are using with `when` conditions also in a scheduled build.

At the moment we found this solution:

```
    triggering:
      events:
        - pull_request_labeled
    when:
      condition: event.pull_request == null or event.pull_request.labels[0].name == "Build"
```
