### DISCUSSION TITLE
My .yaml file is unable to grab the artifacts from a custom route

### DISCUSSION THREAD

**Discussion by Alejandroem** [codemagic-ci-cd/codemagic-docs#2462] [Q&A]
### If you are looking for help, please confirm the following...

- [X] I confirm I have searched the [Docs](https://docs.codemagic.io), [Codemagic Sample Projects](https://github.com/codemagic-ci-cd/codemagic-sample-projects), and GitHub [Discussions](https://github.com/orgs/codemagic-ci-cd/discussions).
- [X] I confirm the software versions on my local computer match the ones in CI environment (e.g. Xcode version, Gradle version). See [here](https://docs.codemagic.io/troubleshooting/common-android-issues/#builds-work-locally-but-fail-on-codemagic)
- [X] I confirm I am able to do a fresh clone of the repository and build the project on my local computer.

### Which mobile framework are you using?

Other - please mention in your question

### Steps to reproduce

Change the artifacts path to a different location pointin to an iPA and using appstore integration for publishing the build
![Screenshot 2024-04-09 at 11 34 56](https://github.com/codemagic-ci-cd/codemagic-docs/assets/12418734/dae04e7a-e1f2-4663-8369-151873cb17c4)

### Expected results

I was expecting the .ipa to appear on the artifacts list, and also to be published

### Actual results

no artifacts are found and nothing is published, I need some help as one client is waiting for this to get completed. 🙏🏻 

### Build id (optional)

66154ea0f8ffb6cd1e2f80f1

**Comment by Alejandroem** [comment]
I have also tried with the code magic cli-tools, as you can see on the image, the .ipa gets built but it never gets pushed to the account?


![Screenshot 2024-04-09 at 17 21 48](https://github.com/codemagic-ci-cd/codemagic-docs/assets/12418734/f76449f8-ab8f-4d19-94ae-cd4eda7a9285)

**Reply by himesh-cm** [reply]
Hi @Alejandroem, For debugging purposes, can you SSH into the build machine as shown [here](https://docs.codemagic.io/troubleshooting/accessing-builder-machine-via-ssh/) and check the path of the `.ipa` file to be sure?
Once the preparation build machine step is over, you can initiate the SSH session.

**Reply by Alejandroem** [reply]
<img width="1440" alt="Screenshot 2024-04-12 at 14 41 33" src="https://github.com/codemagic-ci-cd/codemagic-docs/assets/12418734/7fd11cf6-df7e-4e56-a562-c9d1ee811bd4">

Yes the .ipa file is there as you can see in the image

build id 661979a9a9c675ceeaa00177

**Reply by Alejandroem** [reply]
For more context here is my yaml file

```yaml
workflows:
  kivy-ios:
    name: Kivy iOS Build
    integrations:
      app_store_connect: BOA_Transport
    environment:
      xcode: 15.1
      groups:
        - boa
      vars:       
        XCODE_WORKSPACE: "boa-transport-ios/boa-transport.xcodeproj"
        XCODE_SCHEME: "boa-transport"
      ios_signing:
        distribution_type: app_store
        bundle_identifier: "BOA.boa-transport"

    cache:
      cache_paths:
        - ~/.buildozer
        - ~/.cache/pip
        - build/
        - dist/ 

    scripts:
      - name: Set up SSH key
        script: |
          echo $GITHUB_SSH_KEY > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Clone submodules
        script: |
          git submodule update --init --recursive

      - name: Install Python and pip and other dependencies
        script: |
          brew install python3
          python3 -m ensurepip
          brew install autoconf automake libtool pkg-config
          brew link libtool

      - name: Install virtual env
        script: |
          python3 -m pip install virtualenv
          python3 -m virtualenv venv
          source venv/bin/activate

      - name: Install Dependencies
        script: |
          python3 -m pip install kivy
          python3 -m pip install Cython==3.0.0
          python3 -m pip install pip install kivy-ios
      
      - name: Install dependencies from requirements.txt
        script: |
          python3 -m pip install -r "$FCI_BUILD_DIR/requirements.txt"
      
      - name: Build the Kivy iOS 
        script: |
          toolchain build python3 kivy
          toolchain build python3 libjpeg
          toolchain build python3 pillow
          toolchain build python3 freetype
          toolchain build python3 hostpython3
          toolchain build python3 pyobjus
          toolchain pip install --no-deps kivymd               
        
      - name: Setup folders
        script: |
          cd ..
          git clone git@github.com:A-G-BOA/BOA_transport.git
          directory=$(pwd)
          cd clone
          toolchain create boa-transport-ios-app "$directory/BOA_transport"

      - name: Copy info.plist
        script: |
          cp boa-transport-Info.plist boa-transport-ios-app-ios/boa-transport-ios-app-Info.plist
          cp exportOptions.plist boa-transport-ios-app-ios/exportOptions.plist
          cp exportOptions.plist /Users/builder/export_options.plist     

      - name: Set up provisioning profiles settings on Xcode project
        script: |
          xcode-project use-profiles \
          --project $FCI_BUILD_DIR/boa-transport-ios-app-ios/boa-transport-ios-app.xcodeproj

      - name: Build ipa for distribution
        script: | 
          xcode-project build-ipa \
          --project $FCI_BUILD_DIR/boa-transport-ios-app-ios/boa-transport-ios-app.xcodeproj \
          --scheme boa-transport-ios-app      

    artifacts:
      - /Users/builder/clone/build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      email:
        recipients:
          - alexalejandroem@gmail.com
        notify:
          success: true
          failure: false
      app_store_connect:
        auth: integration 
        submit_to_testflight: true
        expire_build_submitted_for_review: true

    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: "*"
          include: true
          source: true
```

And my exportOptions.plist
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>method</key>
    <string>app-store</string> <!-- Use "ad-hoc", "package", "enterprise", or "development" as needed -->
    <key>teamID</key>
    <string>B7JXL739R3</string> <!-- Your development team ID -->
    <key>uploadSymbols</key>
    <false/> <!-- Optional: Set to false if you don't want to upload symbols to App Store Connect -->
    <key>uploadBitcode</key>
    <false/> <!-- Optional: Set to false if you don't want to include Bitcode -->
    <key>compileBitcode</key>
    <false/> <!-- Optional: Set to false to prevent recompilation of Bitcode -->    
    <!-- Include provisioning profiles if needed, especially for non-automatic signing or specific configurations -->
    <key>provisioningProfiles</key>
    <dict>
        <key>BOA.boa-transport</key>
        <string>Name or UUID of the provisioning profile</string>
    </dict>
    <!-- Specify signing certificate if needed, otherwise it's determined automatically -->
    <key>signingCertificate</key>
    <string>boa_distribution</string>
    <!-- Add any additional options required for your specific deployment strategy -->
</dict>
</plist>
```
