### DISCUSSION TITLE
Flutter analyze throws a lot of errors on Linux instance and not on Mac

### DISCUSSION THREAD

**Discussion by nursultan-akhmetzhanov** [codemagic-ci-cd/codemagic-docs#2563] [Q&A] [answered]
### If you are looking for help, please confirm the following...

- [X] I confirm I have searched the [Docs](https://docs.codemagic.io), [Codemagic Sample Projects](https://github.com/codemagic-ci-cd/codemagic-sample-projects), and GitHub [Discussions](https://github.com/orgs/codemagic-ci-cd/discussions).
- [X] I confirm the software versions on my local computer match the ones in CI environment (e.g. Xcode version, Gradle version). See [here](https://docs.codemagic.io/troubleshooting/common-android-issues/#builds-work-locally-but-fail-on-codemagic)
- [X] I confirm I am able to do a fresh clone of the repository and build the project on my local computer.

### Which mobile framework are you using?

Flutter (Dart)

### Steps to reproduce

Here is the sanitised YAML configuration of the codemagic.yaml file:

```
definitions:
  instance_mac_mini_m2: &instance_mac_mini_m2
    instance_type: mac_mini_m2
    max_build_duration: 60
  instance_mac_mini_m1: &instance_mac_mini_m1
    instance_type: mac_mini_m1
    max_build_duration: 60
  instance_linux: &instance_linux
    instance_type: linux
    max_build_duration: 60
  env_settings: &env_settings
    flutter: 3.16.9
    xcode: latest
    cocoapods: default
    groups:
      - ExampleGroup
  production_triggering: &production_triggering
    events:
      - push
      - tag
    branch_patterns:
      - pattern: release/production
        include: true
    tag_patterns:
      - pattern: production-release
        include: true
  test_triggering: &test_triggering
    events:
      - tag
    tag_patterns:
      - pattern: test-release
        include: true
  cache: &cache_paths
    cache_paths:
      - $HOME/Library/Caches/CocoaPods
      - $HOME/.gradle/caches
      - $FLUTTER_ROOT/.pub-cache
  artifacts: &flutter_artifacts
    - build/**/outputs/bundle/**/*.aab
    - build/ios/ipa/*.ipa
    - build/**/outputs/**/mapping.txt
    - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/Runner.app.dSYM
    - symbols/*.symbols
  app_store_connect_credentials: &app_store_connect_credentials
    api_key: $APP_STORE_CONNECT_PRIVATE_KEY
    key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
    issuer_id: $APP_STORE_CONNECT_ISSUER_ID
  google_play: &google_play
    credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
    track: internal
  scripts:
    - &set_up_ios_code_signing
      name: Set up iOS code signing
      script: |
        keychain initialize
        keychain add-certificates
    - &install_dependencies
      name: Install dependencies
      script: |
        flutter pub cache repair
        flutter pub get
        flutter pub get ./apps/widgetbook
        dart pub get --directory scripts/set_version
    - &generate_localizations
      name: Generate localizations
      script: |
        set -e
        flutter pub run intl_utils:generate
        dart scripts/arb_checker.dart
    - &analyze_and_test
      name: Analyze and test
      script: |
        set -e
        flutter analyze
        flutter test
    - &set_app_version
      name: Set app version
      script: |
        dart run scripts/set_version/bin/set_version.dart
    - &generate_test_release_notes
      name: Generate test build release notes
      script: ./scripts/release_notes.sh
    - &build_ios
      name: Build iOS
      script: |
        set -e
        set -x
        xcode-project use-profiles
        flutter build ipa --export-options-plist ~/export_options.plist --flavor $FLAVOR --dart-define-from-file $DART_DEFINE_FILE -t $TARGET --split-debug-info=symbols
    - &check_mock_data
      name: Check mock data is compiled out
      script: scripts/check_mock_data.sh
    - &build_android
      name: Build Android
      script: |
        set -e
        set -x
        flutter build appbundle --release --flavor $FLAVOR --dart-define-from-file $DART_DEFINE_FILE -t $TARGET --split-debug-info=symbols
    - &upload_debug_symbols
      name: Upload debug symbols
      script: |
        yq -i '.name = strenv(BUNDLE_IDENTIFIER)' pubspec.yaml
        flutter pub get
        flutter packages pub run sentry_dart_plugin
    - &install_patrol
      name: Install patrol and its dependencies
      script: |
        dart pub global activate patrol_cli
        patrol doctor
    - &start_android_emulator
      name: Start Android emulator
      script: |
        cd $ANDROID_HOME/tools
        emulator -avd emulator &
        adb wait-for-device
    - &patrol_integration_tests
      name: Integration tests using patrol
      script: |
        patrol test -t integration_test/basic_order_test.dart --flavor testFlavor --verbose
        test_report: build/app/outputs/androidTest-results/connected/*.xml

workflows:
  example-integration-test:
    name: Example Integration Test
    <<: *instance_linux
    triggering: *test_triggering
    environment:
      <<: *env_settings
      vars:
        TARGET: lib/main_test.dart
        FLAVOR: exampletest
        DART_DEFINE_FILE: env-example-test.json
        BUNDLE_IDENTIFIER: com.example.example.ios.dev
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.example.example.ios.dev
      android_signing:
        - example_test
    cache: *cache_paths
    scripts:
      # - *set_up_ios_code_signing
      - *install_dependencies
      - *generate_localizations
      # - *analyze_and_test
      # - *set_app_version
      - *generate_test_release_notes
      # - *build_ios
      - *build_android
      - *upload_debug_symbols
      - *install_patrol
      - *start_android_emulator
      - *patrol_integration_tests
    artifacts: *flutter_artifacts
    publishing:
      <<: *publish_notifications
      google_play: *google_play
      app_store_connect:
        <<: *app_store_connect_credentials
        submit_to_testflight: true
        submit_to_app_store: false
        beta_groups:
          - External
```

Configuration not related to this issue was removed from the codeblock above

Here are the contents of android/app/build.gradle file:

```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

def dartDefines = [:];
if (project.hasProperty('dart-defines')) {
    // Decode dart-defines, which are comma-separated and encoded in Base64, and store them in a variable.
    dartDefines = dartDefines + project.property('dart-defines')
            .split(',')
            .collectEntries { entry ->
                def pair = new String(entry.decodeBase64(), 'UTF-8').split('=', 2)
                [(pair.first()): pair.last()]
            }
}

android {
    ndkVersion "25.1.8937393"

    signingConfigs {
       release {
           if (System.getenv()['CI']) { // Used when building on CI
               storeFile file(System.getenv()['CI_KEYSTORE_PATH'])
               storePassword System.getenv()['CI_KEYSTORE_PASSWORD']
               keyAlias System.getenv()['CI_KEY_ALIAS']
               keyPassword System.getenv()['CI_KEY_PASSWORD']
           } else {
               keyAlias keystoreProperties['keyAlias']
               keyPassword keystoreProperties['keyPassword']
               storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
               storePassword keystoreProperties['storePassword']
           }
       }
    }

    flavorDimensions "flavor-type"

    productFlavors {
        exampleFlavor1 {
            dimension "flavor-type"
        }
        exampleFlavor2 {
            dimension "flavor-type"
        }
        exampleFlavor3 {
            dimension "flavor-type"
        }
        exampleFlavor4 {
            dimension "flavor-type"
        }
        exampleFlavor5 {
            dimension "flavor-type"
        }
        exampleFlavor6 {
            dimension "flavor-type"
        }
        exampleFlavor7 {
            dimension "flavor-type"
        }
        exampleFlavor8 {
            dimension "flavor-type"
        }
        exampleFlavor9 {
            dimension "flavor-type"
        }
        exampleFlavor10 {
            dimension "flavor-type"
        }
    }

    compileSdkVersion 34

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        applicationId dartDefines.ANDROID_APPLICATION_ID
        resValue "color", "ic_launcher_background", dartDefines.ANDROID_LAUNCHER_BACKGROUND
        resValue "string", "app_name", dartDefines.APP_NAME
        resValue "string", "ANDROID_ASSET_LINK_STATEMENT", dartDefines.ANDROID_ASSET_LINK_STATEMENT
        resValue "string", "FB_APP_ID", dartDefines.FB_APP_ID
        resValue "string", "FB_CLIENT_TOKEN", dartDefines.FB_CLIENT_TOKEN
        minSdkVersion 24
        targetSdkVersion flutter.targetSdkVersion
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "pl.leancode.patrol.PatrolJUnitRunner"
        testInstrumentationRunnerArguments clearPackageData: "true"
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            multiDexEnabled true
            signingConfig signingConfigs.release
        }

        debug {
            minifyEnabled false
            shrinkResources false
            multiDexEnabled false
        }
    }

    testOptions {
        execution "ANDROIDX_TEST_ORCHESTRATOR"
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    androidTestUtil "androidx.test:orchestrator:1.4.2"
}

apply plugin: 'com.google.gms.google-services'
```
### Expected results

`flutter analyze` should successfully analyze the contents of its files and return 0, like it does on Mac instances

### Actual results

The Android build seems to be completely fine yet, the `flutter analyze` throws thousands of lines of errors, around 19 thousands to be exact, like the ones below:
```
...
error • Undefined name 'statusBarDarkIcons' • lib/apps/example/example_theme.dart:100:27 • undefined_identifier
error • The function 'ListTileButtonTheme' isn't defined • lib/apps/example/example_theme.dart:137:26 • undefined_function
error • The function 'lToggleTheme' isn't defined • lib/apps/example/example_theme.dart:235:20 • undefined_function
error • The function 'ToggleTheme' isn't defined • lib/apps/example/example_theme.dart:241:23 • undefined_function
error • The function 'LocationButtonTheme' isn't defined • lib/apps/example/example_theme.dart:309:26 • undefined_function
error • The function 'TextFieldTheme' isn't defined • lib/apps/example/example_theme.dart:329:21 • undefined_function
error • Undefined name 'MenuToolbarStyle' • lib/apps/example/example_theme.dart:340:23 • undefined_identifier
error • Undefined name 'SvgAsset' • lib/apps/example/example_theme.dart:342:9 • undefined_identifier
error • The function 'CouponCardTheme' isn't defined • lib/apps/example/example_theme.dart:346:22 • undefined_function
error • The function 'ToggleButtonTheme' isn't defined • lib/apps/example/example_theme.dart:359:24 • undefined_function
error • The function 'GiftCardTheme' isn't defined • lib/apps/example/example_theme.dart:372:20 • undefined_function
error • The function 'GiftCardItemTheme' isn't defined • lib/apps/example/example_theme.dart:373:18 • undefined_function
error • The function 'GiftCardDetailsTheme' isn't defined • lib/apps/example/example_theme.dart:387:21 • undefined_function
error • The function 'GiftCardTransactionListTheme' isn't defined • lib/apps/example/example_theme.dart:424:29 • undefined_function
error • The function 'GiftCardCheckoutItemTheme' isn't defined • lib/apps/example/example_theme.dart:445:26 • undefined_function
...
```
It seems like it cannot see any of its local files anywhere, files from its own package

`flutter analyze` logs can be found in the **Debugging Scripts** step. The error is thrown at a different, later step, but the problems are related, essentially the same

### Build id (optional)

6655aeb658e2595d08002fa6
