### DISCUSSION TITLE
Flutter Android Email Not Publishing

### DISCUSSION THREAD

**Discussion by bbeckley** [codemagic-ci-cd/codemagic-docs#2580] [Q&A] [answered]
### If you are looking for help, please confirm the following...

- [X] I confirm I have searched the [Docs](https://docs.codemagic.io), [Codemagic Sample Projects](https://github.com/codemagic-ci-cd/codemagic-sample-projects), and GitHub [Discussions](https://github.com/orgs/codemagic-ci-cd/discussions).
- [X] I confirm the software versions on my local computer match the ones in CI environment (e.g. Xcode version, Gradle version). See [here](https://docs.codemagic.io/troubleshooting/common-android-issues/#builds-work-locally-but-fail-on-codemagic)
- [X] I confirm I am able to do a fresh clone of the repository and build the project on my local computer.

### Which mobile framework are you using?

Flutter (Dart)

### Steps to reproduce

When my android build is successful there is not email sent, but if the build fails we get an email.  For my iOS workflow I get an email sent when successful.  My yaml publishing section between both workflows are identical.  I don't believe gmail is blocking or sending to spam and I have check and the failure and iOS build email sends correctly.

```
workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/.gradle/caches
        - $CM_BUILD_DIR/node_modules
    environment:
      groups:
        - browserstack_credentials
        - build_environment
      android_signing:
        - my_keystore_reference
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
            - name: Flutter analyze
              script: |
                flutter analyze
      - name: Flutter unit tests
        script: |
          flutter test
        ignore_failure: true
      - name: Build AAB with Flutter
        script: |
          BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks="$GOOGLE_PLAY_TRACK") + 1))
          echo "My build is $BUILD_ENV_JSON > Build for version > $BUILD_NUMBER"
          flutter build apk --release \
            --build-name=1.0.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER \
            --dart-define-from-file=.env/$BUILD_ENV_JSON
      - name: BrowserStack upload
        script: |
          curl -u "$BROWSERSTACK_USERNAME:$BROWSERSTACK_ACCESS_TOKEN" \
            -X POST "https://api-cloud.browserstack.com/app-live/upload" \
            -F "file=@build/app/outputs/flutter-apk/app-release.apk"
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - someemailaddress@gmail.com
```

iOS yaml that is working

```
 ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/Library/Caches/CocoaPods
        - $CM_BUILD_DIR/node_modules
    environment:
      ios_signing:
        distribution_type: ad_hoc
        bundle_identifier: com.my.org
      groups:
        - browserstack_credentials
        - build_environment
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        APP_STORE_ID: 1234
      flutter: stable
      xcode: 15.3
      cocoapods: 1.15.2
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages pub get
        ignore_failure: true
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter unit tests
        script: |
          flutter test
        ignore_failure: true
      - name: Flutter build ipa and automatic versioning
        script: |
          flutter build ipa --release \
          --build-name=1.0.0 \
          --build-number=$(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_ID") + 1)) \
          --dart-define-from-file=.env/$BUILD_ENV_JSON \
          --export-options-plist=/Users/builder/export_options.plist
      - name: Uploading to BrowserStack App Live environment
        script: |
          curl -u "$BROWSERSTACK_USERNAME:$BROWSERSTACK_ACCESS_TOKEN" \
            -X POST "https://api-cloud.browserstack.com/app-live/upload" \
            -F "file=@build/ios/ipa/myapp_v2.ipa"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
    publishing:
      email:
        recipients:
          - someemailaddress@gmail.com
```

### Expected results

Email for Android build sent when successful or failure

### Actual results

No email sent on successful Android build

### Build id (optional)

665f0fe240e0c287c9b2f596

**Comment by himesh-cm** [comment, marked as answer]
Hey @bbeckley 
Please modify the script as below

```
publishing:
  email:
    recipients:
      - name@example.com
    notify:
      success: false # To not receive a notification when a build succeeds
      failure: false # To not receive a notification when a build fails
```

**Reply by bbeckley** [reply]
I will give that a try, but I believe I did try that once before.  But for iOS the emails are sending without any notify config.  But since I want the emails to send all the time with a success or failure I'd want the values to be true, correct ?

```
publishing:
  email:
    recipients:
      - name@example.com
    notify:
      success: true # notification when a build succeeds
      failure: true #  notification when a build fails
```
