### DISCUSSION TITLE
codemagic.yaml environment/vars variables cannot be dereferenced

### DISCUSSION THREAD

**Discussion by q962** [codemagic-ci-cd/codemagic-docs#2582] [Q&A]
### If you are looking for help, please confirm the following...

- [X] I confirm I have searched the [Docs](https://docs.codemagic.io), [Codemagic Sample Projects](https://github.com/codemagic-ci-cd/codemagic-sample-projects), and GitHub [Discussions](https://github.com/orgs/codemagic-ci-cd/discussions).
- [X] I confirm the software versions on my local computer match the ones in CI environment (e.g. Xcode version, Gradle version). See [here](https://docs.codemagic.io/troubleshooting/common-android-issues/#builds-work-locally-but-fail-on-codemagic)
- [X] I confirm I am able to do a fresh clone of the repository and build the project on my local computer.

### Which mobile framework are you using?

Other - please mention in your question

### Steps to reproduce

[The following used to work](https://blog.codemagic.io/godot-games-cicd/), but is no longer valid
```
        environment:
            groups:
                - godot
            vars:
                GODOT_VERSION: 4.2.2
                GODOT_EXEC_URL: https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}-stable/Godot_v${GODOT_VERSION}-stable_macos.universal.zip
                GODOT_TEMPLATES_URL: https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}-stable/Godot_v${GODOT_VERSION}-stable_export_templates.tpz
```

```
builder@builders-Virtual-Machine clone % echo $GODOT_EXEC_URL
https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}-stable/Godot_v${GODOT_VERSION}-stable_macos.universal.zip

```

The remedy also didn't work, here is my script:
```
        scripts:
            - name: set env
              script: |
                GODOT_VERSION=4.2.2;
                echo "GODOT_VERSION=4.2.2" >> $CM_ENV;
                echo "GODOT_EXEC_URL=https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}-stable/Godot_v${GODOT_VERSION}-stable_macos.universal.zip" >> $CM_ENV;
                echo "GODOT_TEMPLATES_URL=https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}-stable/Godot_v${GODOT_VERSION}-stable_export_templates.tpz" >> $CM_ENV;

```
https://docs.codemagic.io/yaml-basic-configuration/using-environment-variables/

### Expected results

-

### Actual results

Are variables no longer allowed in 'environment/vars'?

What's wrong with my usage of CM_ENV?

### Build id (optional)

666054f3ccaa04aa605ecbb4      66605a1584e8ce0b378a0464
