### DISCUSSION TITLE
Build not getting triggered with correct configuration

### DISCUSSION THREAD

**Discussion by JakeHadley** [codemagic-ci-cd/codemagic-docs#2627] [Q&A] [answered]
### If you are looking for help, please confirm the following...

- [X] I confirm I have searched the [Docs](https://docs.codemagic.io), [Codemagic Sample Projects](https://github.com/codemagic-ci-cd/codemagic-sample-projects), and GitHub [Discussions](https://github.com/orgs/codemagic-ci-cd/discussions).
- [X] I confirm the software versions on my local computer match the ones in CI environment (e.g. Xcode version, Gradle version). See [here](https://docs.codemagic.io/troubleshooting/common-android-issues/#builds-work-locally-but-fail-on-codemagic)
- [X] I confirm I am able to do a fresh clone of the repository and build the project on my local computer.

### Which mobile framework are you using?

Flutter (Dart)

### Steps to reproduce

1. Create a PR from `feature` branch into `main` branch
2. have a codemagic.yaml file with the following triggering config:
```
  ios-workflow:
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: main
          include: true
          source: true
      cancel_previous_builds: true
```
3. complete the pr, merging any changes from `feature` into `main`

### Expected results

Codemagic should trigger a build for the main branch

### Actual results

No builds are getting triggered, I have to trigger it manually
