### DISCUSSION TITLE
Cannot setup Flutter with melos and FVM

### DISCUSSION THREAD

**Discussion by alberto-sf** [codemagic-ci-cd/codemagic-docs#2634] [Q&A] [answered]
### If you are looking for help, please confirm the following...

- [X] I confirm I have searched the [Docs](https://docs.codemagic.io), [Codemagic Sample Projects](https://github.com/codemagic-ci-cd/codemagic-sample-projects), and GitHub [Discussions](https://github.com/orgs/codemagic-ci-cd/discussions).
- [X] I confirm the software versions on my local computer match the ones in CI environment (e.g. Xcode version, Gradle version). See [here](https://docs.codemagic.io/troubleshooting/common-android-issues/#builds-work-locally-but-fail-on-codemagic)
- [X] I confirm I am able to do a fresh clone of the repository and build the project on my local computer.

### Which mobile framework are you using?

Flutter (Dart)

### Steps to reproduce

1 . Use `flutter: fvm`
2. Configure melos and set `sdkPath: .fvm/flutter_sdk` to use FVM
3. Follow the [documentation](https://docs.codemagic.io/yaml-quick-start/building-a-flutter-app/#setting-the-flutter-version) and set `ln -s $FLUTTER_ROOT $CM_BUILD_DIR/.fvm/flutter_sdk`

We have configured the step as recommended:

```yaml
- &install_melos
  name: Install Melos
    script: |
      ln -s $FLUTTER_ROOT $CM_BUILD_DIR/.fvm/flutter_sdk
      dart pub global activate melos
      melos bootstrap
```

### Expected results

The`dart pub global activate melos` and following commands execute successfully 

### Actual results

melos.yaml: SDK path is not valid. Could not find dart tool at /Users/builder/clone/.fvm/flutter_sdk/bin/dart

Build failed :|
Step 3 script `Install Melos` exited with status code 1

### Build id (optional)

669642b0612f74af82a0590e
