### DISCUSSION TITLE
Shorebird release build for ios fails

### DISCUSSION THREAD

**Discussion by AnaNedicGithub** [codemagic-ci-cd/codemagic-docs#2665] [Q&A] [answered]
### If you are looking for help, please confirm the following...

- [X] I confirm I have searched the [Docs](https://docs.codemagic.io), [Codemagic Sample Projects](https://github.com/codemagic-ci-cd/codemagic-sample-projects), and GitHub [Discussions](https://github.com/orgs/codemagic-ci-cd/discussions).
- [X] I confirm the software versions on my local computer match the ones in CI environment (e.g. Xcode version, Gradle version). See [here](https://docs.codemagic.io/troubleshooting/common-android-issues/#builds-work-locally-but-fail-on-codemagic)
- [X] I confirm I am able to do a fresh clone of the repository and build the project on my local computer.

### Which mobile framework are you using?

Flutter (Dart)

### Steps to reproduce

If I run `shorebird release ios` from my console, I can get an .ipa file and upload it successfully to TestFlight using Xcode.

However, If I run run Release iOS Workflow from my project via codemagic, it fails.

If needed, I can provide any file from my project. Thank you!

### Codemagic.yaml

```
definitions:
# Reusable definitions go in this section
scripts:
  - &shorebird_install
    name: Install Shorebird CLI
    script: |
      # Install the Shorebird CLI
      curl --proto '=https' --tlsv1.2 https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh -sSf | bash
      # Set Shorebird PATH
      echo PATH="/Users/builder/.shorebird/bin:$PATH" >> $CM_ENV
  # - &flutter_analyze
  #   name: Run static code analysis
  #   script: flutter analyze
  - &setup_local_properties
    name: Set up local.properties
    script: echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"


workflows:
  # Define your workflows here
  release-android-workflow:
... # android workflow is ok

  release-ios-workflow:
    name: Release iOS Workflow
    integrations:
      app_store_connect: CodemagicCICDAPIKey
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.semdatex.more-app
      groups:
        - shorebird_credentials
      vars:
        APP_STORE_APPLE_ID: 6596759542
      flutter: 3.22.3  #same as locally
      xcode: 15.3
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter unit tests
        script: |
          flutter test
        ignore_failure: true
      - *shorebird_install
      - name: BuildWithShorebird
        script: |
          shorebird release ios --verbose -- \
            --build-name=1.0.0 \
            --build-number=$(($(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID") + 1)) \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - example@gmail.com
        notify:
          success: true
          failure: false
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
```
### Expected results

App uploaded to TestFlight

### Actual results

`: Writing 99941 characters to text file /Users/builder/.pub-cache/log/pub_log.txt.
[   +2 ms] Encountered error while archiving for device.
[        ] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _BuildIOSSubCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:691:7)
           <asynchronous suspension>
           #2      BuildIOSArchiveCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:426:50)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1394:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:372:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:308:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:130:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:93:3)
           <asynchronous suspension>

 (126.8s)
[Process.run] git symbolic-ref HEAD (in /Users/builder/.shorebird/bin/cache)
Exited with code 0

stdout:
refs/heads/stable

[Process.run] git rev-parse --verify HEAD (in /Users/builder/.shorebird/bin/cache)
Exited with code 0

stdout:
d0a36bc6eff29623f1101746cb0c43ab246d0c21

[Process.run] git remote prune origin (in /Users/builder/.shorebird/bin/cache)
Exited with code 0
[Process.run] git fetch --tags (in /Users/builder/.shorebird/bin/cache)
Exited with code 0
[Process.run] git rev-parse --verify @{upstream} (in /Users/builder/.shorebird/bin/cache)
Exited with code 0

stdout:
d0a36bc6eff29623f1101746cb0c43ab246d0c21

Build failed :|
**Step 8 script `BuildWithShorebird` exited with status code 70`**

### Build id (optional)
**66afbf0c93766dfdccfaa3ee**
