### DISCUSSION TITLE
Run Detox tests using codemagic

### DISCUSSION THREAD

**Discussion by Bebrevski** [codemagic-ci-cd/codemagic-docs#2667] [Q&A] [answered]
### If you are looking for help, please confirm the following...

- [X] I confirm I have searched the [Docs](https://docs.codemagic.io), [Codemagic Sample Projects](https://github.com/codemagic-ci-cd/codemagic-sample-projects), and GitHub [Discussions](https://github.com/orgs/codemagic-ci-cd/discussions).
- [X] I confirm the software versions on my local computer match the ones in CI environment (e.g. Xcode version, Gradle version). See [here](https://docs.codemagic.io/troubleshooting/common-android-issues/#builds-work-locally-but-fail-on-codemagic)
- [X] I confirm I am able to do a fresh clone of the repository and build the project on my local computer.

### Which mobile framework are you using?

React Native

### Steps to reproduce

Hey guys. I have some difficulties running detox test on the hosted machine. I red these docs
[How to run RN Detox tests on Codemagic](https://blog.codemagic.io/react-native-detox-tests-on-codemagic/)

After applying all the steps mentioned i get error 

```
● Test suite failed to run

    DetoxRuntimeError: Cannot boot Android Emulator with the name: 'Pixel_API_33'

    HINT: Make sure you choose one of the available emulators:

      at AVDValidator._assertAVDMatch (node_modules/detox/src/devices/allocation/drivers/android/emulator/AVDValidator.js:36:13)
      at AVDValidator.validate (node_modules/detox/src/devices/allocation/drivers/android/emulator/AVDValidator.js:18:16)
      at async EmulatorAllocDriver.allocate (node_modules/detox/src/devices/allocation/drivers/android/emulator/EmulatorAllocDriver.js:59:5)
      at async /Users/builder/clone/node_modules/detox/src/devices/allocation/DeviceAllocator.js:44:22
```
After that I thought that I am not using the proper avdName and started to search what are the provided names of the emulators. And for my surprise there are none

![image](https://github.com/user-attachments/assets/3887fc4d-9fd8-4429-b918-1f561c6ebb2c)

I have searched for any info that can resolve my issue, tried numerous options to find and start any emulator, but with no success.
Can someone help?

### codemagic.yaml
```
workflows:
  react-native-android:
    name: React Native Android
    environment:
      android_signing:
        - Signing_Cert
      java: 17
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Install detox dependencies
        script: brew tap wix/brew
      - name: Install detox-cli
        script: |
          npm install -g detox-cli
          cd $CM_BUILD_DIR && npm install detox --save-dev
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Gradlew - Grant permissions
        script: cd android && chmod +x gradlew && cd ..
      - name: List available devices
        script: |
          echo "Listing available Android devices..."
          adb devices
      - name: Build with Detox
        script: npm run build:e2e:codemagic
      - name: Test with Detox
        script: npm run test:e2e:codemagic
      - name: Build Android release
        script: |
          cd android
          ./gradlew assembleRelease
          ./gradlew bundleRelease
    artifacts:
      - android/app/build/outputs/**/*.aab
      - android/app/build/outputs/**/*.apk
```

### package.json
```
{
  "name": "fleet-platform-mobile",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "debugger": "npx react-native start --experimental-debugger",
    "lint": "eslint .",
    "test:e2e": "detox test -c android.emu.debug --coverage",
    "build:e2e:codemagic": "detox build -c android.emu.test",
    "test:e2e:codemagic": "detox test -c android.emu.test --headless",
    "test": "jest"
  },
  "dependencies": {
    "@gorhom/bottom-sheet": "^4.6.3",
    "@notifee/react-native": "^7.8.2",
    "@react-native-async-storage/async-storage": "^1.22.3",
    "@react-native-community/geolocation": "^3.2.1",
    "@react-native-community/slider": "^4.5.2",
    "@react-native-firebase/app": "^20.3.0",
    "@react-native-firebase/messaging": "^20.3.0",
    "@react-navigation/bottom-tabs": "^6.5.2",
    "@react-navigation/native": "^6.1.17",
    "@react-navigation/native-stack": "^6.9.26",
    "@reduxjs/toolkit": "^2.0.1",
    "@shopify/react-native-skia": "^1.1.0",
    "@wuba/react-native-echarts": "^1.3.0",
    "axios": "^1.6.2",
    "dayjs": "^1.11.10",
    "echarts": "^5.5.0",
    "i18next": "^23.7.6",
    "lodash": "^4.17.21",
    "react": "18.2.0",
    "react-i18next": "^13.4.1",
    "react-native": "0.74.2",
    "react-native-calendars": "^1.1304.0",
    "react-native-date-picker": "^4.3.7",
    "react-native-device-info": "^10.12.0",
    "react-native-dotenv": "^3.4.11",
    "react-native-geocoding": "^0.5.0",
    "react-native-gesture-handler": "^2.16.2",
    "react-native-google-places-autocomplete": "^2.5.6",
    "react-native-keychain": "^8.2.0",
    "react-native-linear-gradient": "^2.8.3",
    "react-native-map-clustering": "^3.4.2",
    "react-native-maps": "^1.8.4",
    "react-native-mask-text": "^0.14.2",
    "react-native-paper": "^5.12.3",
    "react-native-push-notification-popup": "^1.7.0",
    "react-native-reanimated": "^3.11.0",
    "react-native-safe-area-context": "^4.10.1",
    "react-native-screens": "^3.29.0",
    "react-native-svg": "^14.1.0",
    "react-native-svg-transformer": "^1.2.0",
    "react-native-vector-icons": "^10.0.3",
    "react-redux": "^9.0.4",
    "socket.io-client": "^4.7.3"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native/babel-preset": "0.74.84",
    "@react-native/eslint-config": "0.74.84",
    "@react-native/metro-config": "0.74.84",
    "@react-native/typescript-config": "0.74.84",
    "@types/jest": "^29.5.12",
    "@types/lodash": "^4.14.202",
    "@types/node": "^20.14.10",
    "@types/react": "^18.2.6",
    "@types/react-native": "^0.73.0",
    "@types/react-native-dotenv": "^0.2.2",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.6.3",
    "babel-plugin-optional-require": "^0.3.1",
    "detox": "^20.23.0",
    "eslint": "^8.19.0",
    "eslint-plugin-import": "^2.29.1",
    "eslint-plugin-react-hooks": "^4.6.0",
    "jest": "^29.7.0",
    "prettier": "2.8.8",
    "react-test-renderer": "18.2.0",
    "ts-jest": "^29.1.5",
    "typescript": "5.0.4"
  },
  "engines": {
    "node": ">=18"
  },
  "eslintConfig": {
    "extends": "react-app"
  }
}
```

### detoxrc.js
```
apps: {
    'ios.debug': {
      type: 'ios.app',
      binaryPath:
        'ios/build/Build/Products/Debug-iphonesimulator/FleetPlatformMobile.app',
      build:
        'xcodebuild -workspace ios/MobileAppName.xcworkspace -scheme MobileAppName-configuration Debug -sdk iphonesimulator -derivedDataPath ios/build',
    },
    'ios.release': {
      type: 'ios.app',
      binaryPath:
        'ios/build/Build/Products/Release-iphonesimulator/MobileAppName.app',
      build:
        'xcodebuild -workspace ios/MobileAppName.xcworkspace -scheme MobileAppName-configuration Release -sdk iphonesimulator -derivedDataPath ios/build',
    },
    'android.debug': {
      type: 'android.apk',
      binaryPath: 'android/app/build/outputs/apk/debug/app-debug.apk',
      build:
        'cd android && ./gradlew assembleDebug assembleAndroidTest -DtestBuildType=debug',
      reversePorts: [8081],
    },
    'android.release': {
      type: 'android.apk',
      binaryPath: 'android/app/build/outputs/apk/release/app-release.apk',
      build:
        'cd android && ./gradlew assembleRelease assembleAndroidTest -DtestBuildType=release',
    },
    'android.test': {
      type: 'android.apk',
      binaryPath: 'android/app/build/outputs/apk/debug/app-debug.apk',
      build:
        'cd android && ./gradlew assembleRelease assembleAndroidTest -DtestBuildType=debug && cd ..',
    },
  },
  devices: {
    simulator: {
      type: 'ios.simulator',
      device: {
        type: 'iPhone 15',
      },
    },
    attached: {
      type: 'android.attached',
      device: {
        adbName: '.*',
      },
    },
    emulator: {
      type: 'android.emulator',
      device: {
        avdName: 'Pixel_8_Pro_API_34',
      },
    },
    test: {
      type: 'android.emulator',
      device: {
        avdName: 'After i find emulators list i will pick one and set its name here',
      },
    },
  },
  configurations: {
    'ios.sim.debug': {
      device: 'simulator',
      app: 'ios.debug',
    },
    'ios.sim.release': {
      device: 'simulator',
      app: 'ios.release',
    },
    'android.att.debug': {
      device: 'attached',
      app: 'android.debug',
    },
    'android.att.release': {
      device: 'attached',
      app: 'android.release',
    },
    'android.emu.debug': {
      device: 'emulator',
      app: 'android.debug',
    },
    'android.emu.release': {
      device: 'emulator',
      app: 'android.release',
    },
    'android.emu.test': {
      device: 'test',
      app: 'android.test',
    },
  },
```

### Expected results

I am expecting to build test apk, launch emulator and execute e2e tests with Detox

### Actual results

Error after tests start due to missing emulator

### Build id (optional)

66b1dd30e6e549d5839e942b
