### DISCUSSION TITLE
Webhook payload. Is accessible for scripts?

### DISCUSSION THREAD

**Discussion by bahag-chandrana** [codemagic-ci-cd/codemagic-docs#2681] [Q&A] [answered]
### If you are looking for help, please confirm the following...

- [X] I confirm I have searched the [Docs](https://docs.codemagic.io), [Codemagic Sample Projects](https://github.com/codemagic-ci-cd/codemagic-sample-projects), and GitHub [Discussions](https://github.com/orgs/codemagic-ci-cd/discussions).
- [X] I confirm the software versions on my local computer match the ones in CI environment (e.g. Xcode version, Gradle version). See [here](https://docs.codemagic.io/troubleshooting/common-android-issues/#builds-work-locally-but-fail-on-codemagic)
- [X] I confirm I am able to do a fresh clone of the repository and build the project on my local computer.

### Which mobile framework are you using?

Flutter (Dart)

### Steps to reproduce

I am trying to utilize the Pull title from the `event` payload which is the trigger for our workflow. This works well in the `when` condition section as described in the documentation.  For e.g. following works.

```yaml
    when:
      condition: (not event.pull_request.draft) or (event.pull_request.labels[0].name == "run-codemagic")
```

However when I try to access the same payload in one of the scripts its not working. For e.g. as shown below.

```yaml
      - name: Set up release notes
        script: |
          echo $(event.pull_request.title) | jq '.' > $FCI_BUILD_DIR/release_notes.json
          cat $FCI_BUILD_DIR/release_notes.json
```

Is there a specific way to access this webhoook payload within the scripts.

### Expected results

the PR title is accessible in the command line.

### Actual results

Its not clear how to access it in the scripts section.
