### DISCUSSION TITLE
Codemagic Submits to TestFlight even though submit_to_testflight and submit_to_app_store is false.

### DISCUSSION THREAD

**Discussion by superakabo** [codemagic-ci-cd/codemagic-docs#2692] [Q&A] [answered]
### If you are looking for help, please confirm the following...

- [X] I confirm I have searched the [Docs](https://docs.codemagic.io), [Codemagic Sample Projects](https://github.com/codemagic-ci-cd/codemagic-sample-projects), and GitHub [Discussions](https://github.com/orgs/codemagic-ci-cd/discussions).
- [X] I confirm the software versions on my local computer match the ones in CI environment (e.g. Xcode version, Gradle version). See [here](https://docs.codemagic.io/troubleshooting/common-android-issues/#builds-work-locally-but-fail-on-codemagic)
- [X] I confirm I am able to do a fresh clone of the repository and build the project on my local computer.

### Which mobile framework are you using?

Flutter (Dart)

### Steps to reproduce

setting submit_to_testflight to false and submit_to_app_store to false still submits binary to TestFlight.
```yaml
publishing:
  app_store_connect:
    api_key: $APP_STORE_CONNECT_PRIVATE_KEY
    key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
    issuer_id: $APP_STORE_CONNECT_ISSUER_ID
    submit_to_testflight: false
    submit_to_app_store: false
```

### Expected results

The binary (.ipa) is submitted to TestFlight.

### Actual results

The binary (.ipa) should not be submitted to TestFlight.

### Build id (optional)

66c9cbcec8bb145f1b60192a
