### DISCUSSION TITLE
Trigger build with when.changeset in mono repo

### DISCUSSION THREAD

**Discussion by thangmoxielabs** [codemagic-ci-cd/codemagic-docs#2710] [Q&A] [answered]
### If you are looking for help, please confirm the following...

- [X] I confirm I have searched the [Docs](https://docs.codemagic.io), [Codemagic Sample Projects](https://github.com/codemagic-ci-cd/codemagic-sample-projects), and GitHub [Discussions](https://github.com/orgs/codemagic-ci-cd/discussions).
- [X] I confirm the software versions on my local computer match the ones in CI environment (e.g. Xcode version, Gradle version). See [here](https://docs.codemagic.io/troubleshooting/common-android-issues/#builds-work-locally-but-fail-on-codemagic)
- [X] I confirm I am able to do a fresh clone of the repository and build the project on my local computer.

### Which mobile framework are you using?

Flutter (Dart)

### Steps to reproduce

I have the following project structure
app/
- mobile_app/
- kiosk_app/
- core/

Here is the codemagic.yaml sample file:
```
workflows:
  mobile-workflow:
    name: Mobile App workflow
    working_directory: mobile_app
    triggering:
      events:
        - push
    when:
      changeset:
        includes:
          - 'mobile_app'
  kiosk-workflow:
    name: Kiosk App workflow
    working_directory: kiosk_app
    triggering:
      events:
        - push
    when:
      changeset:
        includes:
          - 'kiosk_app'
```

### Expected results

When I make a push that contains only changes in the mobile_app, it will trigger both workflow

### Actual results

When I make a push that contains only changes in the mobile_app, I should trigger only the mobile-workflow only, and same with the kiosk_app
