### DISCUSSION TITLE
White labeling

### DISCUSSION THREAD

**Discussion by zs-dima** [codemagic-ci-cd/codemagic-docs#2752] [Q&A] [answered]
### If you are looking for help, please confirm the following...

- [X] I confirm I have searched the [Docs](https://docs.codemagic.io), [Codemagic Sample Projects](https://github.com/codemagic-ci-cd/codemagic-sample-projects), and GitHub [Discussions](https://github.com/orgs/codemagic-ci-cd/discussions).
- [X] I confirm the software versions on my local computer match the ones in CI environment (e.g. Xcode version, Gradle version). See [here](https://docs.codemagic.io/troubleshooting/common-android-issues/#builds-work-locally-but-fail-on-codemagic)
- [X] I confirm I am able to do a fresh clone of the repository and build the project on my local computer.

### Which mobile framework are you using?

Flutter (Dart)

### Steps to reproduce

1. Create provisioning profiles for each brand and device type: 
brand1_provisioning_profile:      iOS Brand1 com.company1.bundle; 
brand2_provisioning_profile:      iOS Brand2 com.company2.bundle; 
brand1_tv_provisioning_profile: tvOS Brand1 com.company1.bundle; 
brand2_tv_provisioning_profile: tvOS Brand2 com.company2.bundle; 

2. Reference provisioning profiles in the codemagic.yaml workflow:
        provisioning_profiles:
          - profile: brand1_tv_provisioning_profile_ref
          - profile: brand2_tv_provisioning_profile_ref
          - profile: brand1_provisioning_profile_ref
          - profile: brand2_provisioning_profile_ref

3. Update bundle ID according to $BUNDLE_ID environment variable, and check the result using grep:
script: |
  PBXPROJ=$CM_BUILD_DIR/ios/Runner.xcodeproj/project.pbxproj
  sed -i '' "s/$BASE_BUNDLE_ID/$BUNDLE_ID/g" $PBXPROJ
  grep "PRODUCT_BUNDLE_IDENTIFIER" $PBXPROJ

4. Run build for Brand2 iOS

5. Failed to build iOS app
Error (Xcode): Provisioning profile "fomo_app_tv_provisioning_profile" has platform "tvOS", which does not match the current platform "iOS".
/Users/builder/clone/ios/Runner.xcodeproj

### Expected results

Codemagic has to select the provisioning profile using bundle ID AND Device Type. (not only by bundle ID)
so brand1_provisioning_profile_ref has to be selected for the case above instead of brand1_tv_provisioning_profile_ref.

### Actual results

Failed to build iOS app
Error (Xcode): Provisioning profile "brand2_tv_provisioning_profile_ref" has platform "tvOS", which does not match the current platform "iOS".
/Users/builder/clone/ios/Runner.xcodeproj

**Comment by dtrdic** [comment]
hello @zs-dima Instead of manually creating and referencing provisioning profiles in Codemagic, you can allow Codemagic to automatically handle fetching and applying the correct provisioning profiles for your app.

The key command responsible for this is:
`app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create`
This command fetches the provisioning profile and certificate for the specified BUNDLE_ID from App Store Connect. It ensures that the provisioning profile for the iOS App Store distribution is used. By adding the --create flag, it will automatically create a provisioning profile if one does not already exist.

Since you are whitelabeling let me share [this guide](https://docs.codemagic.io/yaml-quick-start/white-label-getting-started/) with you, which will help you on setting up all the required steps for whitelabeling your apps.
Also please share a build id in the future so we can check your configuration and suggest you accordingly

**Comment by zs-dima** [comment]
@dtrdic thanks a lot for the answer
Sure I saw guides and documentation.

If I do not provide provisioning profiles it is error message:
```
1 validation error in codemagic.yaml:
ios-workflow -> environment -> ios_signing ->
  Either distribution profile and bundle identifier or provisioning profiles (and optionally certificates) must be provided.
```

If I provide only one provisioning profile it is error:
```
No development certificates available to code sign app for device deployment
```

I prefer to use integrations instead of manual keychain management as in your example:
 
```yaml
    integrations:
      app_store_connect: app_appstore_api_key
    environment:
      ios_signing:
        certificates:
          - app_apple_signing_certificate
    scripts:
      - *call_scripts
      - name: Set up code signing
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          xcode-project use-profiles          
```

**Reply by dtrdic** [reply, marked as answer]
@zs-dima you won't be able to use the App Store Connect integration in this case. You'll need to take a different approach by manually defining the App Store Connect API key information (e.g., **APP_STORE_CONNECT_KEY_IDENTIFIER**, **APP_STORE_CONNECT_ISSUER_ID**, **APP_STORE_CONNECT_PRIVATE_KEY**) as environment variables and adding them to Codemagic.

So remove this part
   ```
 integrations:
      app_store_connect: app_appstore_api_key
    environment:
      ios_signing:
        certificates:
          - app_apple_signing_certificate
```
Add the required environment variables to Codemagic: You can set them in the Codemagic UI as shown below:
![image](https://github.com/user-attachments/assets/7c396906-c5ef-4030-be64-56c43ed13879)

And reference the variables through the group name in your codemagic.yaml
```
    environment:
      groups:
        - client_001
```
also remove app store integration from publishing section and use variables
```
    artifacts: 
      - build/ios/ipa/*.ipa
    publishing:      
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
```
