### DISCUSSION TITLE
Feature Request: Allow specifying release name for Google play publishing in codemagic.yaml

### DISCUSSION THREAD

**Discussion by bibaswan-bhawal** [codemagic-ci-cd/codemagic-docs#2764] [Ideas]
Currently there is no way to provided a name for a google play release, the name parameter is part of the edits api however there is no way to set that from the yaml file. Since no name is provided the play store uses the app version as the release name. Currently we have to publish as a draft and manually go change the name in the play console but it would be great if we can jsut provide the name in the release pipeline and not have to publish as a draft.

**Comment by mikhail-tokarev** [comment]
Hey @bibaswan-bhawal 
just a quick update that we've added this feature request to our backlog, unfortunately no ETA for now.

**Comment by mohammedbabelly20** [comment]
Hey @bibaswan-bhawal 
I'm happy to share that this is now available in `codemagic.yaml`.

```
  publishing:
    google_play:
      credentials: ...
      release_name: custom release name!  # Optional text
```
Checkout the [docs](https://docs.codemagic.io/yaml-publishing/google-play/#configure-publishing-in-codemagicyaml) for more info.

**Reply by bbhawal-atec** [reply]
That's great to hear! does this support variables similar to the credentials
```
    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS_HOLDER
        release_name: $GOOGLE_APP_NAME_HOLDER
```

**Reply by mohammedbabelly20** [reply]
Sorry for the late response @bbhawal-atec 
Yes, it does support environment variables values.

**Reply by bibaswan-bhawal** [reply]
I'm having trouble making the environment variables work, I followed the same process as the Google credentials field but it seems that when I enter the $GOOGLE_APP_NAME a environment variable with the app name, it takes the variable name as a literal string, could you give a short example of using variables to set the name

**Reply by mohammedbabelly20** [reply]
Sure, here's a working example of google_play section in codemagic.yaml file

```
    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        release_name: $GOOGLE_PLAY_RELEASE_NAME. # <-- add this environment variable
        track: $GOOGLE_PLAY_TRACK
        submit_as_draft: true
```

**Reply by bbhawal-atec** [reply]
So this is my working codemagic yaml, and it seems the variable $GOOGLE_APP_NAME_HOLDER is being interpreted as a string instead of the variable

```
workflows:
  custom-workflow:
    instance_type: mac_mini_m2
    max_build_duration: 30
    integrations:
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      android_signing:
        - keystore_reference
      ios_signing:
        distribution_type: app_store
      groups:
        - service_account
        - vault_credentials
      vars:
      
        GCLOUD_SERVICE_ACCOUNT_CREDENTIALS_HOLDER: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        GOOGLE_APP_NAME_HOLDER: $GOOGLE_APP_NAME
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages and run build runner
        script: |
          flutter packages pub get
          dart run build_runner build
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      # - name: Flutter analyze
      #   script: |
      #     flutter analyze
      - name: Flutter unit tests
        script: |
          flutter test
        ignore_failure: true
      - name: Build AAB with Flutter
        script: |

          flutter build appbundle --dart-define-from-file .env.development

          export app_version="$(git describe --tags --abbrev=0) - $(git tag -l --format='%(contents)' $(git describe --tags --abbrev=0))"
         # Set app name
          echo "GOOGLE_APP_NAME<<DELIMITER" >> $CM_ENV
          echo "" >> $CM_ENV
          echo "DELIMITER" >> $CM_ENV
      - name: Flutter build ipa
        script: |
          flutter build ipa \
          --dart-define-from-file .env.development \
          --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log

    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS_HOLDER
        release_name: $GOOGLE_APP_NAME_HOLDER
        track: internal
        submit_as_draft: true
 ```
