### DISCUSSION TITLE
Building IPA for flutter fails

### DISCUSSION THREAD

**Discussion by roshandevajana** [codemagic-ci-cd/codemagic-docs#2776] [Q&A] [answered]
### If you are looking for help, please confirm the following...

- [X] I confirm I have searched the [Docs](https://docs.codemagic.io), [Codemagic Sample Projects](https://github.com/codemagic-ci-cd/codemagic-sample-projects), and GitHub [Discussions](https://github.com/orgs/codemagic-ci-cd/discussions).
- [X] I confirm the software versions on my local computer match the ones in CI environment (e.g. Xcode version, Gradle version). See [here](https://docs.codemagic.io/troubleshooting/common-android-issues/#builds-work-locally-but-fail-on-codemagic)
- [X] I confirm I am able to do a fresh clone of the repository and build the project on my local computer.

### Which mobile framework are you using?

Flutter (Dart)

### Steps to reproduce

1- Trigger IOS workflow build from codemagic
2- It pass many steps but it's fails while creating build

### Expected results

ipa artifact

### Actual results

![codemagic image](https://github.com/user-attachments/assets/5d4f46a4-143b-48d9-bf3f-fcbd07600560)

### Build id (optional)

66f50e631b24c115a009b145

**Comment by dam-ease** [comment, marked as answer]
Hello Roshan,
Looking through the general error logs, in the `xcode-project use-profiles` step, 
`Did not find matching provisioning profiles for code signing!`
There seems to be a mismatch between your `BUNDLE_ID` and the Provisioning Profile you are attempting to use to sign your application.
Can you please check out your `ios/Runner.xcworkspace` to verify that the Bundle Identifier in your project is your signing id in Xcode?

Afterwards, kindly specify this in your YAML file:
```
environment:
      ios_signing:
        distribution_type: app_store # or: ad_hoc | development | enterprise
        bundle_identifier: com.example.id
```
or make use of 

```
environment:
      ios_signing:
        provisioning_profiles:
          - profile_reference
          # - ...
        certificates:
          - certificate_reference
```
Here is a detailed guide on iOS code signing that could provide more insights into this: https://docs.codemagic.io/yaml-code-signing/signing-ios/

Lastly, are you having any issues sending messages via the chat widget in your codemagic UI? you can send a message using the chat widget for support and faster responses. Please let me know if you have any issues using the chat widget.
