### DISCUSSION TITLE
FVM configuration file not found

### DISCUSSION THREAD

**Discussion by rignaneseleo** [codemagic-ci-cd/codemagic-docs#2825] [Q&A] [answered]
### If you are looking for help, please confirm the following...

- [X] I confirm I have searched the [Docs](https://docs.codemagic.io), [Codemagic Sample Projects](https://github.com/codemagic-ci-cd/codemagic-sample-projects), and GitHub [Discussions](https://github.com/orgs/codemagic-ci-cd/discussions).
- [X] I confirm the software versions on my local computer match the ones in CI environment (e.g. Xcode version, Gradle version). See [here](https://docs.codemagic.io/troubleshooting/common-android-issues/#builds-work-locally-but-fail-on-codemagic)
- [X] I confirm I am able to do a fresh clone of the repository and build the project on my local computer.

### Which mobile framework are you using?

Flutter (Dart)

### Steps to reproduce

In my project, I've got `funlab/.fvm/fvm_config.json` file containing:

```
{
  "flutterSdkVersion": "master",
  "flavors": {}
}
```

However, when I run codemagic, I get error `FVM configuration file not found`.

I've set the Project path as funlab.

### Expected results

It should read the FVM configuration and compile.

### Actual results

It fails.

### Build id (optional)

6734b62cd758c6deb6a9f337

**Comment by rignaneseleo** [comment]
Probably it tries to read the .fvm folder from the root, but that's wrong because fvm is installed into the project folder, wherever that is (in my case `/funlab/`.

**Reply by dam-ease** [reply]
Hello @rignaneseleo,
What version of fvm do you currently use?
With version 3.0 and above `.fvm` is recommended to keep in `.gitignore` which is usually prompted as well, hence there are chances that your fvm folder is currently not being checked to git which is why the file cannot be found, kindly confirm that as well. Also, I'd suggest you work with `.fvmrc` and try building again

**Comment by rignaneseleo** [comment]
I updated FVM but build 673705a80aaa539da550437c still failed.
Checking the repo via github.com the `funlab/.fvmrc` file is correctly placed.

**Reply by dam-ease** [reply]
Thanks for your response @rignaneseleo.
Are you making use of a monorepo? I see your main project name is `thedadlab`, which suggests that fvm is being searched for in `thedadlab/.fvmrc`.

**Reply by rignaneseleo** [reply]
what do you mean? In the codemagic settings I've set the project path to `funlab` which is the folder that contains the `pubspec` as well as the `.fvmrc` file. Why would it search in the project root then?

**Reply by dam-ease** [reply, marked as answer]
Ohh, I see, then this is the issue, unfortunately, it is not possible to use workflow editor and fvm if your project is a monorepo, but you can set it up using `codemagic.yaml `.
The main thing is that you first need to set the path to your working directory then use the scripts section in order to configure and use FVM
![image (8)](https://github.com/user-attachments/assets/99892c32-8307-4d16-84a9-fea7d00d0180)

Let me share an[ example ](https://github.com/codemagic-ci-cd/codemagic-sample-projects/blob/main/flutter/flutter-android-and-ios-yaml-demo-project/codemagic.yaml)of the YAML configuration to use as a reference. You can also follow [this guide](https://docs.codemagic.io/yaml-quick-start/building-a-flutter-app/), which will help you set up your yaml workflow

**Reply by markbeij** [reply]
Do we actually need scripts to install fvm?

The following is not working for me:
```yaml
continuous-integration:
  name: Continuous Integration
  max_build_duration: 10
  working_directory: src
  environment:
    flutter: fvm
```

**Reply by dam-ease** [reply]
Hello @markbeij,
I responded to this via the in-app chat. Yes, you'd need the script to use fvm when the use case is a mono repo.

**Reply by markbeij** [reply]
Somehow I get issues when using this approach in combination with `melos`. To solve this, I still needed to pin the flutter version as well, so I end up with this
```yaml
  continuous-integration:
    name: Continuous Integration
    working_directory: src
    environment:
      flutter: 3.27.4 #we're not yet ready for 3.29
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter
        script: |
          echo Create symbolic link..
          ln -s $FLUTTER_ROOT $CM_BUILD_DIR/src/.fvm/flutter_sdk
          echo Setup Flutter
          brew tap leoafarias/fvm
          brew install fvm
          fvm install
          fvm flutter --version
          fvm use --force
          fvm flutter --version
      - name: Activate Melos
        script: dart pub global activate melos
      - name: Run tests
        script: melos test --no-select
```
