### DISCUSSION TITLE
A variable doesn't work for working_directory

### DISCUSSION THREAD

**Discussion by AndreyBobrovsky** [codemagic-ci-cd/codemagic-docs#2852] [Q&A] [answered]
### If you are looking for help, please confirm the following...

- [X] I confirm I have searched the [Docs](https://docs.codemagic.io), [Codemagic Sample Projects](https://github.com/codemagic-ci-cd/codemagic-sample-projects), and GitHub [Discussions](https://github.com/orgs/codemagic-ci-cd/discussions).
- [X] I confirm the software versions on my local computer match the ones in CI environment (e.g. Xcode version, Gradle version). See [here](https://docs.codemagic.io/troubleshooting/common-android-issues/#builds-work-locally-but-fail-on-codemagic)
- [X] I confirm I am able to do a fresh clone of the repository and build the project on my local computer.

### Which mobile framework are you using?

Flutter (Dart)

### Steps to reproduce

Hello, I need to have ability to specify different working_directory. I have added WORK_DIR in vars section and set working_directory: $WORK_DIR but this doesn't work, it fails. When I set working_directory: somedir, it works perfectly. What am I doing wrong?

Below is example of my yaml file:
```
ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    max_build_duration: 40 # build duration in minutes
    integrations:
      app_store_connect: ANDREY_MAGIC_BUILD
    environment:
      groups:
        - code-signing
      vars:
        BUNDLE_ID: "none"
        WORK_DIR: "none"
      flutter: 3.19.2
      xcode: 15.0 # <-- xcode: latest, set to specific version e.g. 14.3, 15.0 to avoid unexpected updates.
      cocoapods: 1.15.2 # cocoapods: default
    working_directory: $WORK_DIR
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Set up keychain to be used for code signing using Codemagic CLI 'keychain' command
        script: keychain initialize
```

I'm calling a new build in Postman like this
![image](https://github.com/user-attachments/assets/18e08b9b-d8a9-4a22-9057-91eeea74742e)

### Expected results

I want to use my defined variable for working_directory.

### Actual results

It doesn't use my WORK_DIR var for working_directory.

### Build id (optional)

6746047eb5f296efbb41898c

**Comment by dam-ease** [comment]
Hello @AndreyBobrovsky,
The issue with the `working_directory` not seeing the variable `WORK_DIR` seems to be because the `working_directory` field in Codemagic YAML currently does not support dynamically set environment variables. It expects a static string value during initialization.
If you echo the value of the $WORK_DIR after hardcoding the value of the working directory, are you able to access the value? If yes, a workaround here can be using cd in script i.e.
```
scripts:
  - name: Change working directory
    script: |
      cd $WORK_DIR
      flutter packages pub get
```
Please let me know how this goes on your end.

**Comment by AndreyBobrovsky** [comment]
Hello @dam-ease,
thanks for your reply. Unfortunately, but your trick didn't work out. Maybe you can suggest another way?
![image](https://github.com/user-attachments/assets/7c856601-1c6a-4e85-b2cc-6f03fe1b75ae)

**Reply by dam-ease** [reply]
Thanks for your response @AndreyBobrovsky 
I see you didn't print out the value of $WORK_DIR in your script, like I said in my previous comment, this will only be a viable workaround if you are able to access the value of the $WORK_DIR since the working_directory field in Codemagic YAML currently does not support dynamically set environment variables. So please try:
```
scripts:
 - name: Get working directory
    script: |
      echo $WORK_DIR
  - name: Change working directory
    script: |
      cd $WORK_DIR
      flutter packages pub get
```
Please also set a default value for $WORK_DIR in the var section of your YAML file.
```
vars:
        WORK_DIR: "default"
```

**Reply by AndreyBobrovsky** [reply]
I'm really confused. When I created almost empty workflow then I have access to $WORK_DIR and 'echo' command prints value of var. When I use the same $WORK_DIR var in my main workflow the build fails.

My test workflow:
![image](https://github.com/user-attachments/assets/f5b0942c-4f1b-4113-85d9-abb1b8516d0b)

This workflow finishes ok:
![image](https://github.com/user-attachments/assets/29332180-d40f-41d3-96ca-051b1e29252e)

Below is my main workflow with the same Info step, and this info steps fails, understand nothing
![image](https://github.com/user-attachments/assets/91ed4ee6-791e-48a0-9272-863b15550d12)

This workflow fails:
![image](https://github.com/user-attachments/assets/37ee1a00-428f-47f3-8edc-5fd3391821a2)

What is wrong?

**Reply by dam-ease** [reply]
Hello @AndreyBobrovsky,
Thanks for your detailed response. The reason the echo fails in the second build you shared is because the `working_directory` has been set to `default` which doesn't exist before the scripts are executed.
Since the `working_directory` will be set to the default value before the scripts are executed, then the workaround I suggested earlier won't work in this case.
> I need to have ability to specify different working_directory. 

Unfortunately, the working_directory can't be set via environment variables through API calls and the way this will work will be as in the first build of your last response. We are currently planning to improve this to support your use case but can’t give an exact timeline yet.

If creating multiple workflows to achieve this doesn't work in your case for now, another workaround here will be instead of setting the `working_directory` dynamically, using a script to change the directory at the beginning of the build process. An example is:
```
ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    max_build_duration: 40 # build duration in minutes
    integrations:
      app_store_connect: ANDREY_MAGIC_BUILD
    environment:
      groups:
        - code-signing
      vars:
        BUNDLE_ID: "none"
        WORK_DIR: "default"
      flutter: 3.19.2
      xcode: 15.0
      cocoapods: 1.15.2
    scripts:
      - name: Change to working directory
        script: |
          cd $WORK_DIR
          echo "Current directory: $(pwd)"
      - name: Get Flutter packages
        script: |
          flutter packages pub get
```
Here, in your API call, you'd need to specify the full path, an example on my end:
```
"environment": {
            "variables": {
              "WORK_DIR": "apps/counter_app"
            }
          }
```
