### DISCUSSION TITLE
Build failed after project restructure

### DISCUSSION THREAD

**Discussion by Kutbi-dev** [codemagic-ci-cd/codemagic-docs#2894] [Q&A] [answered]
### If you are looking for help, please confirm the following...

- [X] I confirm I have searched the [Docs](https://docs.codemagic.io), [Codemagic Sample Projects](https://github.com/codemagic-ci-cd/codemagic-sample-projects), and GitHub [Discussions](https://github.com/orgs/codemagic-ci-cd/discussions).
- [X] I confirm the software versions on my local computer match the ones in CI environment (e.g. Xcode version, Gradle version). See [here](https://docs.codemagic.io/troubleshooting/common-android-issues/#builds-work-locally-but-fail-on-codemagic)
- [X] I confirm I am able to do a fresh clone of the repository and build the project on my local computer.

### Which mobile framework are you using?

React Native

### Steps to reproduce

Change the structure of the existing project.
Before it was directly in the root folder and now it is in apps/white-label-application/whiteLabelApplication
getting below error in build ipa steps of build pipeline
I also have verified and took the appropriate changes in code magic yaml file related to the two level up structure.

  **/Users/builder/clone/apps/white-label-application/whiteLabelApplication/ios/whiteLabelApplication.xcodeproj: error: "whiteLabelApplication" requires a provisioning profile with the Associated Domains and Push Notifications features. Select a provisioning profile in the Signing & Capabilities editor. (in target 'whiteLabelApplication' from project 'whiteLabelApplication')**

### Expected results

Build should be successfully published on the stores.

### Actual results

<img width="1649" alt="Screenshot 2024-12-19 at 2 16 47 PM" src="https://github.com/user-attachments/assets/024f596f-49ec-41a4-8f33-27966a5534f1" />

Attached is the screenshot of the error I am getting while building the pipeline.

### Build id (optional)

6762b7938d06277ff9441e0f

**Comment by dam-ease** [comment]
Hello @Kutbi-dev
```
Did not find matching provisioning profiles for code signing!
```
I can see this error in your code signing step before picking up the adhoc certificate. Since you are building white label, automatic code signing might be the best route here. This generates and manages provisioning profiles for each unique $BUNDLE_ID during the build process. You can check out more on this [here](https://docs.codemagic.io/yaml-code-signing/alternative-code-signing-methods/).
There is also a sample project here you can follow to achieve this [here](https://github.com/codemagic-ci-cd/codemagic-sample-projects/blob/main/ios/ios-white-label-single-scheme-demo-project/codemagic.yaml)

**Comment by Kutbi-dev** [comment]
Thank you for your quick response @dam-ease 
I just want to add one more point, when I publish the build from my old project structure, it successfully published for both android an iOS.
Above issue occurs only when I publish the build with the new project structure.
Earlier my project structure was **root/WhiteLabelApplication** and new structure is **root/app/white-label-app/WhiteLabelApplication**
So basically it is two level up now.
I made necessary changes in codemagic.yaml file and updated the path as per the new structure. 
After applying these changes in yaml file it gives the successful build for android but for iOS it gives the above error.
So, here my question is if it is related to the profile it wont even successfully published for older project structure.
Please let me know if you have any insights about this and I am attaching my updated .yaml file for your reference.
.............................................................................................................................................................................................................................
```
#TODO to add build triggers and code signings
definitions:
  scripts:
    - &export_env_variables
      name: Export Environment Variables
      script: cd $FCI_BUILD_DIR/apps/white-label-app/tools/; ./codemagic-env-variables.sh
    - &install_modules
      name: Install nodemodules
      script: cd $FCI_BUILD_DIR/apps/white-label-app/whiteLabelApplication; npm install
    - &echo_dir
      name: Echo dir
      script: echo "sdk.dir=$HOME/whiteLabelApplication/programs/android-sdk-macosx" > "$FCI_BUILD_DIR/apps/white-label-app/whiteLabelApplication/android/local.properties"
    - &build_android
      name: Build Android
      script: cd $FCI_BUILD_DIR/apps/white-label-app/whiteLabelApplication/android; ./gradlew $PRODUCT_FLAVOR
    - &install_pods
      name: Install pods
      script: |
        cd $FCI_BUILD_DIR/apps/white-label-app/whiteLabelApplication/ios; pod repo update; pod install
    - &ios_keychain
      name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
      script: keychain initialize
    - &ios_signing_files
      name: Fetch signing files
      script: |
        app-store-connect fetch-signing-files $BUNDLE_ID \
        --type IOS_APP_STORE \
        --create
    - &ios_signing_certs
      name: Set up signing certificate
      script: keychain add-certificates
    - &ios_signing_setup
      name: Set up code signing settings on Xcode project
      script: xcode-project use-profiles
    - &ios_increment_build
      name: increment build number
      # script: cd $FCI_BUILD_DIR/apps/white-label-app/whiteLabelApplication/ios; agvtool new-version -all "$VERSION_NUMBER".$(($BUILD_NUMBER +1)); agvtool new-marketing-version "$VERSION_NUMBER".$(($BUILD_NUMBER +1));
      script: |
        # Navigate to the iOS directory
        cd $FCI_BUILD_DIR/apps/white-label-app/whiteLabelApplication/ios

        # Fetch the latest build number and increment it
        BUILD_NUMBER=$(($BUILD_NUMBER + 1))

        # Set the new build number using agvtool
        agvtool new-version -all $BUILD_NUMBER

        # Set the marketing version to the one passed from CLI (without incrementing)
        agvtool new-marketing-version "$VERSION_NUMBER"
    - &ios_build
      name: Build ipa
      script: |
        cd $FCI_BUILD_DIR/apps/white-label-app/whiteLabelApplication/ios; xcode-project build-ipa --workspace "$FCI_BUILD_DIR/apps/white-label-app/whiteLabelApplication/ios/whiteLabelApplication.xcworkspace" --scheme $XCODE_SCHEME
    - &ios_export_to_app_center
      name: Run IOS export to App Center
      script: cd $FCI_BUILD_DIR/apps/white-label-app/tools/; ./publish-ipa-to-app-centre.sh
    - &android_export_to_app_center
      name: Run IOS export to App Center
      script: cd $FCI_BUILD_DIR/apps/white-label-app/tools/; ./publish-apk-to-app-centre.sh
    - &clean_up_brands_not_required_for_given_flavor
      name: Clean Up Brands not required for the given Flavor
      script: cd $FCI_BUILD_DIR/apps/white-label-app/tools/; ./codemagic-delete-unused-assets.sh ${XCODE_SCHEME}
  artifacts:
    - &apk $FCI_BUILD_DIR/apps/white-label-app/whiteLabelApplication/android/app/build/outputs/apk/release/*.apk
    - &aab $FCI_BUILD_DIR/apps/white-label-app/whiteLabelApplication/android/app/build/outputs/bundle/release/*.aab
    - &ipa $FCI_BUILD_DIR/apps/white-label-app/whiteLabelApplication/ios/build/ios/ipa/*.ipa
    - &dsym $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
  publishing:
    slack: &slack
      channel: "#app-builds"
      notify_on_build_start: true
      notify:
        success: true
        failure: true
workflows:
  aura_store:
    name: Aura Store
    instance_type: mac_mini_m2
    environment:
      node: 18.20.3
      npm: 7.20.3
      xcode: 16.1
      java: 17
      vars:
        NEW_BASE_PATH: "$FCI_BUILD_DIR/apps/white-label-app"
        XCODE_SCHEME: ""
        BUNDLE_ID: ""
        BUNDLE_ID_IDENTIFIER: ""
        APP_CENTER_TOKEN: ""
        APP_CENTER_ORG: "Developments"
        PLAY_STORE_API: ""
      
    scripts:
      - name: Prepare Whitelabel
        script: |
          echo "Preparing Whitelabel"
          cd $NEW_BASE_PATH/tools/; ./settingUpWhitelabel.sh
      - name: Keychain
        script: |
          keychain initialize
      - name: Keychain
        script: |
          app-store-connect fetch-signing-files $BUNDLE_ID \
          --type IOS_APP_STORE \
          --create
      - name: Set up Yarn (use project-specific version)
        script: yarn set version 3.6.0
      - name: Install Modules
        script: |
          cd $NEW_BASE_PATH/whiteLabelApplication; yarn install --immutable
      - name: SSH KEY
        script: |
          echo "sdk.dir=$HOME/whiteLabelApplication/programs/android-sdk-macosx" > "$NEW_BASE_PATH/whiteLabelApplication/android/local.properties"
      - name: Build Android
        script: |
          echo $FCI_KEYSTORE | base64 --decode > $FCI_KEYSTORE_PATH
          cd $NEW_BASE_PATH/whiteLabelApplication/android && ./gradlew bundleRelease
      - name: Publish App Gallery
        script: |
          cd $NEW_BASE_PATH/tools
          ./publish-aab-to-app-gallery.sh
      - name: Install Pods
        script: |
          cd $NEW_BASE_PATH/whiteLabelApplication/ios; pod repo update; pod install
      - name: Set up signing certificate
        script: |
          keychain add-certificates
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles --project whiteLabelApplication/ios/*.xcodeproj
      - name: increment build number
        # script: |
        #   cd $FCI_BUILD_DIR/apps/white-label-app/whiteLabelApplication/ios; agvtool new-version -all "$VERSION_NUMBER".$(($BUILD_NUMBER +1)); agvtool new-marketing-version "$VERSION_NUMBER".$(($BUILD_NUMBER +1));
        script: |
          # Navigate to the iOS directory
          cd $NEW_BASE_PATH/whiteLabelApplication/ios

          # Fetch the latest build number and increment it
          BUILD_NUMBER=$(($BUILD_NUMBER + 1))

          # Set the new build number using agvtool
          agvtool new-version -all $BUILD_NUMBER

          # Set the marketing version to the one passed from CLI (without incrementing)
          agvtool new-marketing-version "$VERSION_NUMBER"
      - name: Build ipa
        script: |
          cd $NEW_BASE_PATH/whiteLabelApplication/ios; xcode-project build-ipa --workspace "$NEW_BASE_PATH/whiteLabelApplication/ios/whiteLabelApplication.xcworkspace"

    artifacts:
      - *apk
      - *aab
      - *ipa
      - *dsym
    publishing:
      app_store_connect: # For iOS app
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
      google_play: # For Android app
        credentials: $PLAY_STORE_API
        track: internal # Name of the track: internal, alpha, beta, production, internal app sharing
        changes_not_sent_for_review: false
      slack: *slack
    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/Library/Caches/CocoaPods
```

**Reply by dam-ease** [reply, marked as answer]
Hello @Kutbi-dev,
Thanks for the details!
The reason iOS failed and Android passed seems to be because you didn't change directory before running the iOS related commands.
Instead of having to change the directory every time a script is run, you can define **working_directory**, every command that is defined in the scripts section will run inside that particular directory. E.g.
```
workflows:
  default-workflow:
    name: Default workflow
    # Specify path to the app folder like this
    working_directory: my_first_app
```
Kindly try this out and please share how it goes on your end.
