### DISCUSSION TITLE
Build not triggered on Merge Request Approval in Gitlab

### DISCUSSION THREAD

**Discussion by evgeny-sureev** [codemagic-ci-cd/codemagic-docs#2896] [Q&A] [answered]
### If you are looking for help, please confirm the following...

- [X] I confirm I have searched the [Docs](https://docs.codemagic.io), [Codemagic Sample Projects](https://github.com/codemagic-ci-cd/codemagic-sample-projects), and GitHub [Discussions](https://github.com/orgs/codemagic-ci-cd/discussions).
- [X] I confirm the software versions on my local computer match the ones in CI environment (e.g. Xcode version, Gradle version). See [here](https://docs.codemagic.io/troubleshooting/common-android-issues/#builds-work-locally-but-fail-on-codemagic)
- [X] I confirm I am able to do a fresh clone of the repository and build the project on my local computer.

### Which mobile framework are you using?

iOS (Swift, Objective-C)

### Steps to reproduce

I have set up webhooks to be triggered by updates on merge requests.
Upon creation and for updates to MR, tests are run. This workflow works.
On MR approval I have set up building and deploying test build. This workfow does not triggers at all.

Sample workflow:
```yaml
workflows:
  approve_me:
    name: MR Approval test
    max_build_duration: 120
    instance_type: mac_mini_m2
    triggering:
      events:
        - pull_request
      cancel_previous_builds: true
    when:
      condition: event.object_attributes.action == "approved"
    scripts:
      - name: "MR got approval"
        script: echo "SUCCESS"
```

### Expected results

On MR approval workflow starts.

### Actual results

Workflow does not start, in "Recent deliveries" section there are delivery with text "Welcome to Codemagic! Your builds will be started on branch push".

**Comment by dam-ease** [comment]
Hello @evgeny-sureev,
To trigger the build after the pull request has been merged, you can target the destination branch. Setting `source:true`, `pattern:main` will trigger the build on the main branch once the pull request has been merged from the feature branch into the main branch.
```
triggering:
  events:
    - push
    - pull_request
  branch_patterns:
    - pattern: 'main'
      include: true
      source: true 
```
The above pattern is set for the main branch but you can set similar patterns for any branch depending on your workflow.
