### DISCUSSION TITLE
exportArchive "Runner.app" requires a provisioning profile with the Associated Domains and Push Notifications features.

### DISCUSSION THREAD

**Discussion by shubham-settlin** [codemagic-ci-cd/codemagic-docs#2915] [Q&A] [answered]
### If you are looking for help, please confirm the following...

- [X] I confirm I have searched the [Docs](https://docs.codemagic.io), [Codemagic Sample Projects](https://github.com/codemagic-ci-cd/codemagic-sample-projects), and GitHub [Discussions](https://github.com/orgs/codemagic-ci-cd/discussions).
- [X] I confirm the software versions on my local computer match the ones in CI environment (e.g. Xcode version, Gradle version). See [here](https://docs.codemagic.io/troubleshooting/common-android-issues/#builds-work-locally-but-fail-on-codemagic)
- [X] I confirm I am able to do a fresh clone of the repository and build the project on my local computer.

### Which mobile framework are you using?

Flutter (Dart)

### Steps to reproduce

I have added these settings in codemagic.yaml file.

```
environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: <my bundle id>
        
  scripts:
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
```

The IPA is building correctly when I try building it locally, but it’s not working in Codemagic. Do I need to add the export-options-plist flag when building the IPA, or is this already handled by the "xcode-project use-profiles" command? In the log, I can see "Saved export options to /Users/builder/export_options.plist" with correct provisioning profile.

Also i have checked, all the capabilities needed are already added in provisioning profile. The certificates and provisioning profile are added in signing identities as suggested in the doc.

### Expected results

IPA should be built and exported to app store connect.

### Actual results

Building App Store IPA... (completed in 1,374ms)
[        ] Encountered error while creating the IPA:
[        ] error: exportArchive "Runner.app" requires a provisioning profile with the Associated Domains and Push Notifications features.
