### DISCUSSION TITLE
macOS publishing produces iOS revision submission instead of macOS submission

### DISCUSSION THREAD

**Discussion by daniel-dosiper** [codemagic-ci-cd/codemagic-docs#2971] [Q&A]
### If you are looking for help, please confirm the following...

- [X] I confirm I have searched the [Docs](https://docs.codemagic.io), [Codemagic Sample Projects](https://github.com/codemagic-ci-cd/codemagic-sample-projects), and GitHub [Discussions](https://github.com/orgs/codemagic-ci-cd/discussions).
- [X] I confirm the software versions on my local computer match the ones in CI environment (e.g. Xcode version, Gradle version). See [here](https://docs.codemagic.io/troubleshooting/common-android-issues/#builds-work-locally-but-fail-on-codemagic)
- [X] I confirm I am able to do a fresh clone of the repository and build the project on my local computer.

### Which mobile framework are you using?

Flutter (Dart)

### Steps to reproduce

```yaml
# Guide for Android/iOS workflows: https://github.com/codemagic-ci-cd/codemagic-sample-projects/tree/main/flutter/flutter-android-and-ios-yaml-demo-project
# Guide for macOS: https://github.com/codemagic-ci-cd/codemagic-sample-projects/tree/main/flutter/flutter-macos-demo-project
# Guide for Windows: https://github.com/codemagic-ci-cd/codemagic-sample-projects/tree/main/flutter/flutter-windows-demo-project
definitions:
  dosiper_working_directory: &dosiper_working_directory
    working_directory: dosiper
  def_max_build_duration: &def_max_build_duration
    max_build_duration: 120
  android_dosiper_package_name: &android_dosiper_package_name
    PACKAGE_NAME: "com.dosiper.lavnet"
  android_common_environment: &android_common_environment
    android_signing:
      - android_dosiper_keystore
    groups:
      - google_play
    flutter: stable
  android_dosiper_environment: &android_dosiper_environment
    environment:
      <<: *android_common_environment
      vars:
        <<: *android_dosiper_package_name
        GOOGLE_PLAY_TRACK: "production"
  apple_developer_portal_integrations: &apple_developer_portal_integrations
    # Integration section is required to make use of the keys stored in 
    # Codemagic UI under Apple Developer Portal integration.
    integrations:
      app_store_connect: codemagic
  ios_macos_common_environment: &ios_macos_common_environment
    flutter: stable
    xcode: 15.3 # <-- set to specific version e.g. 14.3, 15.0 to avoid unexpected updates.
    cocoapods: default
  scripts:
    - &get_flutter_packages
      name: Get Flutter packages
      script: |
        flutter packages pub get
    - &flutter_analyze
      name: Flutter analyze
      script: |
        flutter analyze 
    - &build_aab_with_flutter
      name: Build AAB with Flutter
      script: |
        BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks="$GOOGLE_PLAY_TRACK") + 1))      
        flutter build appbundle --release \
          --build-number=$BUILD_NUMBER
    - &keychain_initialize
      name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
      script: |
        keychain initialize
    - &fetch_mac_app_distribution_cert_and_profile
      name: Fetch Mac App Distribution certificate and Mac App Store profile
      script: |
        app-store-connect fetch-signing-files \
          "$(xcode-project detect-bundle-id)" \
          --platform MAC_OS \
          --type MAC_APP_STORE \
          --create
    - &fetch_mac_installer_distribution_certs
      name: Fetch Mac Installer Distribution certificates
      script: |
        # Watch out! We first have to uncomment only the "create" line to first create the certificate and after
        # that uncomment only the "list". This is because it doesnt work the OR option indicated in the original
        # example like this:
          # app-store-connect certificates list --type MAC_APP_DISTRIBUTION --save || \
          # app-store-connect certificates create --type MAC_APP_DISTRIBUTION --save
        # app-store-connect certificates create --type MAC_INSTALLER_DISTRIBUTION --save
        app-store-connect certificates list --type MAC_INSTALLER_DISTRIBUTION --save
    - &keychain_add_certificates
      name: Set up signing certificate
      script: |
        keychain add-certificates
    - &set_up_signing_settings_on_xcode
      name: Set up code signing settings on Xcode project
      script: |
        xcode-project use-profiles
    - &install_homebrew
      name: Install Homebrew
      script: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    - &install_homebrew_dependencies
      name: Install Homebrew required dependencies to install pods on the next step
      script: |
        brew install automake libtool
    - &install_ios_pods
      name: Install pods
      script: |
        find ios -name "Podfile" -execdir pod install \;
    - &install_macos_pods
      name: Install pods
      script: |
        find macos -name "Podfile" -execdir pod install \;
    - &flutter_build_ios
      name: Flutter build ipa and automatic versioning
      script: |
        flutter build ipa --release \
          --export-options-plist=/Users/builder/export_options.plist
    - &flutter_build_macos
      name: Build Flutter macOS
      script: |
        flutter config --enable-macos-desktop && \
        flutter build macos --release
    - &package_macos_app
      name: Package macOS application
      script: |
        set -x

        # Command to find the path to your generated app
        APP_NAME=$(find $(pwd) -name "*.app")
        cd $(dirname "$APP_NAME")
        PACKAGE_NAME=$(basename "$APP_NAME" .app).pkg

        # Create an unsigned package
        xcrun productbuild --component "$APP_NAME" /Applications/ unsigned.pkg

        # Find the installer certificate commmon name in keychain
        INSTALLER_CERT_NAME=$(keychain list-certificates \
          | jq '.[]
          | select(.common_name
          | contains("Mac Developer Installer"))
          | .common_name' \
          | xargs)

        # Sign the package
        xcrun productsign --sign "$INSTALLER_CERT_NAME" unsigned.pkg "$PACKAGE_NAME"

        # Optionally remove the not needed unsigned package
        rm -f unsigned.pkg
    - &flutter_config_windows
      name: Configure for Windows
      script: flutter config --enable-windows-desktop
    - &package_windows
      name: Package Windows
      script: dart run msix:create
  android_artifacts: &android_artifacts
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
  ios_artifacts: &ios_artifacts
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
  macos_artifacts: &macos_artifacts
    artifacts:
      - build/macos/**/*.pkg
  windows_artifacts: &windows_artifacts
    artifacts:
      - build/windows/**/*.msix
  trigger_on_release: &trigger_on_release
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: '*-release' # Trigger build on release like this: v2.1.5-release
          include: true
      cancel_previous_builds: true  # Set to `true` to automatically cancel outdated webhook builds
  publishing:
    email_publishing: &email_publishing
      email:
        recipients:
          - d.hernaez@dosiper.com
        notify:
          success: true
          failure: true
    google_play_publishing: &google_play_publishing
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: $GOOGLE_PLAY_TRACK
        submit_as_draft: false
    ios_app_store_connect: &ios_app_store_connect
      app_store_connect:
        auth: integration
        submit_to_app_store: true
        release_type: AFTER_APPROVAL
    macos_app_store_connect: &macos_app_store_connect
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_app_store: true
        release_type: AFTER_APPROVAL
    microsoft_partner_center: &microsoft_partner_center
      partner_center: # THESE VARIABLES COME FROM CODEMAGIC ENVIRONMENT VARIABLES, ALREADY DEFINED IN THE ACCOUNT
        store_id: $STORE_ID # Field "Store ID" --> https://partner.microsoft.com/en-us/dashboard/products/9PMQRQ80HTKM/identity
        tenant_id: $TENANT_ID # "Id de directorio (inquilino)" --> https://portal.azure.com/#view/Microsoft_AAD_RegisteredApps/ApplicationMenuBlade/~/Overview/appId/dfb2c79b-2edb-4c83-bb0c-a1ba78330391/isMSAApp~/false
        client_id: $CLIENT_ID # Id. de aplicación (cliente) --> https://portal.azure.com/#view/Microsoft_AAD_RegisteredApps/ApplicationMenuBlade/~/Overview/appId/dfb2c79b-2edb-4c83-bb0c-a1ba78330391/isMSAApp~/false
        client_secret: $CLIENT_SECRET # Column "Value (valor)" of the scret key: https://portal.azure.com/#view/Microsoft_AAD_RegisteredApps/ApplicationMenuBlade/~/Credentials/appId/dfb2c79b-2edb-4c83-bb0c-a1ba78330391/isMSAApp~/false
  workflows:
    def-android-workflow: &def-android-workflow
      instance_type: mac_mini_m2
      <<: *def_max_build_duration
      <<: *trigger_on_release
      scripts:
        - *get_flutter_packages
        - *flutter_analyze
        - *build_aab_with_flutter
      <<: *android_artifacts
      publishing:
        <<: *email_publishing
        <<: *google_play_publishing
    def-ios-workflow: &def-ios-workflow
      instance_type: mac_mini_m2
      <<: *def_max_build_duration
      <<: *trigger_on_release
      <<: *apple_developer_portal_integrations
      scripts:
        - *set_up_signing_settings_on_xcode
        - *get_flutter_packages
        - *flutter_analyze
        - *install_homebrew
        - *install_homebrew_dependencies
        - *install_ios_pods
        - *flutter_build_ios
      <<: *ios_artifacts
      publishing:
        <<: *email_publishing
        <<: *ios_app_store_connect
    def-macos-workflow: &def-macos-workflow
      instance_type: mac_mini_m2
      <<: *def_max_build_duration
      <<: *trigger_on_release
      environment:
        <<: *ios_macos_common_environment
        groups:
          - appstore_credentials # <-- (Includes APP_STORE_CONNECT_ISSUER_ID, APP_STORE_CONNECT_KEY_IDENTIFIER, APP_STORE_CONNECT_PRIVATE_KEY)
      scripts:
        - *keychain_initialize
        - *fetch_mac_app_distribution_cert_and_profile
        - *fetch_mac_installer_distribution_certs
        - *keychain_add_certificates
        - *set_up_signing_settings_on_xcode
        - *get_flutter_packages
        - *flutter_analyze
        - *install_homebrew
        - *install_homebrew_dependencies
        - *install_macos_pods
        - *flutter_build_macos
        - *package_macos_app
      <<: *macos_artifacts
      publishing:
        <<: *email_publishing
        <<: *macos_app_store_connect
    def-windows-workflow: &def-windows-workflow
      instance_type: windows_x2
      <<: *def_max_build_duration
      <<: *trigger_on_release
      environment:
        groups:
          - windows_credentials # includes variables to use in partner_center section
        flutter: stable
      scripts:
        - *get_flutter_packages
        - *flutter_analyze
        - *flutter_config_windows
        - *package_windows
      <<: *windows_artifacts
      publishing:
        <<: *microsoft_partner_center
        <<: *email_publishing
workflows:
  dosiper-android-workflow:
    name: Dosiper Android Workflow
    working_directory: dosiper
    <<: *android_dosiper_environment
    <<: *def-android-workflow
  dosiper-ios-workflow:
    name: Dosiper iOS Workflow
    working_directory: dosiper
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.dosiper.lavnet
      vars:
        APP_ID: 6499311224 # <-- https://appstoreconnect.apple.com/apps/6499311224/distribution/info 
      <<: *ios_macos_common_environment
    <<: *def-ios-workflow
  dosiper-macOS-workflow:
    name: Dosiper macOS Workflow
    working_directory: dosiper
    <<: *def-macos-workflow
  dosiper-windows-workflow:
    name: Dosiper Windows workflow
    working_directory: dosiper
    <<: *def-windows-workflow

```

### Expected results

Everything works as expected except for the macOS publishing step.

### Actual results

The problem seems to be that macOS publishing is creating an "iOS" revision submission instead of a "macOS" submission, I attach the full log here:

[app_store_connect_distribution.log](https://github.com/user-attachments/files/18732393/app_store_connect_distribution.log)

I tried to set "platorm: MAC_OS" in the "app_store_connect" section according to the [underlying tool](https://github.com/codemagic-ci-cd/cli-tools/blob/master/docs/app-store-connect/publish.md) but yaml validation is triggering an error saying this parameter is not allowed here

### Build id (optional)

67a5b96d7740b709e52a5ed3
