### DISCUSSION TITLE
Be able to upload many Android artifacts in a single Codemagic build

### DISCUSSION THREAD

**Discussion by rocboronat** [codemagic-ci-cd/codemagic-docs#2991] [Ideas]
### Use case

We have a Flutter app that has two flavors, free and pro, and in addition, two artifacts for every flavor, the mobile app and the Wear app.

As a single Google Play upload can happen in a single build, we must have four builds to upload all the artifacts, although we could do all the compilations together and save some time (and resources).

### Idea

Let us have many Google Play uploads in a single Codemagic build, and be able to say which artifact has to upload every Google Play delivery. It could look like this:

```
google_play:
  credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
  track: 'production'
  rollout_fraction: 0.20
  submit_as_draft: false
  file: /build/x/y/z/app-free-release.aab
google_play:
  credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
  track: 'production'
  rollout_fraction: 0.20
  submit_as_draft: false
  file: /build/x/y/z/wear-free-release.aab
google_play:
  credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
  track: 'production'
  rollout_fraction: 0.20
  submit_as_draft: false
  file: /build/x/y/z/app-pro-release.aab
google_play:
  credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
  track: 'production'
  rollout_fraction: 0.20
  submit_as_draft: false
  file: /build/x/y/z/wear-pro-release.aab
```

**Comment by EsteveAguilera** [comment]
![img](https://github.com/user-attachments/assets/3f6dbd88-e606-4967-a8ff-d0a155960839)

This is what we have to do in order to deliver the mobile app to Google:
1. build both apps
2. delete the Wear app
3. deliver to Google.
 
To deliver the Wear app it's the same, but deleting the mobile app before delivering it to Google.

If we were able to do two deliveries in the same build, specifying the AAB to deliver, that would save many resources.

**Comment by mikhail-tokarev** [comment]
Thanks for your post and for sharing your use case! It's really valuable.

At the moment we are working on improving [CLI tools](https://github.com/codemagic-ci-cd/cli-tools) to simplify Google Play publishing. It should be definitely possible to publish multiple artifacts from the single workflow.

As the next step, since we use the CLI tools internally, we can also add YAML support for it too. I'll keep this thread open to share updates with you.

**Reply by mikhail-tokarev** [reply]
hey @rocboronat 
just a quick update. We've added Google Play support to CLI tools, any feedback are welcome! example:
```
google-play bundles publish \
  --bundle path/to/app-release.aab \
  --track "internal" \
  --release-name "My release" \
  --rollout-fraction 0.05 \
  --in-app-update-priority 3
```

- quick overview in [release notes](https://github.com/codemagic-ci-cd/cli-tools/releases/tag/v0.57.0) NB! current stable version is 0.57.3
- and docs [here](https://github.com/codemagic-ci-cd/cli-tools/blob/master/docs/google-play/README.md)

**Reply by rocboronat** [reply]
Hey @mikhail-tokarev, thank you so much for this!

One thing, it's not working but it has to be for something super small. I'm receiving the error `google-play bundles publish: error: argument --credentials: Provided value is not a valid JSON`. As I'm "migrating" from the regular `google_play` section inside the `publishing` section, I thought I just had to copy paste the credentials I was defining there in this new approach. 

So I went from here 👇 
```yaml
publishing:
  google_play:
    credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
    track: 'production'
    rollout_fraction: 0.20
```

To here 👇 
```yaml
scripts:
  - name: Upload Free mobile app
    script: |
      google-play bundles publish \
      --credentials $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS \
      --track "production" \
      --rollout 0.20 \
      --bundle build/app/outputs/bundle/freeRelease/app-free-release.aab
```

But I'm getting that `Provided value is not a valid JSON`. So my next approach based on the docs was to do something simpler that only used the credentials. Also to avoid having to wait for the whole build to finish 😄 So I made this other script:

```yaml
scripts:
  - name: Check the integration with Google Play
  script: |
    google-play get-latest-build-number \
    --credentials $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS \
    --package-name "com.EAGINsoftware.dejaloYa" \
    --json
```
But I'm getting the same: `Provided value is not a valid JSON`. So the main question... Can't I reuse the credentials for the "more yaml approach" in this other one?

Thanks!
