### DISCUSSION TITLE
How to check if event.pull_request.labels contains certain name in `when.condition`

### DISCUSSION THREAD

**Discussion by fummicc1** [codemagic-ci-cd/codemagic-docs#3081] [Q&A] [answered]
### If you are looking for help, please confirm the following...

- [X] I confirm I have searched the [Docs](https://docs.codemagic.io), [Codemagic Sample Projects](https://github.com/codemagic-ci-cd/codemagic-sample-projects), and GitHub [Discussions](https://github.com/orgs/codemagic-ci-cd/discussions).
- [X] I confirm the software versions on my local computer match the ones in CI environment (e.g. Xcode version, Gradle version). See [here](https://docs.codemagic.io/troubleshooting/common-android-issues/#builds-work-locally-but-fail-on-codemagic)
- [X] I confirm I am able to do a fresh clone of the repository and build the project on my local computer.

### Which mobile framework are you using?

Flutter (Dart)

### Steps to reproduce

1. Prepare a workflow like the below

```yaml
  foo:
    name: foo
    triggering:
      events:
        - pull_request
        - pull_request_labeled
      branch_patterns:
        - pattern: "main"
          include: true
          source: false
    when:
      condition: event.pull_request.labels[0].name == "foo1"
```

2. Create a PR into main branch and add label named `foo` and `foo1`. Then, add new commit into source branch.
3. `foo` workflow's build skips because it does not match with `when` condition. I guess `foo1` is stored in `event.pull_request.labels[1]`.

### Expected results

I would like to know how to implement this use-case. Maybe I would like to use kind of `Array.contains` method.

### Actual results

To check if any label matches with label named 'foo1', I think I need to add more condition like `event.pull_request.labels[0].name == "foo1" or event.pull_request.labels[1].name == "foo1"`, however I believe this approach isn't best.
