### DISCUSSION TITLE
Starting builds automatically with codemagic.yaml

### DISCUSSION THREAD

**Discussion by fikretsengul** [codemagic-ci-cd/codemagic-docs#3100] [Q&A] [answered]
### If you are looking for help, please confirm the following...

- [X] I confirm I have searched the [Docs](https://docs.codemagic.io), [Codemagic Sample Projects](https://github.com/codemagic-ci-cd/codemagic-sample-projects), and GitHub [Discussions](https://github.com/orgs/codemagic-ci-cd/discussions).
- [X] I confirm the software versions on my local computer match the ones in CI environment (e.g. Xcode version, Gradle version). See [here](https://docs.codemagic.io/troubleshooting/common-android-issues/#builds-work-locally-but-fail-on-codemagic)
- [X] I confirm I am able to do a fresh clone of the repository and build the project on my local computer.

### Which mobile framework are you using?

Flutter (Dart)

### Steps to reproduce

1. Set up a repository with three branches: dev, uat, and main
2. Configure Codemagic YAML with three triggering configurations:
   - uat_triggering: Should only run when pushing/merging from dev to uat
   - prd_triggering: Should only run when pushing/merging from uat to main
   - patch_triggering: Should only run when pushing/merging from dev to main
3. Push code directly to the dev branch
4. Observe that workflows with uat_triggering and patch_triggering are triggered unexpectedly

My YAML configuration is as follows (simplified for clarity):

```yaml
  triggering:
    uat_triggering: &uat_triggering
      events:
        - push
      branch_patterns:
        # Only trigger when pushing to uat from dev (not direct dev pushes)
        - pattern: 'uat'
          include: true
          source: false
        # Exclude direct pushes to dev
        - pattern: 'dev'
          include: false
          source: false
        # Include merges from dev to uat
        - pattern: 'dev'
          include: true
          source: true
      cancel_previous_builds: true
    prd_triggering: &prd_triggering
      events:
        - push
      branch_patterns:
        # Only trigger when pushing to main from uat (not direct main pushes)
        - pattern: 'main'
          include: true
          source: false
        # Include merges from uat to main
        - pattern: 'uat'
          include: true
          source: true
        # Exclude merges from dev to main
        - pattern: 'dev'
          include: false
          source: true
      cancel_previous_builds: true
    patch_triggering: &patch_triggering
      events:
        - push
      branch_patterns:
        # Only trigger when pushing to main from dev (not direct main pushes)
        - pattern: 'main'
          include: true
          source: false
        # Exclude direct pushes to dev
        - pattern: 'dev'
          include: false
          source: false
        # Include merges from dev to main
        - pattern: 'dev'
          include: true
          source: true
        # Exclude merges from uat to main
        - pattern: 'uat'
          include: false
          source: true
      cancel_previous_builds: true
```

### Expected results

When pushing directly to the dev branch, no workflows should be triggered.
Workflows should only be triggered in the following cases:
- uat_triggering: Only when merging/pushing from dev to uat
- prd_triggering: Only when merging/pushing from uat to main
- patch_triggering: Only when merging/pushing from dev to main

### Actual results

When pushing directly to the dev branch, workflows with both uat_triggering and patch_triggering are triggered.

I've tried various combinations of include/exclude patterns and source flags, but I haven't been able to prevent workflows from triggering when pushing directly to dev.

**Comment by dtrdic** [comment, marked as answer]
Hi @fikretsengul, You're currently using the `push` event trigger, which causes workflows to run on **any** push — including direct pushes to the dev branch. That’s why you’re seeing unexpected builds.

In your case, I recommend using only `pull_request` events and enforcing conditions using the `when:` clause with attributes from the pull request webhook.

Here’s an example:
```
      triggering:
          events:
            - pull_request
          branch_patterns:
            - pattern: 'uat'
              include: true
              source: false
      when:
        condition:
           event.pull_request.head.ref == "dev"
```
With this setup:
- A build will be triggered when a pull request is opened into the uat branch.
- The build will continue only if the source branch is dev.
- Pull requests from other branches into `uat` will still trigger a build, but it will stop at the "Fetching app sources" step since the condition is not met.

![image](https://github.com/user-attachments/assets/1441238c-027c-48f2-a899-6b2b6a839746)
