### DISCUSSION TITLE
CI/CD with iOS & Query related to App Store Connect Key

### DISCUSSION THREAD

**Discussion by sonamomar0** [codemagic-ci-cd/codemagic-docs#3126] [Q&A] [answered]
### If you are looking for help, please confirm the following...

- [X] I confirm I have searched the [Docs](https://docs.codemagic.io), [Codemagic Sample Projects](https://github.com/codemagic-ci-cd/codemagic-sample-projects), and GitHub [Discussions](https://github.com/orgs/codemagic-ci-cd/discussions).
- [X] I confirm the software versions on my local computer match the ones in CI environment (e.g. Xcode version, Gradle version). See [here](https://docs.codemagic.io/troubleshooting/common-android-issues/#builds-work-locally-but-fail-on-codemagic)
- [X] I confirm I am able to do a fresh clone of the repository and build the project on my local computer.

### Which mobile framework are you using?

iOS (Swift, Objective-C)

### Steps to reproduce

I want to integrate codemagic ci/cd pipeline in my iOS project. Now i am writing script to export archive and push to testflight but it always fails. Is this issue due to **App Store Connect Key Id**. But I have uploaded certificate & profile in codemagic. 

### Expected results

So is it necessary to use App Store Connect Key or without using this i can achieve the result. If yes, then please help me out where i am wrong and help me in scripting too.

### Actual results

Build ipa file & export it on Testflight.

### Build id (optional)

683847aba2e43b77050a4f65

**Comment by dtrdic** [comment, marked as answer]
Hi @sonamomar0 when publishing to the App Store, you need a way to authenticate with your Apple Developer account. This can be done by using an `App Store Connect API key`, which consists of the `Issuer ID`, `Key ID`, and the `.p8 file`.

You can provide these credentials either through environment variables or by setting up the App Store Connect integration in Codemagic. Both approaches use the same credentials, it's just a matter of how you reference them in your codemagic.yaml.

Let's use the App Store Connect API key integration because it's cleaner and easier to manage.

1. Go to Teams > team name > Integrations > Developer Portal > Connect
2. Add your Issuer ID, Key ID, and upload the .p8 file.
3. Make sure the API key(the .p8 file) has Admin or App Manager access.
4. Then reference it in your codemagic.yaml like this:
```
workflows:
  walkthrough-workflow:
    name: Walkthrough Pipeline Building ipa
    integrations:
      app_store_connect: codemagic # This is the name you gave your App Store API key in Codemagic
```
Also, if you want to upload your .ipa to Testfligt or App Store you will have to use an Apple Distribution certificate and a distribution provisioning profile, of type `app_store` or `ad_hoc`.

Here's how your workflow would look like if you are building an ios native app
```
workflows:
  ios-native-workflow:
    name: iOS Native
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: codemagic
    environment:
      vars:
        BUNDLE_ID: "com.app.gamesapp"
        XCODE_WORKSPACE: "Walkthrough.xcworkspace" 
        XCODE_SCHEME: "Walkthrough"
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.app.gamesapp
      xcode: 16.3
      cocoapods: default
    scripts:
      - name: Install CocoaPods dependencies
        script: | 
          pod install
      - name: Set up provisioning profiles settings on Xcode project
        script: xcode-project use-profiles
      - name: Increment build number
        script: | 
          cd $CM_BUILD_DIR
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID")
          agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))
      - name: Build ipa for distribution
        script: | 
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - user_1@example.com
          - user_2@example.com
        notify:
          success: true
          failure: false
      app_store_connect:
        auth: integration
```
