### DISCUSSION TITLE
How to set the yarn > 4.x

### DISCUSSION THREAD

**Discussion by unbegrenzt** [codemagic-ci-cd/codemagic-docs#3135] [Q&A] [answered]
### If you are looking for help, please confirm the following...

- [X] I confirm I have searched the [Docs](https://docs.codemagic.io), [Codemagic Sample Projects](https://github.com/codemagic-ci-cd/codemagic-sample-projects), and GitHub [Discussions](https://github.com/orgs/codemagic-ci-cd/discussions).
- [X] I confirm the software versions on my local computer match the ones in CI environment (e.g. Xcode version, Gradle version). See [here](https://docs.codemagic.io/troubleshooting/common-android-issues/#builds-work-locally-but-fail-on-codemagic)
- [X] I confirm I am able to do a fresh clone of the repository and build the project on my local computer.

### Which mobile framework are you using?

React Native

### Steps to reproduce

scripts:
      - name: Install Corepack
        script: npm install -g corepack
      - name: Enable Corepack
        script: corepack enable
      - name: Install npm dependencies
        script: |
          yarn set version stable
          yarn install

### Expected results

The environment use yarn > 4 

### Actual results

#!/usr/bin/env bash

yarn set version stable
error This project's package.json defines "packageManager": "yarn@4.9.1". However the current global version of Yarn is 1.22.22.

Presence of the "packageManager" field indicates that the project is meant to be used with Corepack, a tool included by default with all official Node.js distributions starting from 16.9 and 14.19.
Corepack must currently be enabled by running corepack enable in your terminal. For more information, check out https://yarnpkg.com/corepack.

Build failed :|
Step 5 script Update Yarn exited with status code 1

**Comment by dtrdic** [comment, marked as answer]
Hello @unbegrenzt, to use a specific version of Yarn, just uninstall the preinstalled version and install the one you need using npm.

```
    android-workflow:
        name: Android Workflow
        max_build_duration: 120
        instance_type: mac_mini_m2
        scripts:
          - name: yarn install 
            script: |
              sudo npm uninstall -g yarn
              npm install -g yarn@4.9.1
              yarn --version
```
