### DISCUSSION TITLE
error: No profile for team

### DISCUSSION THREAD

**Discussion by divyangkhatri** [codemagic-ci-cd/codemagic-docs#3137] [Q&A]
### If you are looking for help, please confirm the following...

- [X] I confirm I have searched the [Docs](https://docs.codemagic.io), [Codemagic Sample Projects](https://github.com/codemagic-ci-cd/codemagic-sample-projects), and GitHub [Discussions](https://github.com/orgs/codemagic-ci-cd/discussions).
- [X] I confirm the software versions on my local computer match the ones in CI environment (e.g. Xcode version, Gradle version). See [here](https://docs.codemagic.io/troubleshooting/common-android-issues/#builds-work-locally-but-fail-on-codemagic)
- [X] I confirm I am able to do a fresh clone of the repository and build the project on my local computer.

### Which mobile framework are you using?

React Native

### Steps to reproduce

```
  react-native-ios:
    name: React Native iOS
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      ios_signing:
        provisioning_profiles:
          - profile: dokwallet_prod_profile
            environment_variable: DOKWALLET_DIST_PROFILE_PATH
          - profile: kiml_wallet_dist_profile
            environment_variable: KIMLWALLET_DIST_PROFILE_PATH

        certificates:
          - dokwallet_certificate
          - kimlwallet_certificate
      groups:
        - ios_appstore_vars
        - common # common env variables
      vars:
        XCODE_WORKSPACE: "coinswallet.xcworkspace"
        DOKWALLET_XCODE_SCHEME: "coinswallet"
        KIMLWALLET_XCODE_SCHEME: "kimlwallet"
        DOKWALLET_APP_ID: 1533065700
        KIMLWALLET_APP_ID: 6746929530
      node: v20
      xcode: 16.0
      cocoapods: default
    scripts:
      - name: Install yarn dependencies
        script: |
          npm run git:update && yarn install
      - name: Install CocoaPods dependencies
        script: |
         cd ios && pod install
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles --warn-only --verbose
      - name: Dok Wallet Set Version and build number
        script: |
          cd ios
          agvtool new-version -all $DOKWALLET_IOS_BUILD_NUMBER
          agvtool new-marketing-version $DOKWALLET_IOS_VERSION
      - name: Dok Wallet Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/ios/$XCODE_WORKSPACE" \
            --scheme "$DOKWALLET_XCODE_SCHEME"

      - name: KIML Wallet Set Version and build number
        script: |
          cd ios
          agvtool new-version -all $KIMLWALLET_IOS_BUILD_NUMBER
          agvtool new-marketing-version $KIMLWALLET_IOS_VERSION
      - name: KIML Wallet Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/ios/$XCODE_WORKSPACE" \
            --scheme "$KIMLWALLET_XCODE_SCHEME"
      - name: Publish Dok Wallet to App Store Connect
        script: |
          echo $DOKWALLET_AUTH_PRIVATE_KEY > DOKWALLET_PRIVATE_KEY.p8
          app-store-connect publish \
            --path build/ios/ipa/Dok_Wallet.ipa \
            --app-id $DOKWALLET_APP_ID \
            --private-key @file:DOKWALLET_PRIVATE_KEY.p8 \
            --key-id $DOKWALLET_AUTH_KEY_ID \
            --issuer-id $DOKWALLET_ISSUER_ID \
            --submit-to-testflight

      - name: Publish KIML Wallet to App Store Connect
        script: |
          echo $KIMLWALLET_AUTH_PRIVATE_KEY > KIMLWALLET_PRIVATE_KEY.p8
          app-store-connect publish \
            --path build/ios/ipa/KIML_Wallet.ipa \
            --app-id $KIMLWALLET_APP_ID \
            --private-key @file:KIMLWALLET_PRIVATE_KEY.p8 \
            --key-id $KIMLWALLET_AUTH_KEY_ID \
            --issuer-id $KIMLWALLET_ISSUER_ID \
            --submit-to-testflight

    artifacts:
      - build/ios/ipa/*.ipa
      - /Users/builder/*.plist
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      slack:
        channel: codemagic-dokwallet
        notify_on_build_start: true
        notify:
          failure: true
          success: true

```
The above is a workflow in a YAML file.
I’m trying to build and upload two schemas in a single React Native project within single codemagic workflow.
One schema is coinswallets for the “Dok Wallet”, and the other is kimlwallet for the “KIML Wallet”.

Both Dok Wallet and KIML Wallet are deployed under separate Apple Developer accounts, which means they have different team_ids and certificates.

### Expected results

The build should work properly and successfully upload to App Store TestFlight.

### Actual results

I’m getting the following error:
```
Build failed :|
Step 10 script `KIML Wallet Build ipa for distribution` exited with status code 65.
```

In the build logs, the error is:

```
error: No profile for team '9HJ6G8C9BU' matching 'kiml_wallet_dist_profile' found: Xcode couldn't find any provisioning profiles matching '9HJ6G8C9BU/kiml_wallet_dist_profile'.
```

Here, 9HJ6G8C9BU is the team ID for Dok Wallet, and N9US926Q47 is the team ID for KIML Wallet.

I’m not sure why the Dok Wallet team ID (9HJ6G8C9BU) is being used when building the KIML Wallet.
How can I fix this issue?

### Build id (optional)

6844150ea73575dd68a42d5d

**Comment by dtrdic** [comment]
Hey @divyangkhatri I recommend a different approach—using Codemagic build inputs combined with automatic code signing. This lets you define a single, flexible workflow that dynamically adapts based on the selected scheme and variable group.

Each build can target either app (Dok Wallet or KIML Wallet) by simply selecting the desired scheme through the UI or API trigger.
Environment variables, provisioning profiles, and signing identities are separated by using different variable groups.
Here's what your workflow would look like
```
react-native-ios:
      name: React Native iOS 
      max_build_duration: 120
      instance_type: mac_mini_m2
      labels:
        - build_inputs
      inputs:
        variableGroupName:
            description: Select the scheme to build
            type: choice
            options: ["Dok Wallet", "KIML Wallet"]
            default: Dok Wallet
      integrations:
        app_store_connect: kimelview #<--This is the name of your App Store Connect API key. It contains the Issuer ID, Key ID, and your .p8 private key file.
      environment:
        groups:
          - ${{ inputs.variableGroupName }}
        xcode: 16.2
      scripts:
          - name: Set up keychain to be used for code signing using Codemagic CLI 'keychain' command
            script: keychain initialize
          - name: Fetch signing files
            script: | 
              app-store-connect fetch-signing-files "$BUNDLE_ID" \
                --type IOS_APP_STORE \
                --create
          - name: Set up signing certificate
            script: keychain add-certificates
          - name: Set up code signing settings on Xcode project
            script: xcode-project use-profiles
          - name: Install Dependencies
            script: |
              npm install
          - name: Install CocoaPods dependencies
            script: |
              cd ios
              pod install
          - name: Increment build number 
            script: |
              agvtool new-marketing-version 1.0.$(($BUILD_NUMBER))
              agvtool new-version -all $(($BUILD_NUMBER))
          - name: Build ipa for distribution
            script: |
              xcode-project build-ipa \
                --workspace "$CM_BUILD_DIR/ios/$XCODE_WORKSPACE" \
                --scheme "$XCODE_SCHEME" \
                --archive-flags="-destination 'generic/platform=iOS'"              
      artifacts:
          - build/ios/ipa/*.ipa
          - /tmp/xcodebuild_logs/*.log
          - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
          - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
      publishing:
        app_store_connect: 
          auth: integration
```
Just define the `variableGroup` with values specific to each scheme(one for `Doc wallet` and one for `Kim wallet`).
For example, define variables like `APP_ID`, `SCHEME_NAME`, `XCODE_WORKSPACE`, `BUNDLE_ID`, and `CERTIFICATE_PRIVATE_KEY` for each app to enable automatic code signing.

![image](https://github.com/user-attachments/assets/e983f720-dff6-4b40-beaf-33480041f6ca)

When triggering a build manually, Codemagic will prompt you to select which scheme to build:
![image](https://github.com/user-attachments/assets/4aa167ad-361f-4153-bac8-c035f4675b22)
