### DISCUSSION TITLE
Native iOS check coverage unit test

### DISCUSSION THREAD

**Discussion by jdelcastillos** [codemagic-ci-cd/codemagic-docs#939] [Q&A]
Hi,

I want to check the coverage of an iOS Native application. But i doesn't know how to check the result of the coverage. Can you help me, thanks.

This is how my yaml looks like:

```yaml
workflows:
    native-ios:
        name: iOS
        max_build_duration: 120
        instance_type: mac_mini
        environment:
            vars:
               XCODE_WORKSPACE: "ABC/ABC.xcodeproj"
               XCODE_SCHEME: "ABC"
            xcode: 13.0
            cocoapods: default
        scripts:
            - name: Build ipa for distribution
              script: |
                                xcodebuild build -project "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO 
            - name: iOS test
              script: |
                                xcode-project run-tests \
                                --workspace ABC.xcodeproj \
                                --scheme ABC \
                                --device "iPhone 12"
              test_report: build/ios/test/*.xml
        artifacts:
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.xml
```
