### DISCUSSION TITLE
How to distribute only android .apk to firebase, but not the iOS

### DISCUSSION THREAD

**Discussion by RobertApikyan** [codemagic-ci-cd/codemagic-docs#943] [Q&A] [answered]
Is it possible to set Firebase distribution for only Android? As usually for iOS, I'm using TestFlight and do not need it to be published to Firebase one more time.

**Comment by K-Codemagic** [comment, marked as answer]
Hi, you can just mention the publishing for Android:

```
publishing:
  firebase:
    firebase_token: $FIREBASE_TOKEN
    android:
      app_id: x:xxxxxxxxxxxx:android:xxxxxxxxxxxxxxxxxxxxxx
      groups:
        - androidTesters
        - ...
      artifact_type: 'apk' # Replace with 'aab' to only publish the Android app bundle
```

Check [this](https://docs.codemagic.io/yaml-publishing/firebase-app-distribution/#distribution-to-firebase) document for more information.
