### ISSUE TITLE
Docs don't include explanation of how to use target: true when triggering builds with pull requests

### ISSUE THREAD

**Issue by nevercode-kevin** [codemagic-ci-cd/codemagic-docs#1263]
The documentation does not show how to use `target: true` when tracking changes to specific branches with pull requests. 

For example, it is possible to do the following when configuring branch patterns for a pull request:

```
triggering:
  events:
    - pull_request
  branch_patterns:
    - pattern: develop
      target: true
```

`/yaml-running-builds/starting-builds-automatically/` should be update to show how this is used.
