### ISSUE TITLE
Fails to fetch pub get from private repository

### ISSUE THREAD

**Issue by ryomoro** [codemagic-ci-cd/codemagic-docs#577]
I have a flutter project which is fetching a package from a private repo on Github such as:
```
flutter_common:
    git:
      url: git@github.com:hoge/flutter-common.git
      ref: master
```
When I run `flutter pub get` on Github Actions which I set SSH key setting of the repository, It works.

But running on Codemagic, it fails. Even if I set [this setting](https://docs.codemagic.io/configuration/access-private-git-submodules/
). I set the SSH private key of generating on my computer  in an environment variable in your Codemagic configuration file. 

How can I run `flutter pub get` with a private repository on Codemagic? Anyone has a solution?
